"""Simplified municipal boundary polygons for two-tier city detection.

The coarse CITY_BOUNDS bboxes catch metro-adjacent suburbs (Chestermere is
inside Calgary's box; Burnaby, Mississauga, St. Albert sit inside their
neighbours'); a bbox hit is therefore confirmed against these polygons before
a city connector is chosen. Files are generated by
scripts/build_city_boundaries.py (run in the backend container) and committed;
regenerate after annexations. Each polygon is buffered outward ~150 m before
simplification, so containment is permissive at the true edge — never at the
suburb scale.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from importlib import resources

from shapely.geometry import shape
from shapely.prepared import PreparedGeometry, prep
from shapely.validation import make_valid

logger = logging.getLogger(__name__)


@lru_cache(maxsize=None)
def get_boundary(city_id: str) -> PreparedGeometry | None:
    """Prepared municipal boundary for ``city_id``, or None if no file is shipped.

    None means "no polygon to confirm against" — detect_city treats the bbox
    hit as final, so a missing file degrades to the old behavior, never to a
    false rejection.
    """
    try:
        raw = resources.files(__package__).joinpath(f"{city_id}.geojson").read_text("utf-8")
    except (FileNotFoundError, ModuleNotFoundError, NotADirectoryError):
        return None
    try:
        geometry = shape(json.loads(raw)["geometry"])
        if not geometry.is_valid:
            geometry = make_valid(geometry)
        return prep(geometry)
    except Exception:  # noqa: BLE001 — a corrupt file must not break detection
        logger.warning("Boundary file for %s is unreadable — falling back to bbox", city_id)
        return None
