"""Promote visually accepted Meshy catalog objects and generate runtime registry data."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wave", action="append", nargs=3, metavar=("BATCH", "REVIEW", "ARTIFACT_ROOT"), required=True)
    return parser.parse_args()


def ts_key(asset_id: str) -> str:
    words = re.split(r"[^a-zA-Z0-9]+", asset_id)
    return "v3" + "".join(word[:1].upper() + word[1:] for word in words if word)


def q(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(q(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{key}: {q(item)}" for key, item in value.items()) + " }"
    return str(value)


def main() -> None:
    options = parse_args()
    repo = Path(__file__).resolve().parents[2]
    public_root = repo / "frontend/public/park-kits/meshy-catalog-v3"
    records: list[dict[str, Any]] = []
    copied: list[str] = []

    for batch_arg, review_arg, artifact_arg in options.wave:
        batch = json.loads(Path(batch_arg).resolve().read_text(encoding="utf-8"))
        review = json.loads(Path(review_arg).resolve().read_text(encoding="utf-8"))
        accepted = {item["assetId"] for item in review["accepted"]}
        catalog_ids = {item["assetId"] for item in batch["objects"]}
        unknown = accepted - catalog_ids
        if unknown:
            raise ValueError(f"Review accepts IDs absent from {batch_arg}: {sorted(unknown)}")
        artifact_root = Path(artifact_arg).resolve()
        for item in batch["objects"]:
            if item["assetId"] not in accepted:
                continue
            source = artifact_root / item["assetId"] / f"{item['assetId']}-clean.glb"
            if not source.is_file():
                raise FileNotFoundError(source)
            family = item["family"]
            destination = public_root / family / f"{item['assetId']}.glb"
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            records.append({**item, "url": f"/park-kits/meshy-catalog-v3/{family}/{item['assetId']}.glb"})
            copied.append(str(destination.relative_to(repo)).replace("\\", "/"))

    keys: set[str] = set()
    lines = [
        "/** Generated by tools/park_skin_compiler/promote_meshy_park_object_catalog_v3.py.",
        " * Every entry passed archetype-reference and normalized-runtime visual review. */",
        "import type { ParkMeshyArchetypeAsset } from './parkMeshyArchetypeAssets';",
        "",
        "export const PARK_MESHY_ARCHETYPE_ASSETS_V3 = Object.freeze({",
    ]
    for item in sorted(records, key=lambda record: record["assetId"]):
        key = ts_key(item["assetId"])
        if key in keys:
            raise ValueError(f"Duplicate TypeScript key {key}")
        keys.add(key)
        lines.extend([
            f"  {key}: Object.freeze({{",
            f"    id: {q(item['assetId'])},",
            f"    url: {q(item['url'])},",
            f"    archetypeId: {q(item['archetypeId'])},",
            f"    variantIds: Object.freeze({q(item['variantIds'])}),",
            f"    dimensionsM: Object.freeze({q(item['dimensionsM'])}),",
            f"    placementRole: {q(item['placementRole'])},",
            "    sourceKind: 'meshy_multiview_archetype_reference' as const,",
            "    people: false as const,",
            "    largeBuildings: false as const,",
            f"    placement: Object.freeze({q(item['placement'])}),",
            "  }),",
        ])
    lines.extend([
        "}) satisfies Readonly<Record<string, ParkMeshyArchetypeAsset>>;",
        "",
    ])
    registry = repo / "frontend/src/components/viewer/globe/parkMeshyArchetypeAssetsV3.ts"
    registry.write_text("\n".join(lines), encoding="utf-8")
    report = {
        "promotedCount": len(records),
        "registry": str(registry.relative_to(repo)).replace("\\", "/"),
        "files": copied,
    }
    report_path = repo / "tools/park_skin_compiler/meshy_park_object_catalog_v3_promotion.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
