"""City Connector — determines the current city and serves its datasets.

Adding a city: create cities/<city>/ with a connector subclass + DatasetSpecs,
add its bounds + a committed boundary polygon here (generated by
scripts/build_city_boundaries.py). Planning Agents never change (they consume
DNA only).
"""

from __future__ import annotations

from shapely.geometry import Point, Polygon

from app.services.city_connector import boundaries
from app.services.city_connector.base import CityConnector
from app.services.city_connector.cities.calgary import CalgaryConnector
from app.services.city_connector.cities.edmonton import EdmontonConnector
from app.services.city_connector.cities.osm_fallback import OSMFallbackConnector

# (lon_min, lat_min, lon_max, lat_max) — coarse municipal bounds, a cheap
# PREFILTER only. A bbox hit is confirmed against the committed boundary
# polygon: metro-adjacent suburbs (Chestermere in Calgary's box; Burnaby,
# Mississauga, St. Albert in their neighbours') would otherwise get a city
# connector whose datasets all return empty — silently worse than the OSM
# fallback's roads/buildings/parks.
CITY_BOUNDS: dict[str, tuple[float, float, float, float]] = {
    "calgary": (-114.35, 50.80, -113.80, 51.25),
    "edmonton": (-113.75, 53.35, -113.25, 53.75),
}

_CONNECTORS: dict[str, type[CityConnector]] = {
    "calgary": CalgaryConnector,
    "edmonton": EdmontonConnector,
    "osm": OSMFallbackConnector,
}


def detect_city(lon: float, lat: float) -> str:
    for city_id, (lon_min, lat_min, lon_max, lat_max) in CITY_BOUNDS.items():
        if not (lon_min <= lon <= lon_max and lat_min <= lat <= lat_max):
            continue
        boundary = boundaries.get_boundary(city_id)
        if boundary is None or boundary.contains(Point(lon, lat)):
            return city_id
    return "osm"


def get_connector(city_id: str) -> CityConnector:
    connector_cls = _CONNECTORS.get(city_id, OSMFallbackConnector)
    return connector_cls()


def get_connector_for_site(site_polygon_wgs84: Polygon) -> CityConnector:
    centroid = site_polygon_wgs84.centroid
    return get_connector(detect_city(centroid.x, centroid.y))
