function aa(a){chrome.tabs.query({active:!0,currentWindow:!0},function(b){(b=b[0])&&b!==void 0&&a(b)})};String.prototype.trim=String.prototype.trim||function(){return this.replace(/^\s+|\s+$/g,"")};String.format=function(){for(var a=arguments[0],b=0;b<arguments.length-1;b++)a=a.replace(new RegExp("\\{"+b+"\\}","gm"),arguments[b+1]);return a};String.prototype.endsWith=function(a){return this.substr(this.length-a.length)===a};String.prototype.startsWith=function(a){return this.substr(0,a.length)===a};let n={get:function(){return{}}};function ba(a){chrome.storage.sync.get({key:n.get()},function(b){a(b.key)})};function q(a){ba(function(b){if(b.from===void 0||b.from==null||b.to===void 0||b.to==null)b=n.get();a(b)})};function ca(a){da(b=>{t(a,b)?a.g=b:u(a)})}function ea(a,b){return`https://api.cognitive.microsofttranslator.com/${a}?api-version=3.0&${b}`}function w(a){return a.message||"An error has occurred."}function fa(a){var b=ha;b.l?a(b.l,b.l,""):fetch(ea("languages","scope=translation")).then(c=>c.json()).then(c=>{if(c.error)a("","",w(c.error));else{c=c.translation;var d={};for(let f in c)d[f]=c[f].nativeName;b.l=d;a(d,d,"")}}).catch(c=>{a("","",w(c))})}
function t(a,b){return b&&b.state===a.i.A&&Date.now()-b.timestamp<36E5}function ia(a,b,c,d,f,e){const g={};g.url=`https://www.bing.com/${b}?isVertical=1&IG=${a.g.ig}&IID=${a.g.iid}`;g.data=`&${c}=${encodeURIComponent(d)||"auto-detect"}&to=${encodeURIComponent(f)}&text=${encodeURIComponent(e)}&token=${a.g.token}&key=${a.g.key}`;g.headers={"Content-Type":"application/x-www-form-urlencoded"};return g}
function u(a){a.g={state:a.i.I};fetch("https://www.bing.com/translator").then(b=>{if(b.status<200||b.status>=300)throw Error(`response.status: ${b.status}`);return b.text()}).then(b=>{b=ja(a,b);ka(a,b)}).catch(()=>{a.g&&(a.g.state=a.i.H)})}function la(a,b,c,d,f){const e={};e.url=ea(b,`from=${encodeURIComponent(c)}&to=${encodeURIComponent(d)}`);e.data=JSON.stringify([{Text:f}]);e.headers={"Ocp-Apim-Subscription-Key":a.m[a.j],"Content-Type":"application/json"};return e}
function qa(a,b,c,d,f,e){a=t(a,a.g)?ia(a,"tlookupv3","from",b,c,d):la(a,"dictionary/lookup",b,c,d);fetch(a.url,{method:"POST",headers:a.headers,body:a.data}).then(g=>{if(g.status<200||g.status>=300)throw Error();return g.json()}).then(g=>{if(g.statusCode)throw Error();if(g.error)throw Error();g=g[0];g.translations&&g.translations.length>0?(g=ra(b,g),e(g)):e(f)}).catch(()=>{e(f)})}
function ra(a,b){let c=[];var d=b.translations;do{let f=d[0].posTag,e=sa(d,f);c.push(ta(e,f));d=d.filter(g=>g.posTag!==f)}while(d.length);return[{text:b.displaySource,lang:a,definitions:c}]}function sa(a,b){return a.filter(c=>c.posTag===b)}function ta(a,b){a=a.map(c=>{let d=c.backTranslations.map(f=>f.displayText).join(", ");return{definition:`${c.displayTarget} (${d})`}});return{poses:[b.toLowerCase()],senses:a}}
function ja(a,b){const c={};c.timestamp=Date.now();var d=y('IG:"','"',b);if(!d)return c;c.ig=d;d=y('data-iid="','"',b);if(!d)return c;c.iid=d;b=y("params_AbusePreventionHelper = ",";",b);if(!b)return c;b=JSON.parse(b);if(!b||b.length<2)return c;c.key=b[0];c.token=b[1];c.state=a.i.A;return c}function ka(a,b){a.g=b;q(function(c){c.msCreds=b;chrome.storage.sync.set({key:c},void 0)})}function da(a){q(function(b){a(b.msCreds)})}
function y(a,b,c){a=(new RegExp(`${a}(.*?)${b}`)).exec(c);return!a||a.length<=1?null:a[1]}
class ua{constructor(){var a="f122028fc68f468cb0f247f0224c5bd9 d689236971d547d1af7290eba5f31909 cd1000838f1f447fbac42c39a0a6bb03 ddea3270e79c4e2eb6f800053b516807 c45bd509cca34d78bd660740705bdd9f e88478dcd27a41aaa27cba21fd77c150 a1bf90476b444ce39f101a0fd79995d6 6627d5ca631e489aa06ee77066248e58 a31df1f51942432fbed27783ea6cd3aa 88d0ea0917564aa6a802732207b5723c fb7b7cbcc8cc440abcb3caaa1a8ab79c 3dc6c5b5f4e64cb8ba18e7d44dff6caf".split(" ");for(let b=a.length-1;b>0;b--){const c=Math.floor(Math.random()*
(b+1));[a[b],a[c]]=[a[c],a[b]]}this.m=a;this.j=0;ca(this);this.l=null}translate(a,b,c,d,f){!f&&t(this,this.g)?f=ia(this,"ttranslatev3","fromLang",a,b,c):(!f&&u(this),f=la(this,"translate",a,b,c));fetch(f.url,{method:"POST",headers:f.headers,body:f.data}).then(e=>{if(e.status<200||e.status>=300)throw Error();return e.json()}).then(e=>{if(e.statusCode)e.statusCode===205&&u(this),this.translate(a,b,c,d,!0);else if(e.error){var g;if(g=a!=="")g=e.error,g=g!==void 0&&g.code==400023;if(g)this.translate("",
b,c,d);else{e=e.error;if(g=e!==void 0&&e.code==401E3||e!==void 0&&e.code==403001)this.j++,g=this.j<this.m.length,g||(this.j=0);g?this.translate(a,b,c,d):d(w(e))}}else{e=e[0];if(!e)throw Error();g=e.translations[0];if(!g)throw Error();g=g.text;c.includes(" ")?d(g):qa(this,a||e.detectedLanguage.language,b,c,g,d)}}).catch(e=>{d(w(e))})}i(){return{H:0,I:1,A:2}}};function va(a,b){return`https://${"translate-pa"}.googleapis.com/${"v1"}/${a}?key=${"AIzaSyDLEeFI5OtFBwYBIoK_jj5m32rZK5CkCXA"}&${b}`}function z(a){return a.message||"An error has occurred."}function wa(a,b){const c={};for(const d of b)b=d.language,b!==a.j&&(c[b]=d.name);return c}
function xa(a){var b=ya;b.g&&b.i?a(b.g,b.i,""):fetch(va("supportedLanguages","client=gtx&display_language=en")).then(c=>c.json()).then(c=>{c.error?a("","",z(c.error)):(b.g=wa(b,c.sourceLanguages),b.i=wa(b,c.targetLanguages),a(b.g,b.i,""))}).catch(c=>{a("","",z(c))})}
function za(a){const b=a.translation;var c=a.bilingualDictionary;if(!c||c.length===0)return b;c=c.map(d=>{const f=d.pos;d=d.entry.map(e=>{const g=e.reverseTranslation||[];return{definition:`${e.word}${g.length>0?` (${g.join(", ")})`:""}`}});return{pos:[f],senses:d}});return[{text:b,lang:a.sourceLanguage,definitions:c}]}
class Aa{constructor(){this.i=this.g=null}translate(a,b,c,d){a=`params.client=${"gtx"}&query.source_language=${encodeURIComponent(a||this.j)}&query.target_language=${encodeURIComponent(b)}&query.text=${encodeURIComponent(c)}&data_types=TRANSLATION&data_types=BILINGUAL_DICTIONARY_FULL`;fetch(va("translate",a)).then(f=>f.status<200||f.status>=300?f.json().then(e=>{throw Error(JSON.stringify(e)||`${f.status}`);}):f.json()).then(f=>{if(f.error)throw Error(f.error);f=za(f);d(f)}).catch(f=>{d(z(f))})}get j(){return"auto"}}
;function A(a){switch(a){case n.B:return{en:"English"};case n.C:return{ar:"Arabic","pt-BR":"Brazilian Portuguese","zh-CN":"Chinese (Simplified)","zh-TW":"Chinese (Traditional)",cs:"Czech",nl:"Dutch","en-uk":"English (UK)",en:"English (US)",fr:"French",de:"German",hi:"Hindi",it:"Italian",ja:"Japanese",ko:"Korean",ru:"Russian",sk:"Slovak",es:"Spanish",tr:"Turkish"};case n.o:return{ar:"Arabic","pt-BR":"Brazilian Portuguese",bg:"Bulgarian","zh-CN":"Chinese (Simplified)","zh-TW":"Chinese (Traditional)",
cs:"Czech",da:"Danish",nl:"Dutch","en-uk":"English (UK)",en:"English (US)",fi:"Finnish",fr:"French",de:"German",el:"Greek",he:"Hebrew",hi:"Hindi",hu:"Hungarian",id:"Indonesian",it:"Italian",ja:"Japanese",ko:"Korean",no:"Norwegian",pl:"Polish",pt:"Portuguese",ro:"Romanian",ru:"Russian",sk:"Slovak",es:"Spanish",sv:"Swedish",th:"Thai",tr:"Turkish",uk:"Ukrainian",vi:"Vietnamese"};default:return{}}}
function Ba(a){a=a.dictionaryData;if(!a)return B.g;let b=[];a[0].entries.forEach(c=>{var d=c.headword,f,e=c.etymology;e&&e.etymology&&(f=e.etymology.text);var g;c.phonetics&&c.phonetics.length>0&&(g=c.phonetics.map(l=>{var m=l.oxfordAudio;m&&m.startsWith("//")&&(m=`https:${m}`);return{text:l.text,audio:m}}));let k=[];e=c.senseFamilies;let h=c.subentries;e?e.forEach(l=>{var m=[];let p=l.morphUnits;p&&p.forEach(r=>{m.push({pos:r.formType.description,form:r.wordForm})});let x=[];l.senses.forEach(r=>
{let ma=[],na=[],I=[],oa=[],pa=r.thesaurusEntries;pa&&pa.forEach(v=>{ma.push(...Ca(v,"synonyms"));na.push(...Ca(v,"antonyms"));I.push(...(v.examples||[]))});I.length<=0&&r.exampleGroups&&r.exampleGroups.forEach(v=>{I.push(...(v.examples||[]))});r.subsenses&&r.subsenses.forEach(v=>{oa.push(v.conciseDefinition)});x.push({definition:r.definition.text,synonyms:[...(new Set(ma))],antonyms:[...(new Set(na))],examples:[...(new Set(I))],subsenses:[...(new Set(oa))]})});var J;(l=l.partsOfSpeech)&&(J=l.map(r=>
r.value));k.push({poses:J,morphemes:m,senses:x})}):h&&h.forEach(l=>{d=l.lemma;let m=[];l.senseFamily.senses.forEach(p=>{m.push({definition:p.definition.text});(p=p.subsenses)&&p.forEach(x=>{m.push({definition:x.definition.text})})});k.push({poses:[l.type],senses:m})});b.push({text:d,etymology:f,lang:c.corpus.language,phonetics:g,definitions:k})});return b}function Ca(a,b){let c=[];(a=a[b])&&a.forEach(d=>{(d=d.nyms)&&d.forEach(f=>{f.nym&&c.push(f.nym)})});return c}
function Da(a){let b=[];if(!a||a.length<=0)return"An error has occurred.";if(a.title)return a.title;a.forEach(c=>{var d=c.word,f;c.phonetics&&c.phonetics.length>0?f=c.phonetics.map(g=>({text:g.text,audio:g.audio})):c.phonetic&&(f=[{text:c.phonetic,audio:null}]);let e=[];(c=c.meanings)&&c.forEach(g=>{let k=[];g.definitions.forEach(h=>{let l=[];h.example&&l.push(h.example);k.push({definition:h.definition,examples:l,synonyms:h.synonyms,antonyms:h.antonyms})});e.push({poses:[g.partOfSpeech],senses:k})});
b.push({text:d,lang:void 0,phonetics:f,definitions:e})});return b}
class B{static get g(){return"No Definitions Found"}constructor(a,b,c,d){this.g=a;this.j=b;this.l=c;this.i=d}s(a,b,c){a=encodeURIComponent(a);fetch(`https://${this.g}.googleapis.com/${this.j}?term=${a}&language=${b}&corpus=${({en:"en-US","en-uk":"en"})[b]||b}&key=${this.l}`,{method:"GET",headers:{"x-referer":`chrome-extension://${this.i}`}}).then(d=>d.status<200||d.status>=300?d.json().then(f=>{throw Error(JSON.stringify(f)||`response.status: ${d.status}`);}):d.json()).then(d=>{if(d.status<200||d.status>=
300){switch(d.status){case 404:d=B.g;break;default:d="An error has occurred."}c(d)}else d=Ba(d),c(d)}).catch(()=>{c("An error has occurred.")})}m(a,b,c){a=encodeURIComponent(a);fetch(`https://${this.g}.dictionaryapi.dev/${this.j}/${b}/${a}`,{method:"GET",headers:{"x-referer":`chrome-extension://${this.i}`}}).then(d=>d.json()).then(d=>{d=Da(d);c(d)}).catch(()=>{c("An error has occurred.")})}};const Ea=[239,187,191];function Fa(a){return Ea.every((b,c)=>a.charCodeAt(c)===b)}
function Ga(a){function b(k){let h={type:"message",data:""};k.split("\n").forEach(l=>{l.startsWith("event: ")?e=l.slice(6):l.startsWith("data: ")?g+=l.slice(6)+"\n":l.startsWith("id: ")?f=l.slice(3):l.startsWith("retry: ")&&(l=parseInt(l.slice(6),10),isNaN(l)||a({type:"reconnect-interval",value:l}))});e&&(h.type=e);g?h.data=g.slice(0,-1):delete h.data;f&&(h.id=f);e=void 0;g="";f=void 0;return h}let c="",d=!0,f=void 0,e=void 0,g="";return{L:function(k){d&&Fa(k)&&(k=k.slice(Ea.length),d=!1);c+=k;k=
c.split("\n\n");c=k.pop();k.forEach(h=>{(h=b(h))&&a(h)})},reset:function(){c="";e=void 0;g="";f=void 0}}};function C(a,b,c){(a=a.j[b])&&a.forEach(d=>d(c))}function D(a,b,c){a.j[b]||(a.j[b]=[]);a.j[b].push(c)}
class Ha{constructor(a,b){this.l=a;this.socket=null;this.j={};this.g=b;this.i=this.i.bind(this);this.g&&this.g.addEventListener("abort",this.i)}connect(){this.g&&this.g.aborted||(this.socket=new WebSocket(this.l),this.socket.onopen=()=>{C(this,"open")},this.socket.onerror=a=>{C(this,"error",a)},this.socket.onclose=a=>{C(this,"close",a);this.g&&this.g.removeEventListener("abort",this.i)},this.socket.onmessage=a=>{a:{let b;try{b=JSON.parse(a.data)}catch(c){a=void 0;break a}b.type==="http.response.body"&&
(a=atob(b.body).trim().replace(/^data: /,""),C(this,"message",a));a=void 0}return a})}close(){this.socket&&this.socket.readyState!==WebSocket.CLOSED&&this.socket.close()}i(){this.close()}};function E(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a==="x"?b:b&3|8).toString(16)})}async function Ia(){const a=await fetch("https://chatgpt.com/api/auth/session");if(a.status===403)throw Error(F.g);return(await a.json())?.accessToken}async function Ja(a){const b=""+Math.random();if(!a.cache.has(b)){const c=await Ka(a,b,"0");a.cache.set(b,c)}return"gAAAAAC"+a.cache.get(b)}
async function La(a){try{const b=await Ja(a),c=await (await a.request(a.token,"POST","/sentinel/chat-requirements",{p:b})).json();if(c.token)return c;throw Error();}catch(b){throw Error();}}function Ma(a,b){b={"Content-Type":"application/json",...(b?{Authorization:`Bearer ${b}`}:{}),"Oai-Device-Id":a.deviceId,"Oai-Language":"en-US"};a.m&&(b["chatgpt-account-id"]=a.m);return b}
function Na(a,b,c){const {onMessage:d,...f}=c;return fetch(b,f).then(async e=>{if(!e.ok){var g=await e.json().catch(()=>({}));if(g.code==="token_expired")throw Error(F.i);throw Error(Object.keys(g).length?JSON.stringify(g):`${e.status} ${e.statusText}`);}if(e.headers.get("content-type").includes("text/event-stream")){const k=e.body.getReader(),h=new TextDecoder,l=Ga(m=>{m.type==="message"&&m.data&&d(m.data)});return k.read().then(function J({done:p,value:x}){if(!p)return p=h.decode(x,{stream:!0}),
l.L(p),k.read().then(J)})}if(!e.headers.get("content-type").includes("application/json"))throw Error();e=await e.json();g=e?.wss_url;if(!e||!g)throw Error();a.g||(a.g=new Ha(g,a.j.signal),a.g.connect());D(a.g,"error",k=>{throw k;});D(a.g,"message",k=>{d(k)});D(a.g,"close",()=>{})})}
async function Oa(a,b){return new Promise((c,d)=>{const f=e=>{e instanceof DOMException&&e.name==="AbortError"?(a.g&&(a.g.close(),a.g=null),c()):d(e)};try{const e=Ma(a,a.token);e.accept="text/event-stream";e["Openai-Sentinel-Chat-Requirements-Token"]=b.J;b.D&&(e["Openai-Sentinel-Arkose-Token"]=b.D);b.G&&(e["Openai-Sentinel-Proof-Token"]=b.G);Na(a,`https://chatgpt.com/backend-${a.token?"api":"anon"}/conversation`,{method:"POST",headers:e,body:JSON.stringify({action:"next",conversation_mode:{kind:"primary_assistant"},
force_paragen:!1,force_rate_limit:!1,history_and_training_disabled:!0,messages:[{author:{role:"user"},content:{content_type:"text",parts:[b.prompt]},id:E()}],model:a.model,parent_message_id:E(),suggestions:[]}),signal:a.j.signal,onMessage:function(g){if(g==="[DONE]")b.onEvent({type:"done"}),a.g&&(a.g.close(),a.g=null),c();else{try{var k=JSON.parse(g)}catch(h){f(h);return}if(g=k.error)f(Error(g));else if(k.message?.author?.role==="assistant"&&(g=k.message?.content?.parts?.[0]))b.onEvent({type:"answer",
data:{text:g,messageId:k.message?.id,conversationId:k.conversation_id}})}}}).catch(f)}catch(e){f(e)}})}async function Pa(a){try{return(await (await a.request(a.token,"GET","/accounts/check/v4-2023-04-27")).json())?.accounts}catch(b){}}async function Qa(a){try{const b=await (await a.request(a.token,"GET","/models")).json();if(b?.default_model_slug)return b.default_model_slug;if(b?.models?.[0]?.slug)return b.models[0].slug;throw Error();}catch(b){return"text-davinci-002-render-sha"}}
async function Ka(a,b,c){return async function(d,f,e){const g=performance.now();for(let h=0;h<5E5;h++){e[3]=h;e[9]=Math.round(performance.now()-g);var k=JSON.stringify(e);k=btoa(String.fromCharCode(...(new TextEncoder).encode(k)));if(sha3_512(d+k).slice(0,f.length)<=f)return k}return"wQ8Lk5FbGpA2NcR9dShT6gYjU7VxZ4De"}(b,c,[navigator.hardwareConcurrency+a.l?.w||1920+a.l?.h||1080,(new Date).toString(),a.l?.hsl||4294705152,0,navigator.userAgent,"","",navigator.language,navigator.languages.join(","),
0])}async function Ra(a,b,c){a.cache.has(b)||(c=await Ka(a,b,c),a.cache.set(b,c));return"gAAAAAB"+a.cache.get(b)}async function Sa(){var a=chrome.runtime.getURL("PHT/offscreen/offscreen.html");return"getContexts"in chrome.runtime?!!(await chrome.runtime.getContexts({contextTypes:["OFFSCREEN_DOCUMENT"],documentUrls:[a]})).length:await (await globalThis.clients.matchAll()).some(b=>b.url.includes(chrome.runtime.id))}
async function Ta(a,b,c){await Sa()||(a.s||(a.s=chrome.offscreen.createDocument({url:"PHT/offscreen/offscreen.html",reasons:[chrome.offscreen.Reason.IFRAME_SCRIPTING],justification:"generating token using offscreen script"})),await a.s,a.s=null);return await chrome.runtime.sendMessage({cd:c,type:b,target:"offscreen"})}function Ua(a){const b=[F.g,F.j,F.i];return a&&b.includes(a.message)}
async function Va(a){var b=a.i["default"]?.features;b&&b.length&&b.includes("shared_websocket")&&(b=await (await a.request(a.token,"POST","/register-websocket")).json(),b.wss_url&&(a.g=new Ha(b.wss_url,a.j.signal),a.g.connect()))}
async function Wa(a,b){var c=Xa;try{let d=null;c.token||c.i||(c.token=await Ia());c.i||(c.i=await Pa(c),c.i?.["default"]?.account?.account_id&&(c.m=c.i["default"].account.account_id));c.i&&await Va(c);c.model||(c.model=await Qa(c));c.l||(c.l=await Ta(c,9));const f=await La(c),e=await Ra(c,f.proofofwork?.seed,f.proofofwork?.difficulty);let g;if(f.arkose?.required&&(g=await Ta(c,8,f.arkose?.dx),!g.token))throw Error();await Oa(c,{D:g?.token,J:f.token,G:e,onEvent:function(k){k.type==="answer"?(d=k.data.text,
b(d,k.data.messageId,k.data.conversationId)):k.type==="done"&&(d&&d.trim()!==""||b(null))},prompt:a})}catch(d){throw Ua(d)&&(c.token=null,c.model=null),d;}}
class F{constructor(a,b){this.token=a;this.m=this.i=null;this.model=b;this.deviceId=E();this.j=new AbortController;this.g=null;this.cache=new Map;this.l=null}static get g(){return"CGP_CLOUDFLARE"}static get j(){return"CGP_UNAUTHORIZED"}static get i(){return"CGP_TOKEN_EXPIRED"}async request(a,b,c,d){return fetch(`https://chatgpt.com/backend-${a?"api":"anon"}${c}`,{method:b,headers:Ma(this,a),body:d===void 0?void 0:JSON.stringify(d)})}cancel(){this.j.abort();this.j=new AbortController}};importScripts("marked.min.js","sha3.min.js");n={O:"api",v:"Microsoft",u:"Google",B:"dictionaryapi",C:"googleapis",o:"cgp",F:"detect",M:"en",get:function(){return{api:Object.keys({[n.v]:"Microsoft API",[n.u]:"Google API",[n.o]:"ChatGPT"})[0],from:this.F,to:this.M,qtipStyleClass:"",fontFamily:"Times New Roman",fontSize:"17px",maxWidth:"700px",selectionIcon:"false"}}};let G=null,H={};const K=new Map;function Ya(a=Date.now()){for(const [b,c]of K.entries())a-c.timestamp>4E3&&K.delete(b)}
function L(a,b,c,d){if(typeof a==="number"&&!Number.isNaN(a)){var f=Date.now();Ya(f);K.set(a,{timestamp:f,frameId:b,stage:c,url:d})}}chrome.windows.onBoundsChanged.addListener(a=>{G&&a.id===G.id&&chrome.storage.local.set({popupDimensions:{left:a.left,top:a.top,width:a.width,height:a.height,userCustomized:!0}},()=>{})});
async function Za(a){const b=await chrome.storage.local.get(["popupDimensions"]);return b.popupDimensions&&b.popupDimensions.userCustomized?{left:b.popupDimensions.left,top:b.popupDimensions.top,width:b.popupDimensions.width,height:b.popupDimensions.height,userCustomized:!0}:{left:a.left+a.width-420-20,top:a.top+a.height-483-20,width:420,height:483,userCustomized:!1}}
function $a(a,b,c,d,f){return Math.abs(a.left-b)>100||a.state!=="normal"||a.width!==d||a.height!==f?(setTimeout(()=>{chrome.windows.update(a.id,{state:"normal",width:d,height:f,left:b,top:c,focused:!1},()=>{setTimeout(()=>{chrome.windows.update(a.id,{focused:!0})},200)})},100),!0):!1}
async function ab(a,b){if(G)try{await chrome.windows.get(G.id);await chrome.storage.local.set({pdfTranslation:a});const c=await Za(b),d={focused:!0};c.userCustomized||(d.left=c.left,d.top=c.top);await chrome.windows.update(G.id,d);const f=await chrome.tabs.query({windowId:G.id});f.length>0&&chrome.tabs.reload(f[0].id);return}catch(c){G=null}await bb(a,b)}
async function M(a,b=null,c=null,d=null){let f=null;try{if(c&&c>0)f=await chrome.windows.get(c);else if(b&&b.windowId&&b.windowId>0)f=await chrome.windows.get(b.windowId);else{const [e]=await chrome.tabs.query({active:!0,currentWindow:!0});e&&e.windowId>0&&(f=await chrome.windows.get(e.windowId))}}catch(e){f=null}if(!f)try{f=await chrome.windows.getLastFocused()}catch(e){f={left:0,top:0,width:1200,height:800}}try{await ab(a,f)}catch(e){if(d&&typeof d==="function")try{await d()}catch(g){}else try{cb(db,
b?.id??null)}catch(g){}throw e;}}async function bb(a,b){await chrome.storage.local.set({pdfTranslation:a});var c=await Za(b);a=c.left;b=c.top;const d=c.width;c=c.height;const f={url:"PHT/popup.html",type:"popup",width:d,height:c,left:a,top:b,focused:!0,state:"normal"};try{const e=await chrome.windows.create(f);G=e;$a(e,a,b,d,c)||setTimeout(()=>{chrome.windows.update(e.id,{focused:!0})},100)}catch(e){throw e;}}chrome.windows.onRemoved.addListener(a=>{G&&G.id===a&&(G=null)});
chrome.contextMenus.removeAll(()=>{chrome.contextMenus.create({id:"MTContextMenusItemId",title:`${chrome.i18n.getMessage("menuItemTranslateName")} "%s"`,contexts:["selection"]},function(){})});function N(a,b,c,d,f){return{query:a,langTo:b,data:c,searchWeb:d,messageId:f}}
function O(a,b){if(b&&b.usePopupFallback)G&&chrome.runtime.sendMessage({type:3,value:a,isStreamingUpdate:!0,originalTabId:b.id},()=>{});else if(b){var c={type:3,value:a};b&&b.iframeFallback&&(c.iframeFallback=!0,c.sourceFrameId=b.sourceFrameId);P(b.url)?chrome.runtime.sendMessage(c,()=>{}):chrome.tabs.sendMessage(b.id,c,{frameId:b.frameId},d=>{d&&G&&chrome.runtime.sendMessage({...c,isStreamingUpdate:!0,originalTabId:b.id},()=>{});Q(d,b,()=>{chrome.tabs.sendMessage(b.id,c,{frameId:0},f=>{Q(f,{...b,
frameId:0},()=>{chrome.tabs.sendMessage(b.id,c,e=>{Q(e,{...b,frameId:null},()=>{b.usePopupFallback=!0;(async()=>{await M(a,b)})()})})})})})})}}let eb=new B("content-dictionaryextension-pa","v1/dictionaryExtensionData","AIzaSyA6EEtrDCfBkHV8uU2lgGY-N383ZgAOo7Y","mgijmajocgfcbeboacabfgobmjgjcoja"),fb=new B("api","api/v2/entries");const Xa=new F;let ha=new ua,ya=new Aa;function gb(a){return a&&a.trim()}function hb(a){if(!a)return"";const b=marked.parse(a);return b?b.trim():a}
function ib(a,b,c,d,f){a=Ua(a)?`<a href="https://chat.openai.com" target="_blank" rel="noreferrer">${chrome.i18n.getMessage("loginToChatGPT")}</a>`:chrome.i18n.getMessage("errorMessage");f(N(b,c.to,a,c.searchWeb),d)}function jb(a,b,c){c=A(n.o)[c]||c;return`Translate '${a}' from ${A(n.o)[b]||b} to ${c}. Respond in ${c} and act as a translator, providing a clear and concise translation. Do not mention the language in which the translation is provided.`}
function kb(a,b=null){if(a)try{const c={type:3,value:{...a,data:a.data},isStreamingComplete:!0};b!==null&&(c.P=b);chrome.runtime.sendMessage(c,()=>{})}catch(c){}}
async function lb(a,b,c,d){try{const f=jb(a,b.from,b.to),e=N(a,b.to,chrome.i18n.getMessage("thinkingText"),b.searchWeb);d(e,c);let g=!1,k=null;Wa(f,(h,l)=>{if(h){h=hb(h);k=N(a,b.to,h,b.searchWeb,l);c&&!P(c.url)&&d(k,c);try{chrome.runtime.sendMessage({type:3,value:k,isStreamingUpdate:!0},()=>{})}catch(m){}}else g||ib(null,a,b,c,d)}).catch(h=>{ib(h,a,b,c,d)}).finally(()=>{g=!0;kb(k,c&&!P(c.url)?c.id:null)})}catch(f){ib(f,a,b,c,d)}}
function mb(a,b,c,d,f){a&&typeof a==="function"&&a(b,c.to,async e=>{if(c.useCGB==="true"&&[B.g,"An error has occurred."].includes(e))await lb(b,c,d,f);else{var g=e;e===B.g&&(g=chrome.i18n.getMessage("noDefinitionFound"));f(N(b,c.to,g,c.searchWeb),d)}})}function nb(a,b,c,d,f){var e=b;c.nowrap==="true"&&(e=e.replace(/\n/g," "));e=e.trim();a.translate(c.from,c.to,e,g=>{f(N(b,c.to,g,c.searchWeb),d)})}
function R(a,b,c){gb(a)?q(function(d){d.from===n.F&&(d.from="");Xa.cancel();switch(d.api){case n.B:mb(fb.m.bind(fb),a,d,b,c);break;case n.C:mb(eb.s.bind(eb),a,d,b,c);break;case n.o:lb(a,d,b,c);break;case n.v:nb(ha,a,d,b,c);break;case n.u:nb(ya,a,d,b,c)}}):c(N(a,"",null,!1),b)}function ob(a){q(function(b){a({value:{qtipStyleClass:b.qtipStyleClass,fontFamily:b.fontFamily,fontSize:b.fontSize,maxWidth:b.maxWidth,cspPronounce:b.cspPronounce,selectionIcon:b.selectionIcon}})})}
function Q(a,b,c){a||(chrome.runtime.lastError?c&&c():(async()=>{try{await S(b)}catch(d){}})())}function pb(a,b,c,d){a&&a!==void 0&&chrome.tabs.sendMessage(a.id,{type:7,value:{from:b,to:c,error:d}})}function P(a){return a&&a.startsWith(`chrome-extension://${chrome.runtime.id}`)&&a.endsWith("popup.html")}const T=new Map,qb=`${chrome.runtime.id}-fallback-notification`;
function cb(a,b=null){chrome.notifications.getPermissionLevel(c=>{if(c!==chrome.notifications.PermissionLevel.DENIED){switch(a){case U:c="allowAccessToFileURLsMessage";var d="notificationButtonAllow";break;case V:case W:c="reloadPageMessage";d="notificationButtonReload";break;case X:c="pageInaccessibleMessage";d=null;break;case db:c="notificationGenericFailureMessage";d=null;break;default:return}d=d?chrome.i18n.getMessage(d):null;var f=null;if(d){const e=a===W||a===V;if(!e||e&&Number.isInteger(b)&&
b>=0)f=[{title:d}]}c={type:"basic",iconUrl:"../icons/128.png",title:chrome.runtime.getManifest().name,message:chrome.i18n.getMessage(c),buttons:f,priority:1,requireInteraction:!0};chrome.notifications.create(qb,c,e=>{chrome.runtime.lastError||T.set(e,{K:a,tabId:b})})}})}
chrome.notifications.onButtonClicked.addListener(a=>{const b=T.get(a);if(b){var c=b.tabId,d=()=>{T.delete(a);chrome.notifications.clear(a)};switch(b.K){case U:chrome.tabs.create({url:"chrome://extensions/?id="+chrome.runtime.id});d();break;case V:case W:if(typeof c!=="number"){d();break}chrome.tabs.get(c,f=>{chrome.runtime.lastError||!f?d():chrome.tabs.reload(c,{},()=>{d()})});break;case X:case db:d();break;default:d()}}});chrome.notifications.onClicked.addListener(()=>{});
chrome.notifications.onClosed.addListener(a=>{T.delete(a)});
async function rb(a,b=null){try{let c=null;try{if((c=b>0?(await chrome.tabs.query({active:!0,windowId:b}))[0]:(await chrome.tabs.query({active:!0,currentWindow:!0}))[0])&&c.url===a)return c}catch(f){}if(b>0){const f=(await chrome.tabs.query({windowId:b})).find(e=>e.url===a);if(f)return f}const d=(await chrome.tabs.query({})).filter(f=>f.url===a);if(d.length===1)return d[0];if(d.length>1){const f=d.find(e=>e.active);return f?f:d.reduce((e,g)=>g.N>e.N?g:e)}return null}catch(c){return null}}
function sb(a){if(!a)return!1;if(a.startsWith("file:///")&&a.toLowerCase().endsWith(".pdf")||a.startsWith("chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/")||a.startsWith("chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/")||a.includes("/pdfjs/")||a.includes("/pdf.js/")||a.includes("viewer.html")&&a.includes("file=")||a.includes("/viewer")&&a.toLowerCase().includes(".pdf"))return!0;try{if((new URL(a)).pathname.toLowerCase().endsWith(".pdf"))return!0}catch(b){}return!1}
async function tb(a,b,c){return new Promise((d,f)=>{chrome.tabs.sendMessage(a,c,b!==null?{frameId:b}:{},e=>{chrome.runtime.lastError?f(Error(chrome.runtime.lastError.message)):d(e)})})}
async function ub(a){return new Promise(async b=>{try{const g=await chrome.webNavigation.getAllFrames({tabId:a});if(g&&g.length!==0){var c=g.find(k=>k.frameId===0);if(c&&sb(c.url)){const k={type:12};if(await new Promise(h=>{const l=setTimeout(()=>h(!1),500);chrome.tabs.sendMessage(a,k,{frameId:0},m=>{clearTimeout(l);h(!chrome.runtime.lastError&&!!m)})})){b(0);return}}var d=g.map(k=>new Promise(h=>{chrome.tabs.sendMessage(a,{type:13},{frameId:k.frameId},l=>{chrome.runtime.lastError?h(null):l&&l.isVisible?
h(k.frameId):h(null)})})),f=(await Promise.all(d)).filter(k=>k!==null);if(f.length===0)b(null);else{var e=f.includes(0)?0:f[0];b(e)}}else b(null)}catch(g){b(null)}})}async function vb(a,b){const c=await ub(a.id);if(c!==null)try{return await tb(a.id,c,b)}catch(d){throw Error("Visible frame unreachable - popup fallback required");}throw Error("No visible frames available - popup fallback required");}
async function wb(a){const b=await xb(a,null,null);return b?new Promise(c=>{function d(){if(b.frameId===0||b.frameId===null)f();else{var h=setTimeout(()=>{f()},e);chrome.tabs.sendMessage(b.tab.id,{type:12},{frameId:0},l=>{clearTimeout(h);!chrome.runtime.lastError&&l?(L(b.tab.id,0,"stage2",b.tab.url),c(!0)):f()})}}function f(){const h=setTimeout(()=>{c(!1)},e);chrome.tabs.sendMessage(b.tab.id,{type:12},l=>{clearTimeout(h);!chrome.runtime.lastError&&l?(L(b.tab.id,null,"stage3",b.tab.url),c(!0)):c(!1)})}
const e=b.tab.id!==a.id?300:500,g=b.frameId!==null?{frameId:b.frameId}:{},k=setTimeout(()=>{d()},e);chrome.tabs.sendMessage(b.tab.id,{type:12},g,h=>{clearTimeout(k);!chrome.runtime.lastError&&h?(L(b.tab.id,b.frameId,"stage1",b.tab.url),c(!0)):d()})}):!1}let Y={};async function yb(a){return new Promise(b=>{chrome.scripting.executeScript({target:{tabId:a},func:()=>!0},()=>{chrome.runtime.lastError?b(!1):b(!0)})})}
function zb(a,b,c){setTimeout(()=>{var d=Object.keys(Y).sort((f,e)=>Number(f)-Number(e));d.length===0?c?.():(d=Y[d[d.length-1]],Y={},R(d.text,{...a,frameId:d.frameId},b))},250)}var U="FILE_ACCESS_REQUIRED",V="FILE_RELOAD_REQUIRED",X="PAGE_INACCESSIBLE",W="PAGE_RELOAD_REQUIRED",db="GENERIC_FAILURE";async function Ab(a){return a.url.startsWith("file:///")?await new Promise(b=>chrome.extension.isAllowedFileSchemeAccess(b))?V:U:await yb(a.id)?W:X}
function Z(a,b){a=chrome.i18n.getMessage(a);b=chrome.i18n.getMessage(b);return{query:"",data:`<div><h3>${a}</h3>${b}</div>`,langTo:"",searchWeb:""}}
async function Bb(a,b=null){switch(b!==null?b:await Ab(a)){case U:return Z("fallbackFileAccessRequiredHeading","fallbackFileAccessRequiredMessage");case V:return Z("fallbackFileReloadHeading","fallbackFileReloadMessage");case X:return Z("inaccessiblePageHeading","inaccessiblePageMessage");case W:return Z("fallbackPageReloadHeading","fallbackPageReloadMessage");default:return Z("inaccessiblePageHeading","inaccessiblePageMessage")}}
async function S(a){const b=await Ab(a),c=await Bb(a,b);return await M(c,a,null,()=>{cb(b,a?.id??null)})}async function xb(a,b,c){if(!a||!a.url)return null;let d=a;if(a.id<0)if(c)if(a=await rb(c,a.windowId>0?a.windowId:null))d=a,b=0;else return null;else return null;return{tab:d,frameId:b}}
async function Cb(a,b,c){const d=await xb(a,b,c);return d?new Promise(f=>{const e=setTimeout(()=>f(!1),300);chrome.tabs.sendMessage(d.tab.id,{type:12},{frameId:d.frameId},g=>{clearTimeout(e);f(!chrome.runtime.lastError&&!!g)})}):!1}
chrome.contextMenus.onClicked.addListener(async function(a,b){if(P(a.pageUrl))R(a.selectionText,b,O);else if(await Cb(b,a.frameId,a.frameUrl))b.id>=0||P(a.pageUrl)?(b.frameId=a.frameId,R(a.selectionText,b,O)):aa(function(c){R(a.selectionText,c,O)});else{if(await wb(b))try{R(a.selectionText,{...b,frameId:0,iframeFallback:!0,sourceFrameId:a.frameId},O);return}catch(c){}R(a.selectionText,null,async c=>{try{await M(c,b)}catch(d){}})}});
chrome.runtime.onMessage.addListener(function(a,b,c){switch(a.type){case 2:return ob(function(h){if(b.tab&&b.tab!==void 0){h.type=a.type;const l=b.frameId||0;chrome.tabs.sendMessage(b.tab.id,h,{frameId:l},()=>{chrome.runtime.lastError&&l!==0&&chrome.tabs.sendMessage(b.tab.id,h,{frameId:0},()=>{})});c({success:!0,type:a.type})}else c({success:!1,error:"No tab information available"})}),!0;case 7:q(function(h){h.api===n.v?fa(function(l,m,p){pb(b.tab,l,m,p)}):h.api===n.o?(h=A(h.api),pb(b.tab,h,h)):h.api===
n.u&&xa(function(l,m,p){pb(b.tab,l,m,p)})});break;case 4:ob(function(h){h.type=a.type;chrome.tabs.query({},function(l){for(var m=0;m<l.length;++m)chrome.tabs.sendMessage(l[m].id,h)})});break;case 6:gb(a.value)&&(Y[a.time]={text:a.value,frameId:b.frameId});c({type:0});break;case 11:R(a.text,{...b.tab,frameId:b.frameId||0},O);c({type:0});break;case 3:var d=a.value;const f=h=>{c(h)};d?R(d,null,f):aa(function(h){chrome.tabs.sendMessage(h.id,{type:6,beep:!1,value:null},()=>{});zb(null,f,()=>{c(null)})});
return!0;case "ResetPopupPosition":return chrome.storage.local.remove(["popupPosition"],()=>{c({success:!0,message:"Position reset to default"})}),!0;case "AlertDisplayFailed":const e=`tab_${b.tab?.id}`,g=Date.now();if(H[e]&&g-H[e]<1E3)return c({success:!0,fallback:"popup",duplicate_prevented:!0}),!0;H[e]=g;for(d in H)g-H[d]>5E3&&delete H[d];b.tab?(async()=>{try{const h=Z("noSelectionHeading","noSelectionMessagePopup");await M(h,b.tab);c({success:!0,fallback:"popup"})}catch(h){c({success:!1,error:h.message})}finally{setTimeout(()=>
{H[e]===g&&delete H[e]},500)}})():(delete H[e],c({success:!1,error:"No sender tab information"}));return!0;case "ShowPopupFallback":d=b?.tab?.id;typeof d==="number"&&(Ya(Date.now()),K.get(d));const k=a.value;(async()=>{try{await M(k),c({success:!0})}catch(h){c({success:!1,error:h.message})}})();return!0}});
chrome.commands.onCommand.addListener(async function(a,b){a==="translate_selection"&&(P(b.url)?chrome.tabs.sendMessage(b.id,{type:10}):await wb(b)?(chrome.tabs.sendMessage(b.id,{type:6,beep:!1,value:null},c=>{Q(c,b,()=>{(async()=>{await S(b)})()})}),zb(b,O,()=>{const c=chrome.i18n.getMessage("noSelectionHeading")||"No Text Selected",d=chrome.i18n.getMessage("noSelectionMessageQtip")||"Please select some text and try again.",f={type:3,value:{query:"",data:`<div class="pht-no-selection-message"><h3>${c}</h3><p>${d}</p></div>`,
langTo:"",searchWeb:"",showAsAlert:!0}};(async()=>{try{const e=await vb(b,f);if(e&&e.type===1)throw Error(e.error||"qTip failed to render");}catch(e){await S(b)}})()})):(async()=>{await S(b)})())});
