$.extend({u:function(a){var b=[];$.each(a,function(c,d){$.inArray(d,b)==-1&&b.push(d)});return b}});String.prototype.trim=String.prototype.trim||function(){return this.replace(/^\s+|\s+$/g,"")};String.format=function(){for(var a=arguments[0],b=0;b<arguments.length-1;b++)a=a.replace(new RegExp("\\{"+b+"\\}","gm"),arguments[b+1]);return a};String.prototype.endsWith=function(a){return this.substr(this.length-a.length)===a};String.prototype.startsWith=function(a){return this.substr(0,a.length)===a};
String.prototype.reverse=function(){for(var a=this.split(RegExp("[^\\w]+")),b=this.split(RegExp("[\\w]+")),c="",d=0;d<a.length;d++){for(var e=a[d],f="",h=e.length;h>0;)f+=e.substring(h-1,h),h--;b.length>d+1&&(c=c.concat(f,b[d+1]))}return c};let g={get:function(){return{}}};function k(a){chrome.storage.sync.get({key:g.get()},function(b){a(b.key)})};function l(){return{[g.j]:"Microsoft API",[g.i]:"Google API",[g.h]:"ChatGPT"}};const m={m:"api",j:"Microsoft",i:"Google",o:"dictionaryapi",s:"googleapis",h:"cgp",g:"detect",l:"en",get:function(){return{api:Object.keys(l())[0],from:this.g,to:this.l,qtipStyleClass:"",fontFamily:"Times New Roman",fontSize:"17px",maxWidth:"700px",selectionIcon:"false"}}};function n(a,b){chrome.storage.sync.set({key:a},b)}function p(a){k(function(b){if(b.from===void 0||b.from==null||b.to===void 0||b.to==null)b=g.get();a(b)})};g=m;function q(a,b){var c=[];$.each(a,function(d,e){c.push($("<option></option>").attr("value",d).text(e))});$(b).html(c)}
function r(a,b){if(!a||Object.keys(a).length<=0)document.getElementById("lang-from").style.display="none";q(a,"#from");$("#from").prepend(`<option value="${m.g}">${chrome.i18n.getMessage("detectLanguageName")}</option>`);q(b,"#to");p(function(c){$.each(c,function(d,e){let f=$("#"+d);f.val(e);if(f.val()===void 0||f.val()===null)e=f.find("option").first().val(),e!==void 0&&e!==null&&e!==""&&(f.val(e),c[d]=e,chrome.storage.sync.set({key:c},void 0))})})}
function t(){$("#debug_text").text("");chrome.runtime.sendMessage({type:7})}function u(a){const b=document.getElementById(a);if(b){var c=`https://chromewebstore.google.com/detail/${chrome.runtime.id}`;b.href=a==="contactDeveloper"?`${c}/support`:c;b.innerHTML=chrome.i18n.getMessage(a)}}
function v(a,b){a={api:$("#api").val(),from:a,to:b,qtipStyleClass:$("#qtipStyleClass").val(),fontFamily:$("#fontFamily").val(),fontSize:$("#fontSize").val(),maxWidth:$("#maxWidth").val(),searchWeb:$("#searchWeb").val(),useCGB:$("#useCGB").val(),cspPronounce:$("#cspPronounce").val(),nowrap:$("#nowrap").val(),selectionIcon:$("#selectionIcon").val()};n(a,function(){t();chrome.runtime.sendMessage({type:4})})}
function w(){chrome.fontSettings.getFontList(function(a){for(var b in a){var c=a[b].displayName;$("#fontFamily").append($("<option></option>").attr("value",c).text(c))}t()})}function x(){chrome.commands.getAll(function(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b].hasOwnProperty("name")&&a[b].name==="translate_selection"){var c=a[b].shortcut;$("#translateHotkey").val(c)}})}
function y(){$("select").change(function(){var a=$("#from").val(),b=$("#to").val();b==null||b===void 0||a==null||a===void 0?p(function(c){a=c.from;b=c.to;v(a,b)}):v(a,b)})}function z(){$("#openChromeExtensionsPage").click(function(a){a.preventDefault();chrome.tabs.update({url:"chrome://extensions/configureCommands"})})}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("cspPronounceWrapper").style.display="none";document.getElementById("useCGBWrapper").style.display="none";$("#title").text(chrome.i18n.getMessage("optionsTitle"));$("#header").text(chrome.i18n.getMessage("optionsTitle"));$("#translation").text(chrome.i18n.getMessage("translation"));$("#translateBy").text(chrome.i18n.getMessage("translateByName"));$("#fromName").text(chrome.i18n.getMessage("fromName"));$("#toName").text(chrome.i18n.getMessage("toName"));
$("#popup").text(chrome.i18n.getMessage("popup"));$("#qtipStyleClassName").text(chrome.i18n.getMessage("qtipStyleClassName"));$("#maxWidthName").text(chrome.i18n.getMessage("maxWidthName"));$("#fontFamilyName").text(chrome.i18n.getMessage("fontFamilyName"));$("#fontSizeName").text(chrome.i18n.getMessage("fontSizeName"));$("#searchWebName").text(chrome.i18n.getMessage("searchWebName"));$("#searchWebDesc").attr("data-tooltip",chrome.i18n.getMessage("searchWebDesc"));$("#useCGBName").text(chrome.i18n.getMessage("useCGBName"));
$("#useCGBDesc").attr("data-tooltip",chrome.i18n.getMessage("useCGBDesc"));$("#cspPronounceName").text(chrome.i18n.getMessage("cspPronounceName"));$("#cspPronounceDesc").attr("data-tooltip",chrome.i18n.getMessage("cspPronounceDesc"));$("#nowrapName").text(chrome.i18n.getMessage("nowrapName"));$("#nowrapDesc").attr("data-tooltip",chrome.i18n.getMessage("nowrapDesc"));$("#selectionIconName").text(chrome.i18n.getMessage("selectionIconName"));$("#selectionIconDesc").attr("data-tooltip",chrome.i18n.getMessage("selectionIconDesc"));
$("#keyboardShortcutTitle").text(chrome.i18n.getMessage("shortcut"));$("#keyboardShortcutDescription").text(chrome.i18n.getMessage("shortcutDescription"));$("#openChromeExtensionsPage").text(chrome.i18n.getMessage("openKeyboardShortcutsTitle"));$("#support").text(chrome.i18n.getMessage("support"));u("writeReview");u("contactDeveloper");$("#patreon").text(chrome.i18n.getMessage("patreon"));let a=l();for(let b in a)$("#api").append($("<option></option>").attr("value",b).text(a[b]));w();x();y();z()});
chrome.runtime.onMessage.addListener(function(a){switch(a.type){case 7:const b=a.value;!b||b.error?(r({},{}),a=b?.error,$("#debug_text").text(a)):r(a.value.from,a.value.to)}});
