String.prototype.trim=String.prototype.trim||function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.g=function(){return this.replace(/\n/g," ").replace(/\s+/g," ").trim()};String.format=function(){for(var a=arguments[0],b=0;b<arguments.length-1;b++)a=a.replace(new RegExp("\\{"+b+"\\}","gm"),arguments[b+1]);return a};String.prototype.endsWith=function(a){return this.substr(this.length-a.length)===a};String.prototype.startsWith=function(a){return this.substr(0,a.length)===a};function l(){if(typeof chrome!=="undefined"&&chrome.runtime&&typeof document!=="undefined"&&!document.body)return"[extension-loading]";try{if(window.location.href.includes("/popup.html"))return"[popup]"}catch(a){}if(window===window.top)return"[main-frame]";try{const a=new URL(window.location.href),b=a.hostname.split(".").slice(-2).join("."),c=a.pathname.split("/").pop()||"root";return`[${b}/${c.slice(0,8)}:${Date.now().toString().slice(-4)}]`}catch(a){return`[iframe:${Math.random().toString(36).slice(2,
8)}]`}}if(typeof m==="undefined")var m=l();
function n(a,b){typeof b==="object"&&typeof b.data==="object"||!"ar dv fa he ku prs ps ug ur".split(" ").includes(b.langTo)?(a.dir="ltr",a.style.textAlign="left"):(a.dir="rtl",a.style.textAlign="right");a.innerHTML=p(b);a.querySelectorAll(".pht-audio").forEach(c=>{let e=c.getAttribute("data-url");(new Audio(e)).onerror=()=>c.remove();c.onmousedown=f=>{f.preventDefault();f.stopPropagation()};c.addEventListener("click",function(f){f.preventDefault();f.stopPropagation();f.cancelBubble=!0;f=this.getAttribute("data-url");
let d=document.createElement("audio");d.src=f;d.play()})})}
function p(a){if(typeof a!=="object")return a;let b="";a.query&&a.searchWeb&&a.searchWeb!=="none"&&(b=`<div style="font-size:smaller;float:right"><a href="https://www.${a.searchWeb}.com/search?q=define+${encodeURIComponent(a.query)}" target="_blank">${chrome.i18n.getMessage("searchWebName")}</a></div>`);if(typeof a.data!=="object"||a.data===null)return a=a.data===null?chrome.i18n.getMessage("errorMessage"):`${a.data}`,`${a}${b.length===0||a.endsWith("p>")?"":"<br>"}${b}`;var c="";a.data.forEach(e=>
{c!==""&&(c+="<br>");c+='<div style="display:flex;flex-direction:row;justify-content:left">';c+=`<strong>${e.text}</strong>`;if(e.phonetics&&e.phonetics.length>0){var f="";e.phonetics.map(d=>{var k=d.text;k&&k.length>0&&(k.startsWith("/")||(k="/"+k+"/"),f+=`<span style="margin-left:5px;">${k}</span>`);(d=d.audio)&&d.length>0&&(f+=`<span class="pht-audio" data-url="${d}"></span>`)});c+=`${f}`}else e.lang&&(c+=`<em style="margin-left:5px !important;color:gray">${e.lang}</em>`);c+="</div>";e.etymology&&
e.etymology.length>0&&(c+=`<div style="font-size: smaller;">${e.etymology}</div>`);e.definitions.forEach(d=>{var k;d.morphemes&&d.morphemes.length>0?k=d.morphemes.map(g=>`<em style="color:gray">${g.pos}</em>: <span style="color:black">${g.form}</span>`).join("; "):d.poses&&d.poses.length>0&&(k=d.poses.map(g=>`<em style="color:gray">${g}</em>`).join(", "));k&&(c+=`<br>${k}`);d.senses.forEach(g=>{var h="";g.synonyms&&g.synonyms.length>0&&(h+=`<em style="color:gray">synonyms</em>: ${g.synonyms.join(", ")}`);
g.antonyms&&g.antonyms.length>0&&(h&&(h+="<br>"),h+=`<em style="color:gray">antonyms</em>: ${g.antonyms.join(", ")}`);g.examples&&g.examples.length>0&&(h&&(h+="<br>"),h+=`<em style="color:gray">examples</em>: ${g.examples.join("; ")}`);let q=g.subsenses;q&&q.length>0&&(h&&(h+="<br>"),h+=`<em style="color:gray">subsenses</em>: ${q.join("; ")}`);c+=`<details class"pht-details"><summary class="${"pht-summary"+(h?"":" disabled")}">${g.definition}</summary>${h}</details>`})})});return`${c}${b}`}
function r(a){try{return a.getBoundingClientRect()}catch(b){return null}}
function t(){var a=!1;typeof a!=="boolean"&&(a=!1);try{var b=document.activeElement;const e=b?b.tagName.toLowerCase():null;if(e==="textarea"||e==="input"&&/^(?:text|search|password|tel|url)$/i.test(b.type)&&typeof b.selectionStart==="number"){const f=b.value.slice(b.selectionStart,b.selectionEnd);if(!f||f.trim()==="")return null;var c=null;a&&(c=r(b));return{text:f,rect:c,source:e,h:!0}}if(window.getSelection){c=window.getSelection();if(!c||c.rangeCount===0)return null;const f=c.toString();if(!f||
f.trim()==="")return null;b=null;if(a)try{const d=r(c.getRangeAt(0));d&&(d.width>0||d.height>0)&&(b=d)}catch(d){}return{text:f,rect:b,source:c.anchorNode?.parentElement?.isContentEditable?"contenteditable":"selection",h:!1}}return null}catch(e){return null}};(function(){function a(){chrome.windows.getCurrent(b=>{document.body.classList.add(b&&b.type==="popup"?"fallback-window":"toolbar-popup")})}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",a):a()})();function u(a,b){a.disabled=!0;b.disabled=!0;b=document.getElementById("meaning");b.style.display="block";b.innerHTML="processing...";chrome.runtime.sendMessage({type:3,value:a.value},c=>{v(c)})}
function v(a){const b=w();b.disabled=!1;b.focus();x().disabled=!1;const c=document.getElementById("meaning");a&&a.data?(a.query&&(b.value=a.query),c.style.display="block",n(c,a),(a=document.getElementById("pht-open-extensions-link"))&&a.addEventListener("click",e=>{e.preventDefault();chrome.tabs.create({url:"chrome://extensions/?id="+chrome.runtime.id})})):c.style.display="none"}function w(){return document.getElementById("query-field")}function x(){return document.getElementById("define-btn")}
document.addEventListener("DOMContentLoaded",()=>{document.title=chrome.i18n.getMessage("short_name");const a=x();a.innerHTML=chrome.i18n.getMessage("menuItemTranslateName");const b=w();b.addEventListener("keydown",function(c){c.key==="Enter"&&b.value&&u(b,a)},!1);a.addEventListener("click",()=>{b.value&&u(b,a)});chrome.storage.local.get("pdfTranslation",function(c){c.pdfTranslation?(v(c.pdfTranslation),chrome.storage.local.remove("pdfTranslation")):u(b,a)})});
chrome.runtime.onMessage.addListener((a,b,c)=>{if(b.url&&b.url.startsWith(`chrome-extension://${chrome.runtime.id}`)&&b.url.endsWith("background.js"))if(a.type===10){if(a=t())b=w(),b.value=a.text,u(b,x());c({success:!0})}else if(a.isStreamingComplete)v(a.value),a=w(),b=x(),a.disabled=!1,b.disabled=!1,a.focus(),c({success:!0,streamingComplete:!0});else if(a.isStreamingUpdate)v(a.value),c({success:!0,streaming:!0});else if(a.type===3){b=t()?.text.g();const e=a.value?.query?.g();b===e&&(v(a.value),c())}});
