"""Generate the Transport Standards index (side project: side/transport-standards).
Reads streetPathArchetypes.json, filters to in-scope transportation categories,
derives render-readiness, attaches standard family + citation, emits a typed TS file.
Re-runnable; never mutates the catalog. See docs/transport-standards/CATALOG_GAP_CHECK.md."""
import json, re, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

def num(v):
    """Coerce a section value to a clean number|None — the catalog stores
    targetSpeed_kmh inconsistently (40, '—', '50 km/h')."""
    if isinstance(v, (int, float)):
        return v
    if isinstance(v, str):
        m = re.search(r"-?\d+(?:\.\d+)?", v)
        return float(m.group()) if m else None
    return None

CATALOG = "frontend/src/data/streetPathArchetypes.json"
OUT = "frontend/src/data/transportStandards.ts"

# category -> (standardFamily, jurisdiction)
FAMILY = {
    "calgary_street_manual":       ("Calgary Street Manual — Cross-Sections (Ch4 / Complete Streets TP021)", "Calgary"),
    "traffic_safety_vision_zero":  ("Calgary Street Manual — Traffic Calming (Ch10) / Vision Zero",          "Calgary"),
    "intersections":               ("Calgary Street Manual — Intersections (Ch9)",                          "Calgary"),
    "alberta_bike_design_guide":   ("Alberta Bicycle Facilities Design Guide",                              "Alberta"),
}
IN_SCOPE = set(FAMILY)

d = json.load(open(CATALOG, encoding="utf-8"))
rows = []
for a in d["archetypes"]:
    cat = a.get("aestheticCategory")
    if cat not in IN_SCOPE:
        continue
    gt = a.get("generationTags") or []
    sec = a.get("section") or None
    if "technical-diagram" in gt:
        mode = "diagram"
    elif sec:
        mode = "section-data"
    else:
        mode = "card-only"
    fam, juris = FAMILY[cat]
    cite = None
    if sec:
        fig = sec.get("figure"); draft = sec.get("draftStatus")
        bits = []
        if fig: bits.append(f"Fig {fig}")
        if draft: bits.append(draft)
        if sec.get("confidence"): bits.append(f"confidence: {sec['confidence']}")
        cite = ", ".join(bits) or None
    rows.append({
        "archetypeId": a["id"],
        "title": a.get("title", a["id"]),
        "category": cat,
        "standardFamily": fam,
        "jurisdiction": juris,
        "citation": cite,
        "renderMode": mode,                       # how it renders faithfully today
        "renderReady": mode in ("diagram", "section-data"),  # wireable to the faithful path
        "hasSection": bool(sec),
        "sectionSvgUrl": a.get("sectionSvgUrl"),
        "rowM": num((sec or {}).get("row_m")),
        "targetSpeedKmh": num((sec or {}).get("targetSpeed_kmh")),
    })

rows.sort(key=lambda r: (r["category"], r["archetypeId"]))
families = []
for cat, (fam, juris) in FAMILY.items():
    members = [r for r in rows if r["category"] == cat]
    families.append({"category": cat, "label": fam, "jurisdiction": juris, "count": len(members)})

ts = f"""// AUTO-GENERATED by scripts/_transport_standards_index.py — do not hand-edit.
// Side project: side/transport-standards. Backbone for the Standards Browser (Step A).
// Maps in-scope transportation archetypes -> design standard + citation + render-readiness.

export type RenderMode = 'diagram' | 'section-data' | 'card-only';

export interface TransportStandardEntry {{
  archetypeId: string;
  title: string;
  category: string;
  standardFamily: string;
  jurisdiction: 'Calgary' | 'Alberta' | 'Canada (TAC)' | 'NACTO' | 'AASHTO';
  citation: string | null;
  /** how this archetype renders faithfully today */
  renderMode: RenderMode;
  /** true if it can be driven through the geometry-faithful (diagram-conditioned) path */
  renderReady: boolean;
  hasSection: boolean;
  sectionSvgUrl: string | null;
  rowM: number | null;
  targetSpeedKmh: number | null;
}}

export interface StandardFamily {{
  category: string;
  label: string;
  jurisdiction: string;
  count: number;
}}

export const STANDARD_FAMILIES: StandardFamily[] = {json.dumps(families, indent=2, ensure_ascii=False)};

export const TRANSPORT_STANDARDS: TransportStandardEntry[] = {json.dumps(rows, indent=2, ensure_ascii=False)};
"""
open(OUT, "w", encoding="utf-8").write(ts)

diag = sum(1 for r in rows if r["renderMode"] == "diagram")
secd = sum(1 for r in rows if r["renderMode"] == "section-data")
card = sum(1 for r in rows if r["renderMode"] == "card-only")
print(f"Wrote {OUT}")
print(f"  in-scope entries : {len(rows)}")
print(f"  render-faithful now (diagram)        : {diag}")
print(f"  wireable (section-data)              : {secd}")
print(f"  card-only (needs section authoring)  : {card}")
print("  families:")
for f in families:
    print(f"    {f['count']:3d}  {f['label']}")
