# Plan: Lifelike Textures + "Place in Tiles" + High-Quality Development Render

Self-contained execution prompt for a fresh session. Repo: `beemanbesh/2D-Maps2`,
branch `experiment/lego-assembly` (PR #20, draft, base `feat/urban-intelligence-dna`).
Do not merge. Keep everything reversible and committed in logical increments.

## Verified environment (do not re-derive)

- Worktree: `C:\Users\andre\lego-wt` (main Playground tree has unrelated in-progress work — do not touch it except `.claude/launch.json` if needed).
- Backend venv: `C:\Users\andre\lego-wt\backend\.venv` (full deps + pytest). Backend tests: `cd backend && .venv\Scripts\python.exe -m pytest tests/test_lego_assembly.py -q`.
- Blender 5.1.2: `C:\Program Files\Blender Foundation\Blender 5.1\blender.exe` (auto-discovered by `tools/archetype_compiler/blender_locator.py`).
- One-command family generation: `python tools/archetype_compiler/generate_family.py --archetype-id <id>` (export → grammar → Blender → validate). Library import: `python tools/archetype_compiler/import_manifest.py build/archetypes/<id> --api-base http://localhost:8001 --token <jwt>`.
- Dev stack for testing: worktree backend `cd backend && .venv\Scripts\python.exe -m uvicorn app.main:app --port 8001` (uses `backend/.env`, already copied, has GEMINI_API_KEY + MESHY_API_KEY); frontend via `.claude/launch.json` name `lego-frontend` on :5175 (proxies /api → 8001). CRITICAL gotcha already fixed there: the vite process must `Set-Location` into `C:\Users\andre\lego-wt\frontend` before starting or Tailwind resolves content globs against the wrong tree and arbitrary classes like `z-[110]` silently vanish.
- Admin JWT mint: `backend\.venv\Scripts\python.exe -c "import sys; sys.path.insert(0,'backend'); from app.core.security import create_access_token; print(create_access_token('651daf60-b797-4f95-b1e7-6364d6dc0665','admin'))"` (works against the worktree backend).
- Coordinate contract: modules are metres, glTF Y-up, origin bottom-centre, front facade +Z; recipes stack with `position [x,y,z]` z-up metres. `frontend/src/features/legoAssembly/legoShared.tsx` `ModuleInstance` holds the canonical three.js swizzle.
- Material keyword table (prose → colour) lives in `tools/archetype_compiler/compiler.py` (`_MATERIAL_KEYWORDS`) — this is the hook for textures.
- Archetype reference images live at `frontend/public/archetypes/buildings/<slug>/variant_N.png` (the card renders users see — textures must visually match these).
- Gemini image: model `gemini-3.1-flash-image` (GA id), do NOT send temperature, DO send `aspect_ratio` + `image_size`; simple natural prompts beat structured ones; critical constraints go at the END of the prompt. Backend has `GEMINI_API_KEY` in `backend/.env`; the google-genai SDK is installed in the backend venv.
- A `GlobeLegoAssemblyLayer` (recipes → module stacks on Google Tiles, `GlobeBuildingModelsLayer` patterns: `computeFootprintFrame`, EastNorthUpFrame, drape-and-freeze terrain, renderOrder 150) was being built at the end of the previous session — `git log` first; if it landed, build on it; if not, its spec is in the PR #20 conversation and follows `GlobeBuildingModelsLayer.tsx` exactly.
- Backend endpoints that exist: `/api/v1/lego-assembly/{modules,plan,import-manifest,recipes/{building_id}}`. Recipes live in `Building.specifications["legoAssembly"]` (copy-update-reassign + `flag_modified`). Zone PUT REPLACES the whole `properties` dict — always merge client-side.
- Zone→building link: `SiteZone.building_id` / `building_ids` (columns, set by generate-all; NOT settable via zone PUT).
- Frontend gates: `npx tsc --noEmit` → 0 errors on this branch; `npm run build` passes; feature tests `npx vitest run src/features/legoAssembly` (19+).

## Workstream A — AI-generated PBR texture library (match the archetype images)

Goal: replace flat colours with tileable textures generated by Gemini image (GPT Image
2 as fallback for photoreal stubborn materials), visually matched to the archetype
card images, applied deterministically in Blender.

A1. Texture library tool: `tools/archetype_compiler/generate_textures.py`
   - For each entry in the material keyword table (charred timber, larch, CLT, red/buff
     brick, white plaster, zinc, corrugated steel, stone, concrete, glass mullion...):
     call Gemini (`gemini-3.1-flash-image`) with a simple prompt:
     "Seamless tileable texture of <material prose>, photographed straight-on, even
     diffuse lighting, no shadows, no perspective, 2 metres of wall coverage.
     The texture must tile seamlessly in both directions." — `aspect_ratio "1:1"`,
     `image_size 1024`. Optionally pass the archetype's own variant PNG as a reference
     image (`--from-archetype <id>` mode) so the texture matches the card look.
   - Post-process in Pillow/numpy (both in the backend venv):
     (a) enforce tileability: offset-by-50% + cross-blend seams (or mirror-tile
     fallback); (b) derive normal map from luminance height (sobel) and a roughness
     map from inverted local contrast — honest approximations, good enough at street
     scale; (c) downsize to 1024, save `albedo.png`, `normal.png`, `roughness.png`.
   - Validate: shift-by-half seam contrast metric below threshold; else regenerate
     (max 2 retries) or fall back to mirror-tiling. Record per-texture provenance
     (prompt, model, date, source archetype image if used) in
     `tools/archetype_compiler/textures/manifest.json`.
   - Layout: `tools/archetype_compiler/textures/<material_key>/{albedo,normal,roughness}.png`.
     Commit the library (≈20 materials × ~1 MB — acceptable on an experiment branch).
   - PILOT FIRST (collaboration pattern): generate 3 materials (charred timber, buff
     brick, zinc), show them + a re-render of nordic_timber_midrise to Andrew before
     the full sweep.

A2. Blender generator upgrade (`tools/archetype_compiler/blender_generate.py`)
   - Map material slots to texture sets: extend the compiler so `Material` carries
     `texture_key` (the matched keyword) alongside `base_color`; blender_generate
     loads the texture set when present (Principled BSDF: albedo → Base Color,
     normal via Normal Map node, roughness map), falls back to flat colour when
     absent (keeps pipeline working with zero textures).
   - UV: box/cube projection per module part with real-world texel density (1 tile =
     2 m). `bpy.ops.uv.cube_project(cube_size=2.0)` per mesh before join, or
     mathutils-based box UV in code (more deterministic — preferred).
   - Bake ambient occlusion per module (Cycles bake to a 512 AO map, multiplied into
     base colour) — biggest realism win independent of albedo textures. Add
     `--no-ao` flag for fast runs. GLB export embeds textures automatically.
   - Watch GLB size: target < 8 MB per module at 1K textures; validate_outputs.py
     gains a size warning threshold.
   - Regenerate + re-import the 5 existing families (nordic, rndsqr, contemporary
     midrise, calgary infill, hotel_particulier); dedupe updates them in place.

A3. Tests/validation: compiler unit tests for texture_key matching; validate_outputs
    checks GLBs still parse + size warnings; visual: preview PNGs regenerate into
    `docs/lego_previews/` for PR review.

## Workstream B — "Place" button: LEGO model replaces the zone polygon in 3D Tiles

B1. Backend: `POST /api/v1/lego-assembly/place/{zone_id}` (in
    `backend/app/api/v1/lego_assembly.py`):
    - Auth like recipes (project editor). Body = the plan/recipe payload (same
      Pydantic model as recipes endpoint) plus optional floors/dims.
    - If `zone.building_id` is null: create a `Building` (project_id from zone,
      name from archetype label, footprint = zone.geometry, floor_count from
      recipe target), set `zone.building_id` + `zone.building_ids`, flush.
    - Save the recipe into `building.specifications["legoAssembly"]` (existing
      copy-update-reassign helper) and stamp `specifications["lego_placed"] = true`.
    - Return building id + zone id. Tests: creates-building path, reuses-existing
      path, permission denial (mirror existing recipe tests with mock_db).
B2. Frontend LEGO Builder (`frontend/src/features/legoAssembly/LegoBuilderPanel.tsx`):
    - Per assembled zone row: "Place" button; header: "Place all" — call the new
      endpoint per zone (Promise.allSettled), badge rows as placed, then
      invalidate the project query (`queryClient.invalidateQueries(['project', ...])`)
      so the globe refetches buildings. Same for the single-zone composer
      (`LegoAssemblyPreview.tsx`) — its Save recipe becomes Save/Place split or a
      "Place on map" second button.
    - After placing, the globe must show the stack (GlobeLegoAssemblyLayer) and hide
      the zone's coloured polygon/prism: GlobeZoneLayer already supports
      `suppressedBuildingIds` (prism suppression handshake used by
      GlobeBuildingModelsLayer via onLoadedIdsChange) — extend the same handshake
      from GlobeLegoAssemblyLayer, and additionally dim/hide the zone FILL for
      placed zones (find the fill styling in GlobeZoneLayer; a `placedZoneIds` prop
      mirroring the suppression pattern; keep the outline for selectability).
    - Zones stay selectable/editable; clearing the recipe (existing DELETE) must
      restore the polygon (suppression derives from live recipe presence, not a
      stored flag — derive, don't duplicate state).
B3. Verify live on the 5175 stack: place Hotel Particulier in the Lego Test project
    (project `c21ff031-0f60-4486-91f8-351f94d794b0`), screenshot the globe with the
    stack replacing the red polygon. The Browser-pane rAF freeze means screenshots
    may be stale — verify via DOM/network + ask Andrew to confirm visually.

## Workstream C — RENDER produces a higher-quality style render of the development

The existing globe RENDER (useGlobeAIRender) already captures the WebGL canvas
(preserveDrawingBuffer: true) — placed LEGO stacks automatically appear in the
capture and act as geometry conditioning. Build on that:

C1. "Development render" mode in the globe render panel:
    - When ≥1 placed LEGO building is in view, offer style "Development (high
      fidelity)": conditioning = current globe capture (which now contains textured
      massing) + the per-building archetype identity.
    - Prompt assembly: collect `generation_style_input` payloads for all PLACED
      buildings in the view cone (they're on `zone.properties` /
      `building.specifications` — reuse `collectArchetypeRenderInputs.ts` patterns),
      summarize into one prompt: per-building material/style sentence + "keep every
      building exactly where it stands in the reference image; preserve massing,
      floor counts and roof forms" AT THE END (Gemini weights the tail).
    - Model call through the existing render proxy (`backend/app/api/v1/render.py`),
      `gemini-3.1-flash-image`, no temperature, aspect_ratio matching capture.
    - Keep prompts SIMPLE (project memory: simple beats structured; negatives
      backfire; no "8k").
C2. Optional second pass: archetype reference images (variant PNGs) of the placed
    buildings attached as additional reference inputs (multi-image conditioning is
    supported by the render proxy — check `reference_images` handling in render.py)
    — pilot on one scene, compare with/without, show Andrew A/B.
C3. Do NOT rebuild the render pipeline — this is a new style/mode + prompt builder
    only. Respect existing memories: roadways sacred in masks, containment needs
    sensible zoom, night styles hide seams.

## Order of execution & definition of done

Order: A1 pilot (3 textures) → show Andrew → A1 full + A2 + regenerate families →
B1+B2 (Place) → B3 live verify → C1 → C2 A/B pilot → PR #20 update.

Done when: (1) texture library committed with provenance manifest; (2) all 5
families regenerate textured, validation passes, GLBs < 8 MB/module; (3) previews in
docs/lego_previews refreshed; (4) Place button creates/links the building, saves the
recipe, the stack replaces the coloured polygon on the globe, and clearing restores
it; (5) backend tests extended and green (place endpoint); frontend tsc 0 / build
green / feature vitest green; (6) Development render mode produces an image from a
placed scene and the A/B (with vs without archetype refs) is documented; (7) PR #20
body updated honestly (CI note: full backend suite inherits 25 base-branch failures
— see PR body — do not claim green); (8) everything on `experiment/lego-assembly`,
draft, unmerged.

Aesthetic checkpoints for Andrew (stop and show, don't guess): texture pilot trio;
textured nordic + hotel_particulier previews; first placed-stack globe screenshot;
Development-render A/B.
