"""Two-tier city detection — committed municipal boundary polygons.

The coarse CITY_BOUNDS bbox is only a prefilter; these tests pin the
containment behavior detect_city() relies on: downtown points resolve to the
city, metro-adjacent suburbs INSIDE the coarse bbox do not. Boundary files are
generated by scripts/build_city_boundaries.py; if a regeneration breaks one of
these points, the file is wrong — not the test.
"""

import pytest
from shapely.geometry import Point

from app.services.city_connector.boundaries import get_boundary

DOWNTOWN = {
    "calgary": (-114.07, 51.045),
    "edmonton": (-113.49, 53.54),
    "vancouver": (-123.12, 49.28),
    "toronto": (-79.38, 43.65),
}

# Suburbs that sit inside (or beside) the coarse detection bbox but outside the
# municipality — the exact misroutes the boundary polygons exist to prevent.
SUBURB_NEAR_MISSES = {
    "calgary": [(-113.82, 51.04)],                      # Chestermere
    "edmonton": [(-113.63, 53.63), (-113.28, 53.52)],   # St. Albert, Sherwood Park
    "vancouver": [(-123.24, 49.26), (-123.07, 49.31)],  # UBC/UEL, North Vancouver
    "toronto": [(-79.64, 43.59), (-79.51, 43.84)],      # Mississauga, Vaughan
}


@pytest.mark.parametrize("city_id", sorted(DOWNTOWN))
def test_boundary_contains_downtown(city_id):
    boundary = get_boundary(city_id)
    assert boundary is not None, f"missing committed boundary file for {city_id}"
    lon, lat = DOWNTOWN[city_id]
    assert boundary.contains(Point(lon, lat))


@pytest.mark.parametrize("city_id", sorted(SUBURB_NEAR_MISSES))
def test_boundary_excludes_adjacent_suburbs(city_id):
    boundary = get_boundary(city_id)
    assert boundary is not None
    for lon, lat in SUBURB_NEAR_MISSES[city_id]:
        assert not boundary.contains(Point(lon, lat)), f"({lon}, {lat}) wrongly inside {city_id}"


def test_missing_boundary_returns_none():
    assert get_boundary("montreal") is None
    assert get_boundary("osm") is None
