// Generated by python -m tools.catalogue_promotion sync. Edit library.json.
import type { PlaceAsset } from './assetRegistry';

export const PUBLISHED_BUILDING_ASSETS: PlaceAsset[] = [
  {
    "id": "trial_postwar_bungalow",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Post-war bungalow",
    "description": "One-storey brick home with a sheltered porch.",
    "thumbnail": "/archetypes/buildings/calgary-inner-city-bungalow/variant_2.png",
    "model": {
      "variantId": "bungalow_postwar_ranch",
      "revision": "calgary-inner-city-bungalow-clay-v005",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "detached",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "repeat_native",
    "width": 15.0,
    "depth": 20.0,
    "minWidth": 15.0,
    "minDepth": 20.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      10.898324012756348,
      16.050000190734863,
      6.360000133514404
    ],
    "reshapeDescription": "Widen the plot to add complete houses. Each house keeps its authored proportions.",
    "properties": {
      "building_archetype_id": "calgary_inner_city_bungalow",
      "development_archetype_id": "calgary_inner_city_bungalow",
      "development_selected_variant_id": "bungalow_postwar_ranch",
      "development_archetype_label": "Post-war bungalow",
      "floors": 1,
      "floor_count": 1,
      "native_home_plot": true
    }
  },
  {
    "id": "trial_edwardian_foursquare",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Edwardian Foursquare",
    "description": "Two-storey brick home with a porch and dormer.",
    "thumbnail": "/archetypes/buildings/toronto-edwardian-foursquare/variant_0.png",
    "model": {
      "variantId": "toronto_foursquare_red_brick",
      "revision": "toronto-edwardian-foursquare-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "detached",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "repeat_native",
    "width": 15.0,
    "depth": 22.0,
    "minWidth": 15.0,
    "minDepth": 22.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      11.069999694824219,
      17.93000030517578,
      10.8100004196167
    ],
    "reshapeDescription": "Widen the plot to add complete houses. The porch, dormer and two storeys keep their proportions.",
    "properties": {
      "building_archetype_id": "toronto_edwardian_foursquare",
      "development_archetype_id": "toronto_edwardian_foursquare",
      "development_selected_variant_id": "toronto_foursquare_red_brick",
      "development_archetype_label": "Edwardian Foursquare",
      "floors": 2,
      "floor_count": 2,
      "native_home_plot": true
    }
  },
  {
    "id": "trial_sandstone_civic",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Sandstone civic hall",
    "description": "Courtyard institution with an arched facade and clock tower.",
    "thumbnail": "/archetypes/buildings/calgary-sandstone-heritage/variant_0.png",
    "model": {
      "variantId": "sandstone_romanesque_revival",
      "revision": "calgary-sandstone-heritage-clay-v007",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "civic",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 64.0,
    "depth": 66.0,
    "minWidth": 64.0,
    "minDepth": 66.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      59.40999984741211,
      60.010000228881836,
      44.0
    ],
    "reshapeDescription": "A complete landmark at its authored size. Move or rotate it; the courtyard and tower retain their proportions.",
    "properties": {
      "building_archetype_id": "calgary_sandstone_heritage",
      "development_archetype_id": "calgary_sandstone_heritage",
      "development_selected_variant_id": "sandstone_romanesque_revival",
      "development_archetype_label": "Sandstone civic hall",
      "floors": 3,
      "floor_count": 3,
      "native_plot_axes": true
    }
  }
];
