// Generated by python -m tools.catalogue_promotion sync. Edit library.json.
import type { PlaceAsset } from './assetRegistry';

export const CATALOGUE_BUILDING_ASSETS: PlaceAsset[] = [
  {
    "id": "trial_postwar_bungalow",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Post-war bungalow",
    "description": "One-storey brick home with a sheltered porch.",
    "thumbnail": "/archetypes/buildings/calgary-inner-city-bungalow/variant_2.png",
    "model": {
      "variantId": "bungalow_postwar_ranch",
      "revision": "calgary-inner-city-bungalow-clay-v005",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "detached",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "repeat_native",
    "width": 15.0,
    "depth": 20.0,
    "minWidth": 15.0,
    "minDepth": 20.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      10.898324012756348,
      16.050000190734863,
      6.360000133514404
    ],
    "reshapeDescription": "Widen the plot to add complete houses. Each house keeps its authored proportions.",
    "properties": {
      "building_archetype_id": "calgary_inner_city_bungalow",
      "development_archetype_id": "calgary_inner_city_bungalow",
      "development_selected_variant_id": "bungalow_postwar_ranch",
      "development_archetype_label": "Post-war bungalow",
      "floors": 1,
      "floor_count": 1,
      "native_home_plot": true
    }
  },
  {
    "id": "trial_edwardian_foursquare",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Edwardian Foursquare",
    "description": "Two-storey brick home with a porch and dormer.",
    "thumbnail": "/archetypes/buildings/toronto-edwardian-foursquare/variant_0.png",
    "model": {
      "variantId": "toronto_foursquare_red_brick",
      "revision": "toronto-edwardian-foursquare-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "detached",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "repeat_native",
    "width": 15.0,
    "depth": 22.0,
    "minWidth": 15.0,
    "minDepth": 22.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      11.069999694824219,
      17.93000030517578,
      10.8100004196167
    ],
    "reshapeDescription": "Widen the plot to add complete houses. The porch, dormer and two storeys keep their proportions.",
    "properties": {
      "building_archetype_id": "toronto_edwardian_foursquare",
      "development_archetype_id": "toronto_edwardian_foursquare",
      "development_selected_variant_id": "toronto_foursquare_red_brick",
      "development_archetype_label": "Edwardian Foursquare",
      "floors": 2,
      "floor_count": 2,
      "native_home_plot": true
    }
  },
  {
    "id": "trial_sandstone_civic",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Sandstone civic hall",
    "description": "Courtyard institution with an arched facade and clock tower.",
    "thumbnail": "/archetypes/buildings/calgary-sandstone-heritage/variant_0.png",
    "model": {
      "variantId": "sandstone_romanesque_revival",
      "revision": "calgary-sandstone-heritage-clay-v007",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "civic",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 64.0,
    "depth": 66.0,
    "minWidth": 64.0,
    "minDepth": 66.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      59.40999984741211,
      60.010000228881836,
      44.0
    ],
    "reshapeDescription": "A complete landmark at its authored size. Move or rotate it; the courtyard and tower retain their proportions.",
    "properties": {
      "building_archetype_id": "calgary_sandstone_heritage",
      "development_archetype_id": "calgary_sandstone_heritage",
      "development_selected_variant_id": "sandstone_romanesque_revival",
      "development_archetype_label": "Sandstone civic hall",
      "floors": 3,
      "floor_count": 3,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_rammed_earth_infill",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Rammed-earth timber infill",
    "description": "Three-storey rammed-earth home with shaded loggias and timber screens.",
    "thumbnail": "/archetypes/buildings/detached_contemporary_infill/variant_3.png",
    "model": {
      "variantId": "detached_infill_rammed_earth",
      "revision": "detached_contemporary_infill-clay-v003",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "detached",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 18.0,
    "depth": 24.0,
    "minWidth": 18.0,
    "minDepth": 24.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      13.375,
      19.600000381469727,
      10.149999618530273
    ],
    "reshapeDescription": "Resize the plot around one complete building. The building keeps its three storeys and authored proportions.",
    "properties": {
      "building_archetype_id": "detached_contemporary_infill",
      "development_archetype_id": "detached_contemporary_infill",
      "development_selected_variant_id": "detached_infill_rammed_earth",
      "development_archetype_label": "Rammed-earth timber infill",
      "floors": 3,
      "floor_count": 3,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_classic_courtyard_motel",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Classic courtyard motel",
    "description": "Single-storey motor court with colourful doors, reception and a vintage roadside sign.",
    "thumbnail": "/archetypes/buildings/highway-motor-hotel/variant_0.png",
    "model": {
      "variantId": "hotel_roadside_motel",
      "revision": "highway-motor-hotel-clay-v002",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "hotels",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 29.0,
    "depth": 42.0,
    "minWidth": 29.0,
    "minDepth": 42.0,
    "maxSize": 120.0,
    "nativeDimensions": [
      24.8799991607666,
      37.7400016784668,
      7.21999979019165
    ],
    "reshapeDescription": "Resize the plot around the complete motel. Wings, guest rooms and sign keep their authored proportions.",
    "properties": {
      "building_archetype_id": "highway_motor_hotel",
      "development_archetype_id": "highway_motor_hotel",
      "development_selected_variant_id": "hotel_roadside_motel",
      "development_archetype_label": "Classic courtyard motel",
      "floors": 1,
      "floor_count": 1,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_beltline_brick_midrise",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Beltline brick mixed-use mid-rise",
    "description": "Five-storey brick corner building with shops, recessed balconies and a metal-clad upper floor.",
    "thumbnail": "/archetypes/buildings/calgary-beltline-mid-rise/variant_1.png",
    "model": {
      "variantId": "beltline_brick_modern",
      "revision": "calgary-beltline-mid-rise-clay-v003",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "mixed",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 39.0,
    "depth": 39.0,
    "minWidth": 39.0,
    "minDepth": 39.0,
    "maxSize": 120.0,
    "nativeDimensions": [
      34.15999984741211,
      34.15999984741211,
      20.43000030517578
    ],
    "reshapeDescription": "Resize the plot around the complete building. Shops, balconies and roof retain their authored proportions.",
    "properties": {
      "building_archetype_id": "calgary_beltline_mid_rise",
      "development_archetype_id": "calgary_beltline_mid_rise",
      "development_selected_variant_id": "beltline_brick_modern",
      "development_archetype_label": "Beltline brick mixed-use mid-rise",
      "floors": 5,
      "floor_count": 5,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_blue_glass_office_tower",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Blue glass office tower",
    "description": "A 25-storey blue glass office tower with a glazed lobby, entrance canopy and rooftop crown.",
    "thumbnail": "/archetypes/buildings/glass_tower_podium_modern/variant_0.png",
    "model": {
      "variantId": "glass_tower_blue_reflective",
      "revision": "glass_tower_podium_modern-clay-v003",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "offices",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 36.0,
    "depth": 34.0,
    "minWidth": 36.0,
    "minDepth": 34.0,
    "maxSize": 160.0,
    "nativeDimensions": [
      32.1200008392334,
      30.074999809265137,
      99.0
    ],
    "reshapeDescription": "Resize the plot around the complete tower. Its floors, canopy and crown keep their original proportions.",
    "properties": {
      "building_archetype_id": "glass_tower_podium_modern",
      "development_archetype_id": "glass_tower_podium_modern",
      "development_selected_variant_id": "glass_tower_blue_reflective",
      "development_archetype_label": "Blue glass office tower",
      "floors": 25,
      "floor_count": 25,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_vancouver_balcony_podium_tower",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Vancouver balcony and podium tower",
    "description": "A 16-storey residential tower with rounded balconies, a landscaped podium and a lower shop wing.",
    "thumbnail": "/archetypes/buildings/vancouverism-tower-podium/variant_0.png",
    "model": {
      "variantId": "vancouverism_classic",
      "revision": "vancouverism-tower-podium-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "towers",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 52.0,
    "depth": 44.0,
    "minWidth": 52.0,
    "minDepth": 44.0,
    "maxSize": 180.0,
    "nativeDimensions": [
      48.05500030517578,
      40.05500030517578,
      58.79999923706055
    ],
    "reshapeDescription": "Resize the plot around this complete tower. Floors, terraces and structural details retain their authored proportions.",
    "properties": {
      "building_archetype_id": "vancouverism_tower_podium",
      "development_archetype_id": "vancouverism_tower_podium",
      "development_selected_variant_id": "vancouverism_classic",
      "development_archetype_label": "Vancouver balcony and podium tower",
      "floors": 16,
      "floor_count": 16,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_twisting_glass_sky_garden_tower",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "ready",
    "label": "Twisting glass tower with sky garden",
    "description": "A 40-level twisting glass tower with a shared sky garden, trussed lobby and a rooftop garden.",
    "thumbnail": "/archetypes/buildings/glass_tower_podium_modern/variant_1.png",
    "model": {
      "variantId": "glass_tower_twisted",
      "revision": "glass-tower-twisted-clay-v005",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "offices",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 49.0,
    "depth": 49.0,
    "minWidth": 49.0,
    "minDepth": 49.0,
    "maxSize": 180.0,
    "nativeDimensions": [
      43.4902229309082,
      44.02606964111328,
      147.6999969482422
    ],
    "reshapeDescription": "Resize the plot around this complete tower. Floors, terraces and structural details retain their authored proportions.",
    "properties": {
      "building_archetype_id": "glass_tower_podium_modern",
      "development_archetype_id": "glass_tower_podium_modern",
      "development_selected_variant_id": "glass_tower_twisted",
      "development_archetype_label": "Twisting glass tower with sky garden",
      "floors": 40,
      "floor_count": 40,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_side_by_side_duplex",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Side-by-side duplex",
    "description": "Two homes with separate recessed entrances and flat roofs.",
    "thumbnail": "/archetypes/buildings/calgary-modern-infill-house/variant_2.png",
    "model": {
      "variantId": "infill_duplex",
      "revision": "calgary-side-by-side-duplex-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "two_home",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 17.0,
    "depth": 25.0,
    "minWidth": 17.0,
    "minDepth": 25.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      13.34000015258789,
      21.472000122070312,
      9.0
    ],
    "reshapeDescription": "One complete two-home building at its native size. Resize the surrounding plot; the homes do not stretch or repeat.",
    "properties": {
      "building_archetype_id": "calgary_modern_infill_house",
      "development_archetype_id": "calgary_modern_infill_house",
      "development_selected_variant_id": "infill_duplex",
      "development_archetype_label": "Side-by-side duplex",
      "floors": 2,
      "floor_count": 2,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_montreal_plateau_duplex",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Plateau stacked duplex",
    "description": "Two stacked homes with bay windows and a curved outdoor stair.",
    "thumbnail": "/archetypes/buildings/montreal-duplex/variant_0.png",
    "model": {
      "variantId": "montreal_duplex_plateau",
      "revision": "montreal-plateau-duplex-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "two_home",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 16.0,
    "depth": 23.0,
    "minWidth": 16.0,
    "minDepth": 23.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      12.64909839630127,
      19.320000171661377,
      8.104999542236328
    ],
    "reshapeDescription": "One complete stacked duplex at native size, including its curved stair. Resize the surrounding plot without stretching the building.",
    "properties": {
      "building_archetype_id": "montreal_duplex",
      "development_archetype_id": "montreal_duplex",
      "development_selected_variant_id": "montreal_duplex_plateau",
      "development_archetype_label": "Plateau stacked duplex",
      "floors": 2,
      "floor_count": 2,
      "native_plot_axes": true
    }
  },
  {
    "id": "clay_courtyard_brick_modern",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Brick courtyard entrance building",
    "description": "One three-storey brick entrance building with two homes-access vestibules and two open passages. The surrounding courtyard is designed separately.",
    "thumbnail": "/archetypes/buildings/courtyard_family_housing/variant_2.png",
    "model": {
      "variantId": "courtyard_family_brick_modern",
      "revision": "courtyard-brick-modern-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "apartments",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 30.0,
    "depth": 17.0,
    "minWidth": 30.0,
    "minDepth": 17.0,
    "maxSize": 100.0,
    "nativeDimensions": [
      25.582000732421875,
      13.381999969482422,
      12.27500057220459
    ],
    "reshapeDescription": "One complete entrance building at native scale. Resize its plot without stretching the arches, passages or roof.",
    "properties": {
      "building_archetype_id": "courtyard_family_housing",
      "development_archetype_id": "courtyard_family_housing",
      "development_selected_variant_id": "courtyard_family_brick_modern",
      "development_archetype_label": "Brick courtyard entrance building",
      "floors": 3,
      "floor_count": 3,
      "native_plot_axes": true
    }
  },
  {
    "id": "showcase_market",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Grand Iron & Glass Market",
    "description": "Two occupied market galleries, an iron barrel vault and complete vendor stalls.",
    "thumbnail": "/archetypes/buildings/food_hall_market_hall/showcase-v1-front.png",
    "model": {
      "variantId": "market_historic_iron_glass",
      "revision": "showcase-market-clay-v006",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "shops",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 39.0,
    "depth": 52.0,
    "minWidth": 39.0,
    "minDepth": 52.0,
    "maxSize": 150.0,
    "nativeDimensions": [
      35.25,
      48.47999954223633,
      19.09000015258789
    ],
    "reshapeDescription": "One complete native building. Enlarge its surrounding plot or place another building.",
    "properties": {
      "building_archetype_id": "food_hall_market_hall",
      "development_archetype_id": "food_hall_market_hall",
      "development_selected_variant_id": "market_historic_iron_glass",
      "development_archetype_label": "Grand Iron & Glass Market",
      "floors": 2,
      "floor_count": 2,
      "native_plot_axes": true
    }
  },
  {
    "id": "showcase_aquatic",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Living-Roof Aquatic Centre",
    "description": "A planted glulam vault, glazed entrance arch and complete eight-lane swimming hall.",
    "thumbnail": "/archetypes/buildings/aquatic-natatorium-complex/showcase-v1-front.png",
    "model": {
      "variantId": "biophilic_mass_timber_pool",
      "revision": "showcase-aquatic-clay-v004",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "civic",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 42.0,
    "depth": 60.0,
    "minWidth": 42.0,
    "minDepth": 60.0,
    "maxSize": 150.0,
    "nativeDimensions": [
      38.36000061035156,
      56.73500061035156,
      16.597248077392578
    ],
    "reshapeDescription": "One complete native building. Enlarge its surrounding plot or place another building.",
    "properties": {
      "building_archetype_id": "aquatic_natatorium_complex",
      "development_archetype_id": "aquatic_natatorium_complex",
      "development_selected_variant_id": "biophilic_mass_timber_pool",
      "development_archetype_label": "Living-Roof Aquatic Centre",
      "floors": 1,
      "floor_count": 1,
      "native_plot_axes": true
    }
  },
  {
    "id": "showcase_tower",
    "kind": "object",
    "definitionVersion": 1,
    "readiness": "pilot",
    "label": "Gilded Terracotta Tower",
    "description": "A cream terracotta setback tower with recessed windows, sunburst relief and a gilded lantern.",
    "thumbnail": "/archetypes/buildings/art_deco_setback_tower/showcase-v1-front.png",
    "model": {
      "variantId": "art_deco_cream_terracotta",
      "revision": "showcase-tower-clay-v005",
      "method": "RLASM 6.1"
    },
    "calgaryGuide": {
      "groupId": "offices",
      "basis": "form_reference"
    },
    "zoneType": "building",
    "reshapeMode": "fixed_native",
    "width": 36.0,
    "depth": 33.0,
    "minWidth": 36.0,
    "minDepth": 33.0,
    "maxSize": 150.0,
    "nativeDimensions": [
      32.779998779296875,
      29.31721782684326,
      68.5999984741211
    ],
    "reshapeDescription": "One complete native building. Enlarge its surrounding plot or place another building.",
    "properties": {
      "building_archetype_id": "art_deco_setback_tower",
      "development_archetype_id": "art_deco_setback_tower",
      "development_selected_variant_id": "art_deco_cream_terracotta",
      "development_archetype_label": "Gilded Terracotta Tower",
      "floors": 17,
      "floor_count": 17,
      "native_plot_axes": true
    }
  }
];

export const PUBLISHED_BUILDING_ASSETS = CATALOGUE_BUILDING_ASSETS.filter(
  (asset): asset is PlaceAsset & { readiness: 'ready' } => asset.readiness === 'ready',
);
