import { useEffect,useMemo,type ReactNode } from 'react';import{useTexture}from'@react-three/drei';import*as THREE from'three';import type{ParkLegoFamilyId}from'./parkLegoFamilies';import{resolveParkGuideDimensionsM,type ParkGroundGuide}from'./parkGroundProfiles';import{PUBLIC_REALM_PROGRAM_BASE_LIFT_METERS}from'./publicRealmDepthPolicy';import type{Batch10ProgramFrame as ProgramFrame}from'./GlobeParkBatch10Assembly';
type FamilyId=Extract<ParkLegoFamilyId,'park_rooftop_intensive_garden_v0'|'park_community_healing_garden_v2'|'park_greenbelt_rail_trail_v1'|'park_foothill_heathland_trail_v2'|'park_marina_pacific_dock_v2'|'park_working_pier_brooklyn_park_v3'|'park_floating_meadow_loop_v2'|'park_lighthouse_pacific_headland_v2'|'park_lake_edge_timber_deck_v2'|'park_stormwater_natural_creek_v0'>;
const SLUG:Record<FamilyId,string>={park_rooftop_intensive_garden_v0:'rooftop-intensive-garden-v0',park_community_healing_garden_v2:'community-healing-garden-v2',park_greenbelt_rail_trail_v1:'greenbelt-rail-trail-v1',park_foothill_heathland_trail_v2:'foothill-heathland-trail-v2',park_marina_pacific_dock_v2:'marina-pacific-dock-v2',park_working_pier_brooklyn_park_v3:'working-pier-brooklyn-park-v3',park_floating_meadow_loop_v2:'floating-meadow-loop-v2',park_lighthouse_pacific_headland_v2:'lighthouse-pacific-headland-v2',park_lake_edge_timber_deck_v2:'lake-edge-timber-deck-v2',park_stormwater_natural_creek_v0:'stormwater-natural-creek-v0'};
interface Maps{map:THREE.Texture;normalMap:THREE.Texture;roughnessMap:THREE.Texture;aoMap:THREE.Texture}
function useMaps(slug:string,role:string,repeat=4):Maps{const root=`/park-skins/${slug}/adaptive-v1/${role}`,source=useTexture({map:`${root}/albedo.jpg`,normalMap:`${root}/normal.png`,roughnessMap:`${root}/roughness.jpg`,aoMap:`${root}/ao.jpg`}),maps=useMemo(()=>Object.fromEntries(Object.entries(source).map(([k,v])=>{const t=v.clone();t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);t.needsUpdate=true;return[k,t]}))as unknown as Maps,[repeat,source]);maps.map.colorSpace=THREE.SRGBColorSpace;useEffect(()=>()=>Object.values(maps).forEach(t=>t.dispose()),[maps]);return maps}
const pt=(g:ParkGroundGuide,f:ProgramFrame)=>({x:f.minX+f.width*g.x,y:f.maxY-f.height*g.y});
function Segment({a,b,width,z,maps,color}:{a:{x:number;y:number};b:{x:number;y:number};width:number;z:number;maps?:Maps;color:string}){const len=Math.hypot(b.x-a.x,b.y-a.y);return <mesh position={[(a.x+b.x)/2,(a.y+b.y)/2,z+.09]}rotation={[0,0,Math.atan2(b.y-a.y,b.x-a.x)]}><boxGeometry args={[len,width,.18]}/><meshStandardMaterial {...maps}color={color}roughness={.92}/></mesh>}
function Tree({x,y,z,low=false}:{x:number;y:number;z:number;low?:boolean}){return <group position={[x,y,z]}><mesh position={[0,0,1.35]}rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.11,.18,2.7,8]}/><meshStandardMaterial color="#584738"roughness={.98}/></mesh><mesh position={[0,0,low?2.8:3.45]}scale={low?[1.25,1.05,.6]:[1.05,.95,1]}><dodecahedronGeometry args={[1.15,1]}/><meshStandardMaterial color="#526c47"roughness={.99}/></mesh></group>}
function Pergola({x,y,z,w,d,maps}:{x:number;y:number;z:number;w:number;d:number;maps:Maps}){return <group position={[x,y,z]}>{[-1,1].flatMap(sx=>[-1,1].map(sy=><mesh key={`${sx}-${sy}`}position={[sx*w*.43,sy*d*.4,1.35]}><boxGeometry args={[.14,.14,2.7]}/><meshStandardMaterial {...maps}color="#74543e"/></mesh>))}{Array.from({length:6},(_,i)=><mesh key={i}position={[0,-d/2+i*d/5,2.78]}><boxGeometry args={[w,.13,.16]}/><meshStandardMaterial {...maps}color="#7b5a42"/></mesh>)}</group>}
function Bridge({x,y,z,w=4,maps}:{x:number;y:number;z:number;w?:number;maps:Maps}){return <group position={[x,y,z]}><mesh position={[0,0,.28]}><boxGeometry args={[w,2.2,.28]}/><meshStandardMaterial {...maps}color="#795a42"/></mesh>{[-1,1].map(s=><mesh key={s}position={[0,s*1.05,.8]}><boxGeometry args={[w,.08,1]}/><meshStandardMaterial color="#454946"roughness={.75}/></mesh>)}</group>}
export function GlobeParkBatch13Assembly({familyId,guides,frame,terrainZ}:{familyId:ParkLegoFamilyId;guides:ParkGroundGuide[];frame:ProgramFrame;terrainZ:(x:number,y:number)=>number}){const id=familyId as FamilyId,slug=SLUG[id],lift=PUBLIC_REALM_PROGRAM_BASE_LIFT_METERS,paver=useMaps(slug,'paver'),planting=useMaps(slug,'planting',5),timber=useMaps(slug,'timber'),safety=useMaps(slug,'safety'),cx=frame.minX+frame.width/2,cy=frame.minY+frame.height/2,base=terrainZ(cx,cy)+lift,paths:ReactNode[]=[];
guides.forEach((g,gi)=>{if(g.kind==='polyline'&&g.points){const ps=g.points.map(([x,y])=>({x:frame.minX+frame.width*x,y:frame.maxY-frame.height*y}));ps.slice(0,-1).forEach((p,i)=>paths.push(<Segment key={`p-${gi}-${i}`}a={p}b={ps[i+1]}width={g.strokeWidthM??3}z={Math.max(terrainZ(p.x,p.y),terrainZ(ps[i+1].x,ps[i+1].y))+lift}maps={g.color.startsWith('#5')?undefined:paver}color={g.color}/>))}else if(g.kind==='axis'){const c=pt(g,frame),len=Math.max(g.widthM??0,g.heightM??0,g.width*frame.width,g.height*frame.height),a=(g.rotationDeg??90)*Math.PI/180,p1={x:c.x-Math.cos(a)*len/2,y:c.y-Math.sin(a)*len/2},p2={x:c.x+Math.cos(a)*len/2,y:c.y+Math.sin(a)*len/2};paths.push(<Segment key={`a-${gi}`}a={p1}b={p2}width={g.strokeWidthM??3}z={Math.max(terrainZ(p1.x,p1.y),terrainZ(p2.x,p2.y))+lift}maps={g.color.startsWith('#5')?undefined:(g.color.startsWith('#7')?timber:paver)}color={g.color}/>)}});
const pads=guides.filter(g=>['rectangle','rounded_rectangle','ellipse'].includes(g.kind)).map((g,i)=>{const c=pt(g,frame),s=resolveParkGuideDimensionsM(g,frame),z=terrainZ(c.x,c.y)+lift,water=g.color.startsWith('#5')&&Number.parseInt(g.color.slice(2,4),16)>105,green=['#5','#6','#7'].includes(g.color.slice(0,2))&&!water,rot:[number,number,number]=g.kind==='ellipse'?[Math.PI/2,0,(g.rotationDeg??0)*Math.PI/180]:[0,0,(g.rotationDeg??0)*Math.PI/180];return <mesh key={i}position={[c.x,c.y,z+.12]}rotation={rot}scale={g.kind==='ellipse'?[s.width/2,s.height/2,1]:[1,1,1]}>{g.kind==='ellipse'?<cylinderGeometry args={[1,1,.24,36]}/>:<boxGeometry args={[s.width,s.height,.24]}/>} {water?<meshPhysicalMaterial color={g.color}roughness={.18}metalness={.05}/>:<meshStandardMaterial {...(green?planting:paver)}color={g.color}roughness={.93}/>}</mesh>});
const low=id.includes('foothill')||id.includes('lighthouse'),treeCount=id.includes('marina')||id.includes('floating')?4:Math.min(20,Math.max(5,Math.floor(frame.width*frame.height/1000))),trees=Array.from({length:treeCount},(_,i)=>{const x=frame.minX+frame.width*(.08+((i*.293)%.84)),y=frame.minY+frame.height*(.08+((i*.541)%.84));return <Tree key={i}x={x}y={y}z={terrainZ(x,y)+lift}low={low}/>}),extras:ReactNode[]=[];
if(id==='park_rooftop_intensive_garden_v0'||id==='park_community_healing_garden_v2')extras.push(<Pergola key="p"x={cx}y={frame.maxY-frame.height*.20}z={base}w={Math.min(8,frame.width*.28)}d={Math.min(5,frame.height*.18)}maps={timber}/>);
if(id==='park_foothill_heathland_trail_v2')Array.from({length:8},(_,i)=>{const x=frame.minX+frame.width*(.12+((i*.31)%.76)),y=frame.minY+frame.height*(.18+((i*.47)%.64));extras.push(<mesh key={i}position={[x,y,terrainZ(x,y)+lift+.35]}scale={[1.2+(i%3)*.3,.8+(i%2)*.3,.5]}><dodecahedronGeometry args={[.8,0]}/><meshStandardMaterial color="#777066"roughness={.98}/></mesh>)});
if(id==='park_marina_pacific_dock_v2')Array.from({length:Math.min(7,Math.max(3,Math.floor(frame.width/18)))},(_,i)=>{const x=frame.minX+frame.width*(.18+i*.64/Math.max(1,Math.min(7,Math.max(3,Math.floor(frame.width/18)))-1));extras.push(<Bridge key={i}x={x}y={cy+frame.height*.08}z={base}w={Math.min(3.5,frame.width*.06)}maps={timber}/>)});
if(id==='park_floating_meadow_loop_v2')[-.16,.16].forEach((d,i)=>extras.push(<Bridge key={i}x={cx+d*frame.width}y={cy}z={base+.12}w={Math.min(6,frame.width*.15)}maps={timber}/>));
if(id==='park_lighthouse_pacific_headland_v2')extras.push(<mesh key="reserve"position={[frame.minX+frame.width*.72,frame.maxY-frame.height*.42,base+.25]}rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[Math.min(5,frame.width*.06),Math.min(5,frame.width*.06),.3,32]}/><meshStandardMaterial {...paver}color="#99928b"/></mesh>);
if(id==='park_stormwater_natural_creek_v0')[-.16,.18].forEach((d,i)=>extras.push(<Bridge key={i}x={cx+d*frame.width}y={cy-d*frame.height*.25}z={base+.15}w={Math.min(6,frame.width*.10)}maps={timber}/>));
return <group>{pads}{paths}{trees}{extras}<mesh position={[cx,cy,base-.02]}><boxGeometry args={[.01,.01,.01]}/><meshStandardMaterial {...safety}/></mesh></group>}
