import { useEffect,useMemo,type ReactNode } from 'react';import{useTexture}from'@react-three/drei';import*as THREE from'three';import type{ParkLegoFamilyId}from'./parkLegoFamilies';import{resolveParkGuideDimensionsM,type ParkGroundGuide}from'./parkGroundProfiles';import{PUBLIC_REALM_PROGRAM_BASE_LIFT_METERS}from'./publicRealmDepthPolicy';import type{Batch10ProgramFrame as ProgramFrame}from'./GlobeParkBatch10Assembly';import{batch21ParkSkinForSelection}from'./parkBatch21Skins';import{batch23ParkSkinForSelection}from'./parkBatch23Skins';import{batch26ParkSkinForSelection}from'./parkBatch26Skins';
type FamilyId=Extract<ParkLegoFamilyId,'park_rooftop_intensive_garden_v0'|'park_community_healing_garden_v2'|'park_greenbelt_rail_trail_v1'|'park_foothill_heathland_trail_v2'|'park_marina_pacific_dock_v2'|'park_working_pier_brooklyn_park_v3'|'park_floating_meadow_loop_v2'|'park_lighthouse_pacific_headland_v2'|'park_lake_edge_timber_deck_v2'|'park_stormwater_natural_creek_v0'>;
const SLUG:Record<FamilyId,string>={park_rooftop_intensive_garden_v0:'rooftop-intensive-garden-v0',park_community_healing_garden_v2:'community-healing-garden-v2',park_greenbelt_rail_trail_v1:'greenbelt-rail-trail-v1',park_foothill_heathland_trail_v2:'foothill-heathland-trail-v2',park_marina_pacific_dock_v2:'marina-pacific-dock-v2',park_working_pier_brooklyn_park_v3:'working-pier-brooklyn-park-v3',park_floating_meadow_loop_v2:'floating-meadow-loop-v2',park_lighthouse_pacific_headland_v2:'lighthouse-pacific-headland-v2',park_lake_edge_timber_deck_v2:'lake-edge-timber-deck-v2',park_stormwater_natural_creek_v0:'stormwater-natural-creek-v0'};
interface Maps{map:THREE.Texture;normalMap:THREE.Texture;roughnessMap:THREE.Texture;aoMap:THREE.Texture}
function useMaps(slug:string,role:string,repeat=4):Maps{const root=`/park-skins/${slug}/adaptive-v1/${role}`,source=useTexture({map:`${root}/albedo.jpg`,normalMap:`${root}/normal.png`,roughnessMap:`${root}/roughness.jpg`,aoMap:`${root}/ao.jpg`}),maps=useMemo(()=>Object.fromEntries(Object.entries(source).map(([k,v])=>{const t=v.clone();t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);t.needsUpdate=true;return[k,t]}))as unknown as Maps,[repeat,source]);maps.map.colorSpace=THREE.SRGBColorSpace;useEffect(()=>()=>Object.values(maps).forEach(t=>t.dispose()),[maps]);return maps}
const pt=(g:ParkGroundGuide,f:ProgramFrame)=>({x:f.minX+f.width*g.x,y:f.maxY-f.height*g.y});
function Segment({a,b,width,z,maps,color}:{a:{x:number;y:number};b:{x:number;y:number};width:number;z:number;maps?:Maps;color:string}){const len=Math.hypot(b.x-a.x,b.y-a.y);return <mesh position={[(a.x+b.x)/2,(a.y+b.y)/2,z+.09]}rotation={[0,0,Math.atan2(b.y-a.y,b.x-a.x)]}><boxGeometry args={[len,width,.18]}/><meshStandardMaterial {...maps}color={color}roughness={.92}/></mesh>}
function Tree({x,y,z,low=false}:{x:number;y:number;z:number;low?:boolean}){return <group position={[x,y,z]}><mesh position={[0,0,1.35]}rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.11,.18,2.7,8]}/><meshStandardMaterial color="#584738"roughness={.98}/></mesh><mesh position={[0,0,low?2.8:3.45]}scale={low?[1.25,1.05,.6]:[1.05,.95,1]}><dodecahedronGeometry args={[1.15,1]}/><meshStandardMaterial color="#526c47"roughness={.99}/></mesh></group>}
function Pergola({x,y,z,w,d,maps}:{x:number;y:number;z:number;w:number;d:number;maps:Maps}){return <group position={[x,y,z]}>{[-1,1].flatMap(sx=>[-1,1].map(sy=><mesh key={`${sx}-${sy}`}position={[sx*w*.43,sy*d*.4,1.35]}><boxGeometry args={[.14,.14,2.7]}/><meshStandardMaterial {...maps}color="#74543e"/></mesh>))}{Array.from({length:6},(_,i)=><mesh key={i}position={[0,-d/2+i*d/5,2.78]}><boxGeometry args={[w,.13,.16]}/><meshStandardMaterial {...maps}color="#7b5a42"/></mesh>)}</group>}
function Bridge({x,y,z,w=4,maps}:{x:number;y:number;z:number;w?:number;maps:Maps}){return <group position={[x,y,z]}><mesh position={[0,0,.28]}><boxGeometry args={[w,2.2,.28]}/><meshStandardMaterial {...maps}color="#795a42"/></mesh>{[-1,1].map(s=><mesh key={s}position={[0,s*1.05,.8]}><boxGeometry args={[w,.08,1]}/><meshStandardMaterial color="#454946"roughness={.75}/></mesh>)}</group>}
function Pavilion({x,y,z,w,d,maps,glass=false}:{x:number;y:number;z:number;w:number;d:number;maps:Maps;glass?:boolean}){return <group position={[x,y,z]}>{[-1,1].flatMap(sx=>[-1,1].map(sy=><mesh key={`${sx}-${sy}`}position={[sx*w*.42,sy*d*.40,1.6]}><boxGeometry args={[.18,.18,3.2]}/><meshStandardMaterial {...maps}color="#ffffff"/></mesh>))}<mesh position={[0,0,3.3]}><boxGeometry args={[w,d,.3]}/>{glass?<meshPhysicalMaterial color="#c9d6d4"transparent opacity={.52}roughness={.18}/>:<meshStandardMaterial {...maps}color="#ffffff"/>}</mesh></group>}
function Lighthouse({x,y,z,scale=1,fortress=false}:{x:number;y:number;z:number;scale?:number;fortress?:boolean}){return <group position={[x,y,z]} scale={scale}>{fortress&&<mesh position={[0,0,.75]}><cylinderGeometry args={[3.5,4.3,1.5,8]}/><meshStandardMaterial color="#8b8172"roughness={.95}/></mesh>}<mesh position={[0,0,3.3]}><cylinderGeometry args={[.75,1.1,6.6,12]}/><meshStandardMaterial color="#eee7d7"roughness={.82}/></mesh><mesh position={[0,0,6.75]}><cylinderGeometry args={[1.05,1.05,.7,12]}/><meshPhysicalMaterial color="#657b81"transparent opacity={.66}roughness={.2}/></mesh><mesh position={[0,0,7.45]}><coneGeometry args={[1.25,.9,12]}/><meshStandardMaterial color="#6f3431"roughness={.82}/></mesh></group>}
function Kiosk({x,y,z,maps}:{x:number;y:number;z:number;maps:Maps}){return <group position={[x,y,z]}><mesh position={[0,0,1.05]}><boxGeometry args={[3.3,2.4,2.1]}/><meshStandardMaterial {...maps}color="#ffffff"/></mesh><mesh position={[0,0,2.5]}rotation={[0,0,Math.PI/4]}><coneGeometry args={[2.2,1.1,4]}/><meshStandardMaterial color="#515b59"roughness={.75}/></mesh></group>}
export function GlobeParkBatch13Assembly({familyId,guides,frame,terrainZ,archetypeId,variantId}:{familyId:ParkLegoFamilyId;guides:ParkGroundGuide[];frame:ProgramFrame;terrainZ:(x:number,y:number)=>number;archetypeId?:string;variantId?:string}){const id=familyId as FamilyId,variantSkin=batch26ParkSkinForSelection(archetypeId??'',variantId??'')??batch23ParkSkinForSelection(archetypeId??'',variantId??'')??batch21ParkSkinForSelection(archetypeId??'',variantId??''),slug=variantSkin?.slug??SLUG[id],lift=PUBLIC_REALM_PROGRAM_BASE_LIFT_METERS,paver=useMaps(slug,'paver'),lawn=useMaps(slug,'lawn',5),planting=useMaps(slug,'planting',5),timber=useMaps(slug,'timber'),safety=useMaps(slug,'safety'),cx=frame.minX+frame.width/2,cy=frame.minY+frame.height/2,base=terrainZ(cx,cy)+lift,paths:ReactNode[]=[];
if(id==='park_community_healing_garden_v2'&&variantId&&variantId!=='garden_healing'){
const allotment=variantId==='garden_classic_allotment',permaculture=variantId==='garden_permaculture_farm',bedCount=allotment?12:permaculture?7:8;
return <group>
<mesh position={[cx,cy,base+.10]}><boxGeometry args={[frame.width*.92,frame.height*.88,.20]}/><meshStandardMaterial {...(allotment?lawn:paver)}color={allotment?'#9eb47c':'#ffffff'}roughness={.95}/></mesh>
{allotment&&<><Segment a={{x:frame.minX+frame.width*.06,y:cy}}b={{x:frame.maxX-frame.width*.06,y:cy}}width={2.1}z={base+.20}maps={paver}color="#ffffff"/><Segment a={{x:cx,y:frame.minY+frame.height*.06}}b={{x:cx,y:frame.maxY-frame.height*.06}}width={2.1}z={base+.20}maps={paver}color="#ffffff"/></>}
{allotment&&<>{[-1,1].map(side=><mesh key={`garden-edge-y-${side}`}position={[cx,cy+side*frame.height*.39,base+1.25]}><boxGeometry args={[frame.width*.80,1.6,.34]}/><meshStandardMaterial {...planting}color="#ffffff"roughness={.98}/></mesh>)}{[-1,1].map(side=><mesh key={`garden-edge-x-${side}`}position={[cx+side*frame.width*.41,cy,base+1.25]}><boxGeometry args={[1.6,frame.height*.70,.34]}/><meshStandardMaterial {...planting}color="#ffffff"roughness={.98}/></mesh>)}</>}
{Array.from({length:bedCount},(_,i)=>{const cols=allotment?4:permaculture?1:4,a=i*Math.PI*2/bedCount,x=allotment?frame.minX+frame.width*(.14+(i%cols)*.72/(cols-1)):permaculture?cx+Math.cos(a)*frame.width*(.18+(i%2)*.09):frame.minX+frame.width*(.18+(i%cols)*.64/(cols-1)),y=allotment?frame.minY+frame.height*(.22+Math.floor(i/cols)*.48/2):permaculture?cy+Math.sin(a)*frame.height*(.17+(i%2)*.10):cy+(Math.floor(i/cols)-.5)*frame.height*.30,z=base+1.2,bedW=Math.min(allotment?5.2:3.8,frame.width*.18),bedD=Math.min(allotment?2.35:2.5,frame.height*.13);return <group key={i}position={[x,y,z]}rotation={[0,0,permaculture?a:0]}><mesh position={[0,0,.42]}><boxGeometry args={[bedW,bedD,.84]}/><meshStandardMaterial {...timber}color="#ffffff"roughness={.94}/></mesh><mesh position={[0,0,.89]}><boxGeometry args={[bedW*.88,bedD*.70,.14]}/><meshStandardMaterial {...planting}color="#ffffff"roughness={.99}/></mesh>{Array.from({length:6},(_,crop)=>{const row=crop%3-1,line=Math.floor(crop/3)-.5;return <mesh key={crop}position={[row*bedW*.23,line*bedD*.35,1.16]}><sphereGeometry args={[.30+(crop%2)*.07,8,6]}/><meshStandardMaterial color={['#3e7e36','#72a84c','#b18a3f'][crop%3]}roughness={.98}/></mesh>})}</group>})}
{allotment&&Array.from({length:4},(_,i)=>{const x=frame.minX+frame.width*(.14+i*.72/3),y=frame.maxY-frame.height*.13,z=base+1.2;return <group key={`shed-${i}`}position={[x,y,z]}><mesh position={[0,0,.8]}><boxGeometry args={[2.4,1.8,1.6]}/><meshStandardMaterial color={['#8f4e3f','#556f58','#b59a55','#62788e'][i]}roughness={.9}/></mesh><mesh position={[0,0,1.8]}rotation={[0,0,Math.PI/4]}><coneGeometry args={[1.75,.9,4]}/><meshStandardMaterial {...timber}color="#ffffff"roughness={.94}/></mesh></group>})}
{allotment&&Array.from({length:4},(_,i)=>{const x=frame.minX+frame.width*(.18+i*.64/3),y=frame.minY+frame.height*.11;return <Tree key={`orchard-${i}`}x={x}y={y}z={base+1.2}low/>})}
{permaculture&&<group position={[frame.maxX-frame.width*.19,frame.maxY-frame.height*.20,base]}><mesh position={[0,0,1.25]}><boxGeometry args={[Math.min(5,frame.width*.18),Math.min(3.2,frame.height*.13),2.5]}/><meshPhysicalMaterial color="#bfd2c9"transparent opacity={.48}roughness={.18}/></mesh><mesh position={[0,0,2.65]}rotation={[0,0,Math.PI/4]}><coneGeometry args={[Math.min(3.4,frame.width*.12),1.2,4]}/><meshPhysicalMaterial color="#cadbd3"transparent opacity={.52}roughness={.16}/></mesh></group>}
{!allotment&&<Pergola x={cx}y={frame.maxY-frame.height*.18}z={base+.2}w={Math.min(8,frame.width*.28)}d={Math.min(5,frame.height*.18)}maps={timber}/>}</group>;
}
guides.forEach((g,gi)=>{if(g.kind==='polyline'&&g.points){const ps=g.points.map(([x,y])=>({x:frame.minX+frame.width*x,y:frame.maxY-frame.height*y}));ps.slice(0,-1).forEach((p,i)=>paths.push(<Segment key={`p-${gi}-${i}`}a={p}b={ps[i+1]}width={g.strokeWidthM??3}z={Math.max(terrainZ(p.x,p.y),terrainZ(ps[i+1].x,ps[i+1].y))+lift}maps={g.color.startsWith('#5')?undefined:paver}color={g.color}/>))}else if(g.kind==='axis'){const c=pt(g,frame),len=Math.max(g.widthM??0,g.heightM??0,g.width*frame.width,g.height*frame.height),a=(g.rotationDeg??90)*Math.PI/180,p1={x:c.x-Math.cos(a)*len/2,y:c.y-Math.sin(a)*len/2},p2={x:c.x+Math.cos(a)*len/2,y:c.y+Math.sin(a)*len/2};paths.push(<Segment key={`a-${gi}`}a={p1}b={p2}width={g.strokeWidthM??3}z={Math.max(terrainZ(p1.x,p1.y),terrainZ(p2.x,p2.y))+lift}maps={g.color.startsWith('#5')?undefined:(g.color.startsWith('#7')?timber:paver)}color={g.color}/>)}});
const pads=guides.filter(g=>['rectangle','rounded_rectangle','ellipse'].includes(g.kind)).map((g,i)=>{const c=pt(g,frame),s=resolveParkGuideDimensionsM(g,frame),z=terrainZ(c.x,c.y)+lift,water=g.color.startsWith('#5')&&Number.parseInt(g.color.slice(2,4),16)>105,green=['#5','#6','#7'].includes(g.color.slice(0,2))&&!water,rot:[number,number,number]=g.kind==='ellipse'?[Math.PI/2,0,(g.rotationDeg??0)*Math.PI/180]:[0,0,(g.rotationDeg??0)*Math.PI/180];return <mesh key={i}position={[c.x,c.y,z+.12]}rotation={rot}scale={g.kind==='ellipse'?[s.width/2,s.height/2,1]:[1,1,1]}>{g.kind==='ellipse'?<cylinderGeometry args={[1,1,.24,36]}/>:<boxGeometry args={[s.width,s.height,.24]}/>} {water?<meshPhysicalMaterial color={g.color}roughness={.18}metalness={.05}/>:<meshStandardMaterial {...(green?planting:paver)}color={variantSkin?'#ffffff':g.color}roughness={.93}/>}</mesh>});
const low=id.includes('foothill')||id.includes('lighthouse'),treeCount=id.includes('marina')||id.includes('floating')?4:Math.min(20,Math.max(5,Math.floor(frame.width*frame.height/1000))),trees=Array.from({length:treeCount},(_,i)=>{const x=frame.minX+frame.width*(.08+((i*.293)%.84)),y=frame.minY+frame.height*(.08+((i*.541)%.84));return <Tree key={i}x={x}y={y}z={terrainZ(x,y)+lift}low={low}/>}),extras:ReactNode[]=[];
if(id==='park_rooftop_intensive_garden_v0'||id==='park_community_healing_garden_v2')extras.push(<Pergola key="p"x={cx}y={frame.maxY-frame.height*.20}z={base}w={Math.min(8,frame.width*.28)}d={Math.min(5,frame.height*.18)}maps={timber}/>);
if(id==='park_greenbelt_rail_trail_v1'){
if(variantId==='greenbelt_buffer_park_v0')extras.push(<Pavilion key="pavilion"x={frame.maxX-frame.width*.20}y={frame.maxY-frame.height*.20}z={base}w={Math.min(9,frame.width*.10)}d={Math.min(6,frame.height*.18)}maps={timber}/>);
if(variantId==='greenbelt_buffer_park_v2')Array.from({length:8},(_,i)=>{const x=frame.minX+frame.width*(.10+i*.80/7),y=cy+(i%2?1:-1)*frame.height*.24;extras.push(<mesh key={i}position={[x,y,terrainZ(x,y)+lift+.65]}><boxGeometry args={[Math.min(7,frame.width*.07),1.5,1.3]}/><meshStandardMaterial {...planting}color="#ffffff"roughness={.98}/></mesh>)});
if(variantId==='greenbelt_buffer_park_v3')[-.18,.18].forEach((d,i)=>extras.push(<mesh key={i}position={[cx+d*frame.width,cy,base+.15]}><boxGeometry args={[Math.min(18,frame.width*.18),Math.min(28,frame.height*.45),.3]}/><meshStandardMaterial {...safety}color="#ffffff"roughness={.9}/></mesh>));
}
if(id==='park_foothill_heathland_trail_v2'){
const boulderCount=variantId==='foothill_trail_park_v3'?14:8;Array.from({length:boulderCount},(_,i)=>{const x=frame.minX+frame.width*(.12+((i*.31)%.76)),y=frame.minY+frame.height*(.18+((i*.47)%.64));extras.push(<mesh key={i}position={[x,y,terrainZ(x,y)+lift+.35]}scale={[1.2+(i%3)*.3,.8+(i%2)*.3,.5]}><dodecahedronGeometry args={[.8,0]}/><meshStandardMaterial color={variantId==='foothill_trail_park_v0'?'#9a846a':variantId==='foothill_trail_park_v3'?'#7b7f7c':'#777066'}roughness={.98}/></mesh>)});if(variantId==='foothill_trail_park_v1')Array.from({length:7},(_,i)=>{const x=frame.minX+frame.width*(.15+i*.70/6),y=cy+(i%2?1:-1)*frame.height*.18;extras.push(<Tree key={`e-${i}`}x={x}y={y}z={terrainZ(x,y)+lift}/>)});
}
if(id==='park_marina_pacific_dock_v2'){
const count=variantId==='marina_yacht_harbor_v0'?3:variantId==='marina_yacht_harbor_v3'?4:Math.min(7,Math.max(3,Math.floor(frame.width/18)));Array.from({length:count},(_,i)=>{const x=frame.minX+frame.width*(.18+i*.64/Math.max(1,count-1));extras.push(<Bridge key={i}x={x}y={cy+frame.height*.08}z={base}w={Math.min(variantId==='marina_yacht_harbor_v3'?8:4,frame.width*.08)}maps={timber}/>)});if(variantId==='marina_yacht_harbor_v1')extras.push(<Pavilion key="fish"x={frame.minX+frame.width*.18}y={frame.maxY-frame.height*.16}z={base}w={Math.min(12,frame.width*.18)}d={Math.min(7,frame.height*.16)}maps={paver}/>);
}
if(id==='park_working_pier_brooklyn_park_v3'){
if(variantId==='working_pier_wharf_conversion_v0')extras.push(<Pavilion key="market"x={cx}y={cy}z={base}w={Math.min(30,frame.width*.46)}d={Math.min(16,frame.height*.34)}maps={timber}/>);
if(variantId==='working_pier_wharf_conversion_v1')Array.from({length:Math.min(7,Math.max(3,Math.floor(frame.width/16)))},(_,i)=>{const x=frame.minX+frame.width*(.14+i*.72/Math.max(1,Math.min(6,Math.floor(frame.width/16)-1)));extras.push(<Kiosk key={i}x={x}y={cy}z={base}maps={timber}/>)});
if(variantId==='working_pier_wharf_conversion_v2')[-.18,.18].forEach((d,i)=>extras.push(<Segment key={i}a={{x:frame.minX+frame.width*.06,y:cy+d*frame.height}}b={{x:frame.maxX-frame.width*.06,y:cy+d*frame.height}}width={1.1}z={base+.28}maps={paver}color="#ffffff"/>));
}
if(id==='park_floating_meadow_loop_v2'){
if(variantId==='floating_park_pool_v0'){[-1,1].forEach((s,i)=>extras.push(<mesh key={`h-${i}`}position={[cx+s*frame.width*.17,cy,base+.32]}><boxGeometry args={[frame.width*.28,frame.height*.18,.64]}/><meshPhysicalMaterial color="#4d91a1"roughness={.16}/></mesh>,<mesh key={`v-${i}`}position={[cx,cy+s*frame.height*.17,base+.33]}><boxGeometry args={[frame.width*.18,frame.height*.28,.66]}/><meshPhysicalMaterial color="#4d91a1"roughness={.16}/></mesh>));}
else if(variantId==='floating_park_pool_v1')extras.push(<mesh key="bath"position={[cx,cy,base+.3]}><boxGeometry args={[frame.width*.55,frame.height*.48,.6]}/><meshPhysicalMaterial color="#548c99"roughness={.16}/></mesh>);
else if(variantId==='floating_park_pool_v3'){Array.from({length:9},(_,i)=>{const a=i*Math.PI*2/9,r=.12+(i%3)*.09,x=cx+Math.cos(a)*frame.width*r,y=cy+Math.sin(a)*frame.height*r;extras.push(<group key={i}position={[x,y,base]}><mesh position={[0,0,1.7]}><cylinderGeometry args={[1.8,.65,3.4,12]}/><meshStandardMaterial color="#d4cfbd"roughness={.82}/></mesh><mesh position={[0,0,3.35]}scale={[2.0,2.0,.45]}><sphereGeometry args={[1,16,8]}/><meshStandardMaterial {...planting}color="#ffffff"/></mesh></group>)})}
else [-.16,.16].forEach((d,i)=>extras.push(<Bridge key={i}x={cx+d*frame.width}y={cy}z={base+.12}w={Math.min(6,frame.width*.15)}maps={timber}/>));
}
if(id==='park_lighthouse_pacific_headland_v2'){
const lx=frame.minX+frame.width*.72,ly=frame.maxY-frame.height*.42;extras.push(<mesh key="reserve"position={[lx,ly,base+.25]}rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[Math.min(5,frame.width*.06),Math.min(5,frame.width*.06),.3,32]}/><meshStandardMaterial {...paver}color="#ffffff"/></mesh>,<Lighthouse key="light"x={lx}y={ly}z={base+.4}scale={variantId==='lighthouse_point_park_v3'?1.25:.9}fortress={variantId==='lighthouse_point_park_v3'}/>);if(variantId==='lighthouse_point_park_v0')extras.push(<Pavilion key="cottage"x={lx-frame.width*.12}y={ly}z={base}w={Math.min(8,frame.width*.08)}d={Math.min(5,frame.height*.08)}maps={paver}/>);
}
if(id==='park_lake_edge_timber_deck_v2'){
const tiers=variantId==='lake_edge_plaza_v0'?3:variantId==='lake_edge_plaza_v3'?2:1;Array.from({length:tiers},(_,i)=>extras.push(<mesh key={i}position={[cx,frame.minY+frame.height*(.16+i*.10),base+.15+i*.24]}><boxGeometry args={[frame.width*(.78-i*.09),Math.min(5,frame.height*.14),.3]}/><meshStandardMaterial {...(variantId==='lake_edge_plaza_v2'?timber:paver)}color="#ffffff"/></mesh>));if(variantId==='lake_edge_plaza_v1')[-.24,0,.24].forEach((d,i)=>extras.push(<Pavilion key={i}x={cx+d*frame.width}y={cy}z={base}w={Math.min(7,frame.width*.08)}d={Math.min(4,frame.height*.12)}maps={timber}/>));
}
if(id==='park_stormwater_natural_creek_v0')[-.16,.18].forEach((d,i)=>extras.push(<Bridge key={i}x={cx+d*frame.width}y={cy-d*frame.height*.25}z={base+.15}w={Math.min(6,frame.width*.10)}maps={timber}/>));
return <group>{pads}{paths}{trees}{extras}<mesh position={[cx,cy,base-.02]}><boxGeometry args={[.01,.01,.01]}/><meshStandardMaterial {...safety}/></mesh></group>}
