"""
Architectural style registry for the 3D Development Platform.

Defines 20 architectural styles with prompt enrichment, material selection,
and geometry parameters used by both procedural and AI-based generation.
"""

from dataclasses import dataclass, field


@dataclass
class ArchitecturalStyle:
    """Complete architectural style definition."""

    id: str
    name: str
    description: str
    # Materials
    facade_material: str = "concrete"
    secondary_material: str = "glass"
    roof_material: str = "roof_tile"
    color_overrides: dict = field(default_factory=dict)
    # Geometry
    preferred_roof_types: list[str] = field(default_factory=lambda: ["flat"])
    window_density: float = 0.5
    window_width: float = 1.2
    window_height: float = 1.5
    balcony_probability: float = 0.3
    cornice_enabled: bool = True
    # AI prompt modifiers
    prompt_prefix: str = ""
    prompt_suffix: str = ""
    negative_prompt: str = ""
    meshy_art_style: str = "realistic"
    # Metadata
    thumbnail_url: str | None = None
    tags: list[str] = field(default_factory=list)


ARCHITECTURAL_STYLES: dict[str, ArchitecturalStyle] = {
    "modern": ArchitecturalStyle(
        id="modern",
        name="Modern",
        description="Clean lines, large glass panels, minimal ornamentation",
        facade_material="concrete",
        secondary_material="glass",
        roof_material="concrete",
        preferred_roof_types=["flat"],
        window_density=0.7,
        window_width=1.8,
        window_height=2.0,
        balcony_probability=0.4,
        cornice_enabled=False,
        prompt_prefix="Modern contemporary architecture,",
        prompt_suffix="clean lines, large glass windows, minimalist facade, flat roof",
        negative_prompt="ornate, classical, decorative, old-fashioned",
        tags=["contemporary", "minimal", "glass"],
    ),
    "classical": ArchitecturalStyle(
        id="classical",
        name="Classical",
        description="Symmetrical facades, columns, pediments, ornamental details",
        facade_material="concrete",
        secondary_material="concrete",
        roof_material="roof_tile",
        color_overrides={"facade": [0.92, 0.89, 0.83, 1.0]},
        preferred_roof_types=["hipped", "gabled"],
        window_density=0.5,
        window_width=1.0,
        window_height=1.8,
        balcony_probability=0.2,
        cornice_enabled=True,
        prompt_prefix="Classical Neoclassical architecture,",
        prompt_suffix="symmetrical facade, columns, pediment, ornamental cornice, stone facade",
        negative_prompt="modern, glass, industrial, minimalist",
        tags=["traditional", "ornamental", "stone"],
    ),
    "brutalist": ArchitecturalStyle(
        id="brutalist",
        name="Brutalist",
        description="Raw exposed concrete, massive geometric forms, minimal windows",
        facade_material="concrete",
        secondary_material="concrete",
        roof_material="concrete",
        color_overrides={"facade": [0.65, 0.62, 0.58, 1.0]},
        preferred_roof_types=["flat"],
        window_density=0.3,
        window_width=0.8,
        window_height=1.2,
        balcony_probability=0.1,
        cornice_enabled=False,
        prompt_prefix="Brutalist architecture,",
        prompt_suffix="raw exposed concrete, massive geometric forms, monolithic, bold shapes",
        negative_prompt="glass, decorative, ornate, colorful, wood",
        tags=["concrete", "monolithic", "geometric"],
    ),
    "art_deco": ArchitecturalStyle(
        id="art_deco",
        name="Art Deco",
        description="Geometric ornamentation, stepped forms, metallic accents",
        facade_material="concrete",
        secondary_material="metal",
        roof_material="metal",
        color_overrides={"facade": [0.85, 0.82, 0.75, 1.0], "metal": [0.83, 0.69, 0.22, 1.0]},
        preferred_roof_types=["flat"],
        window_density=0.5,
        window_width=1.0,
        window_height=2.0,
        balcony_probability=0.3,
        cornice_enabled=True,
        prompt_prefix="Art Deco architecture,",
        prompt_suffix="geometric ornamentation, stepped facade, gold and chrome accents, 1920s style",
        negative_prompt="rustic, modern minimalist, organic shapes",
        tags=["decorative", "geometric", "glamorous"],
    ),
    "industrial": ArchitecturalStyle(
        id="industrial",
        name="Industrial",
        description="Exposed steel, brick, large utilitarian windows",
        facade_material="brick",
        secondary_material="metal",
        roof_material="metal",
        preferred_roof_types=["flat", "gabled"],
        window_density=0.6,
        window_width=1.5,
        window_height=2.0,
        balcony_probability=0.0,
        cornice_enabled=False,
        prompt_prefix="Industrial architecture,",
        prompt_suffix="exposed steel beams, red brick, large factory windows, utilitarian design",
        negative_prompt="residential, ornate, classical, suburban",
        tags=["urban", "loft", "warehouse"],
    ),
    "victorian": ArchitecturalStyle(
        id="victorian",
        name="Victorian",
        description="Ornate details, bay windows, decorative trim, steep roofs",
        facade_material="wood",
        secondary_material="wood",
        roof_material="roof_tile",
        color_overrides={"facade": [0.75, 0.68, 0.55, 1.0]},
        preferred_roof_types=["gabled", "hipped"],
        window_density=0.55,
        window_width=0.9,
        window_height=1.6,
        balcony_probability=0.4,
        cornice_enabled=True,
        prompt_prefix="Victorian architecture,",
        prompt_suffix="ornate trim, bay windows, steep gabled roof, decorative woodwork, painted facade",
        negative_prompt="modern, minimalist, concrete, industrial",
        tags=["ornamental", "historical", "residential"],
    ),
    "mediterranean": ArchitecturalStyle(
        id="mediterranean",
        name="Mediterranean",
        description="Stucco walls, terracotta roofs, arched windows, courtyards",
        facade_material="concrete",
        secondary_material="wood",
        roof_material="roof_tile",
        color_overrides={"facade": [0.95, 0.90, 0.80, 1.0], "roof_tile": [0.65, 0.35, 0.18, 1.0]},
        preferred_roof_types=["hipped"],
        window_density=0.45,
        window_width=1.0,
        window_height=1.6,
        balcony_probability=0.5,
        cornice_enabled=True,
        prompt_prefix="Mediterranean architecture,",
        prompt_suffix="warm stucco walls, terracotta tile roof, arched windows, wrought iron balconies",
        negative_prompt="modern glass, industrial, cold, grey, flat roof",
        tags=["warm", "coastal", "stucco"],
    ),
    "scandinavian": ArchitecturalStyle(
        id="scandinavian",
        name="Scandinavian",
        description="Light wood cladding, simple forms, large windows, natural materials",
        facade_material="wood",
        secondary_material="glass",
        roof_material="metal",
        color_overrides={"facade": [0.82, 0.75, 0.62, 1.0]},
        preferred_roof_types=["gabled", "flat"],
        window_density=0.65,
        window_width=1.4,
        window_height=1.8,
        balcony_probability=0.2,
        cornice_enabled=False,
        prompt_prefix="Scandinavian Nordic architecture,",
        prompt_suffix="light wood cladding, large windows, simple clean forms, natural materials, cozy",
        negative_prompt="ornate, classical, dark, industrial",
        tags=["nordic", "wood", "minimal"],
    ),
    "colonial": ArchitecturalStyle(
        id="colonial",
        name="Colonial",
        description="Symmetrical facade, shuttered windows, columned porch",
        facade_material="wood",
        secondary_material="wood",
        roof_material="roof_tile",
        color_overrides={"facade": [0.90, 0.88, 0.85, 1.0]},
        preferred_roof_types=["gabled", "hipped"],
        window_density=0.5,
        window_width=0.9,
        window_height=1.5,
        balcony_probability=0.1,
        cornice_enabled=True,
        prompt_prefix="Colonial American architecture,",
        prompt_suffix="symmetrical facade, window shutters, columned front porch, dormer windows",
        negative_prompt="modern, industrial, glass facade, concrete",
        tags=["traditional", "american", "residential"],
    ),
    "japanese_modern": ArchitecturalStyle(
        id="japanese_modern",
        name="Japanese Modern",
        description="Minimalist forms, natural materials, indoor-outdoor flow",
        facade_material="wood",
        secondary_material="glass",
        roof_material="metal",
        color_overrides={"facade": [0.55, 0.48, 0.38, 1.0]},
        preferred_roof_types=["flat", "gabled"],
        window_density=0.6,
        window_width=1.6,
        window_height=2.2,
        balcony_probability=0.2,
        cornice_enabled=False,
        prompt_prefix="Japanese modern architecture,",
        prompt_suffix="minimalist design, natural wood, large glass walls, zen aesthetic, clean geometry",
        negative_prompt="ornate, European, classical, heavy decoration",
        tags=["zen", "minimal", "wood"],
    ),
    "neo_gothic": ArchitecturalStyle(
        id="neo_gothic",
        name="Neo-Gothic",
        description="Pointed arches, ribbed vaults, flying buttresses, vertical emphasis",
        facade_material="concrete",
        secondary_material="concrete",
        roof_material="roof_tile",
        color_overrides={"facade": [0.70, 0.65, 0.58, 1.0]},
        preferred_roof_types=["gabled"],
        window_density=0.45,
        window_width=0.8,
        window_height=2.5,
        balcony_probability=0.0,
        cornice_enabled=True,
        prompt_prefix="Neo-Gothic architecture,",
        prompt_suffix="pointed arches, stone facade, tall narrow windows, spires, dramatic vertical lines",
        negative_prompt="modern, horizontal, minimalist, glass curtain wall",
        tags=["gothic", "dramatic", "historical"],
    ),
    "mid_century_modern": ArchitecturalStyle(
        id="mid_century_modern",
        name="Mid-Century Modern",
        description="Post-and-beam construction, floor-to-ceiling glass, integration with nature",
        facade_material="wood",
        secondary_material="glass",
        roof_material="concrete",
        color_overrides={"facade": [0.72, 0.58, 0.40, 1.0]},
        preferred_roof_types=["flat", "gabled"],
        window_density=0.75,
        window_width=2.0,
        window_height=2.4,
        balcony_probability=0.3,
        cornice_enabled=False,
        prompt_prefix="Mid-century modern architecture,",
        prompt_suffix="post-and-beam, floor-to-ceiling glass, flat or low-slope roof, open plan, 1950s-60s style",
        negative_prompt="ornate, Victorian, heavy masonry, small windows",
        tags=["retro", "glass", "open-plan"],
    ),
    "tropical": ArchitecturalStyle(
        id="tropical",
        name="Tropical",
        description="Open-air design, deep overhangs, natural ventilation, lush integration",
        facade_material="wood",
        secondary_material="glass",
        roof_material="roof_tile",
        color_overrides={"facade": [0.80, 0.72, 0.55, 1.0]},
        preferred_roof_types=["hipped", "gabled"],
        window_density=0.6,
        window_width=1.8,
        window_height=2.0,
        balcony_probability=0.6,
        cornice_enabled=False,
        prompt_prefix="Tropical resort architecture,",
        prompt_suffix="deep overhangs, open-air design, natural ventilation, thatched or tile roof, lush surroundings",
        negative_prompt="enclosed, cold climate, heavy insulation, small windows",
        tags=["resort", "open-air", "natural"],
    ),
    "high_tech": ArchitecturalStyle(
        id="high_tech",
        name="High-Tech",
        description="Exposed structural systems, high-tech materials, mechanical aesthetics",
        facade_material="metal",
        secondary_material="glass",
        roof_material="metal",
        color_overrides={"metal": [0.70, 0.70, 0.72, 1.0]},
        preferred_roof_types=["flat"],
        window_density=0.65,
        window_width=1.5,
        window_height=1.8,
        balcony_probability=0.2,
        cornice_enabled=False,
        prompt_prefix="High-tech architecture,",
        prompt_suffix="exposed structure, steel and glass, mechanical aesthetic, visible services, modern engineering",
        negative_prompt="traditional, masonry, rustic, wood, ornamental",
        tags=["tech", "steel", "engineering"],
    ),
    "postmodern": ArchitecturalStyle(
        id="postmodern",
        name="Postmodern",
        description="Bold colors, historical references mixed with modern elements, playful forms",
        facade_material="concrete",
        secondary_material="metal",
        roof_material="metal",
        color_overrides={"facade": [0.85, 0.75, 0.70, 1.0]},
        preferred_roof_types=["flat", "gabled"],
        window_density=0.5,
        window_width=1.2,
        window_height=1.6,
        balcony_probability=0.3,
        cornice_enabled=True,
        prompt_prefix="Postmodern architecture,",
        prompt_suffix="bold colors, eclectic mix of historical and modern elements, playful geometry, ironic ornamentation",
        negative_prompt="minimalist, austere, monochrome, plain",
        tags=["eclectic", "colorful", "playful"],
    ),
    "deconstructivist": ArchitecturalStyle(
        id="deconstructivist",
        name="Deconstructivist",
        description="Fragmented forms, non-rectilinear shapes, dynamic angular geometry",
        facade_material="metal",
        secondary_material="glass",
        roof_material="metal",
        preferred_roof_types=["flat"],
        window_density=0.4,
        window_width=1.3,
        window_height=1.6,
        balcony_probability=0.1,
        cornice_enabled=False,
        prompt_prefix="Deconstructivist architecture,",
        prompt_suffix="fragmented angular forms, non-linear geometry, dynamic shapes, titanium cladding, avant-garde",
        negative_prompt="symmetrical, traditional, orderly, classical",
        tags=["avant-garde", "angular", "sculptural"],
    ),
    "organic": ArchitecturalStyle(
        id="organic",
        name="Organic",
        description="Curved forms inspired by nature, flowing lines, living roofs",
        facade_material="concrete",
        secondary_material="glass",
        roof_material="green_roof",
        color_overrides={"facade": [0.82, 0.78, 0.72, 1.0]},
        preferred_roof_types=["flat"],
        window_density=0.55,
        window_width=1.4,
        window_height=1.6,
        balcony_probability=0.3,
        cornice_enabled=False,
        prompt_prefix="Organic architecture,",
        prompt_suffix="curved flowing forms, inspired by nature, green living roof, harmonious with landscape",
        negative_prompt="angular, rectilinear, industrial, harsh geometric",
        tags=["biomorphic", "curved", "green"],
    ),
    "minimalist": ArchitecturalStyle(
        id="minimalist",
        name="Minimalist",
        description="Pure geometric forms, monochrome palette, maximum simplicity",
        facade_material="concrete",
        secondary_material="glass",
        roof_material="concrete",
        color_overrides={"facade": [0.95, 0.95, 0.95, 1.0]},
        preferred_roof_types=["flat"],
        window_density=0.4,
        window_width=2.0,
        window_height=2.4,
        balcony_probability=0.1,
        cornice_enabled=False,
        prompt_prefix="Minimalist architecture,",
        prompt_suffix="pure white surfaces, simple geometric forms, monochrome, maximum simplicity, Tadao Ando style",
        negative_prompt="ornate, colorful, decorative, complex patterns",
        tags=["white", "simple", "pure"],
    ),
    "cottage": ArchitecturalStyle(
        id="cottage",
        name="Cottage",
        description="Cozy rustic charm, pitched roof, stone and wood, flower boxes",
        facade_material="brick",
        secondary_material="wood",
        roof_material="roof_tile",
        color_overrides={"brick": [0.68, 0.52, 0.40, 1.0]},
        preferred_roof_types=["gabled", "hipped"],
        window_density=0.45,
        window_width=0.8,
        window_height=1.2,
        balcony_probability=0.1,
        cornice_enabled=True,
        prompt_prefix="English cottage architecture,",
        prompt_suffix="cozy rustic charm, stone and timber, pitched thatched roof, flower window boxes, chimney",
        negative_prompt="modern, urban, glass, tall, industrial",
        tags=["rustic", "cozy", "residential"],
    ),
    "warehouse": ArchitecturalStyle(
        id="warehouse",
        name="Warehouse",
        description="Converted industrial, exposed brick, large steel-framed windows",
        facade_material="brick",
        secondary_material="metal",
        roof_material="metal",
        preferred_roof_types=["flat", "gabled"],
        window_density=0.55,
        window_width=2.0,
        window_height=2.5,
        balcony_probability=0.2,
        cornice_enabled=False,
        prompt_prefix="Warehouse conversion architecture,",
        prompt_suffix="exposed red brick, large steel-framed windows, industrial character, converted loft spaces",
        negative_prompt="suburban, ornate, classical columns, pitched tile roof",
        tags=["industrial", "loft", "urban"],
    ),
}


def get_style(style_id: str | None) -> ArchitecturalStyle:
    """Get an architectural style by ID, falling back to 'modern' if not found."""
    if not style_id:
        return ARCHITECTURAL_STYLES["modern"]
    return ARCHITECTURAL_STYLES.get(style_id, ARCHITECTURAL_STYLES["modern"])
