"""Add renderPrompt to all streets and parks archetypes (local only)."""
import json

# ── Load the render prompt data from the agent outputs ──
# Streets
streets_prompts = {
    "narrow_residential_street": {"mapOverlay": "Replace the colored street zone with a photorealistic narrow residential street. Smooth dark gray asphalt roadway 8-10 meters wide with no painted center line. Parallel-parked cars along both curbs as small colored rectangles. Pale gray concrete sidewalks on both sides separated from the road by a narrow grass planting strip. Mature deciduous street trees planted at regular 10-meter intervals in the planting strip with round canopies partially overhanging the road, creating dappled shadow patterns on the asphalt. Front yard lawns and driveways visible beyond the sidewalks. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a narrow dark gray asphalt strip with no center line markings. Rows of small colored car rectangles parked along both curb edges. Pale gray concrete sidewalk strips on each side with a narrow green grass buffer. Round deciduous tree canopies at regular intervals partially overhanging the road, casting circular shadow patterns. Green lawn strips visible beyond the sidewalks. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, lane markings, median, commercial signage"},
    "suburban_residential_street": {"mapOverlay": "Replace the colored street zone with a photorealistic wide suburban residential street. Asphalt roadway with a dashed yellow center line and rolled concrete curbs. Wide bright green lawn setbacks stretching from the curb to houses on both sides. Young deciduous trees with small canopies at irregular intervals in wide grass strips. Concrete sidewalks set well back from the curb. Wide driveways connecting to garage doors, no on-street parking. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a dark gray asphalt road strip with dashed yellow center line. Rolled concrete curb edges. Wide bright green lawn panels on both sides. Small young tree canopies scattered at irregular intervals. Pale concrete sidewalks set far back from the curb. Driveway cuts visible as lighter rectangles. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, mature tree canopy closing over road, commercial buildings"},
    "collector_road": {"mapOverlay": "Replace the colored street zone with a photorealistic collector road. Moderately wide asphalt roadway with one travel lane each direction and a center turn lane. Double yellow center lines and white dashed lane markings. Concrete sidewalks on both sides with narrow grass planting strips and mature street trees. Mixed residential and small commercial buildings along the edges. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a three-lane asphalt road pattern with double yellow center lines and white dashed markings. Concrete sidewalk strips with green grass buffer. Round tree canopies at regular intervals. White crosswalk stripes at intersections. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, highway-scale infrastructure"},
    "arterial_boulevard": {"mapOverlay": "Replace the colored street zone with a photorealistic divided arterial boulevard. Wide roadway with a central raised median planted with a double row of mature deciduous trees forming a continuous green canopy band. Two to three asphalt travel lanes in each direction with white dashed lane markings. Painted bike lanes along each curb edge. Wide concrete sidewalks with additional street trees. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a wide symmetric road corridor. A continuous green canopy band of mature tree crowns runs down the center median. Dark asphalt travel lanes on each side with white dashed markings. Pale concrete sidewalk bands with tree canopy dots on the outer edges. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, highway-scale infrastructure"},
    "highway_freeway": {"mapOverlay": "Replace the colored street zone with a photorealistic multi-lane highway. Broad asphalt corridor with four or more lanes in each direction. Concrete jersey barrier median. White dashed lane markings across all lanes. Wide paved shoulders. No trees, no sidewalks, no pedestrian infrastructure. Sound walls along outer edges. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a broad dark gray asphalt expanse. White dashed lane markings creating 8+ lane grid pattern. Thin pale concrete jersey barrier line down the center. Wide paved shoulders. No trees or green elements. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, trees, pedestrian crossings, bike lanes"},
    "roundabout": {"mapOverlay": "Replace the colored street zone with a photorealistic roundabout intersection. A circular road ring of dark gray asphalt surrounding a raised central landscaped island with mature trees and shrubs. White dashed lane markings. Triangular concrete splitter islands at each approach. Crosswalk zebra stripes. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a circular dark gray asphalt ring encircling a green landscaped center island with tree canopies. White dashed markings on the roadway. Triangular splitter islands at each approach. White crosswalk stripes. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, traffic signals in roundabout"},
    "cul_de_sac": {"mapOverlay": "Replace the colored street zone with a photorealistic cul-de-sac. A narrow residential street terminating in a circular bulb turnaround. Raised center island with a tree and shrubs. Smooth dark gray asphalt with rolled concrete curb. Driveways radiating outward. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a lollipop-shaped asphalt pattern: narrow stem street connecting to a circular turnaround bulb. A green center dot with tree canopy. Driveway cuts radiating outward. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, through traffic, commercial buildings"},
    "back_alley_service_lane": {"mapOverlay": "Replace the colored street zone with a photorealistic back alley service lane. A narrow paved strip of cracked asphalt running behind buildings. No sidewalks, no curbs. Utility poles with overhead wires. Dumpsters against building walls. Garage doors facing the alley. Chain-link fences. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a thin gray strip of cracked asphalt between building rear walls. No curbs. Utility pole tops. Dark rectangular dumpster shapes. Flat garage door panels along edges. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, trees, landscaping, clean new pavement"},
    "separated_bike_lane": {"mapOverlay": "Replace the colored street zone with a photorealistic separated two-way cycle track. Green-painted or red-brown colored asphalt surface 3-4 meters wide. White dashed center line and bicycle stencil markings. Physically separated by bollards or raised curb from traffic lanes. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a thin colored ribbon of green-painted or red-brown asphalt. White dashed center line. White bicycle stencil markings. Row of small bollard dots separating from the darker adjacent road. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, cars on bike lane"},
    "multi_use_trail": {"mapOverlay": "Replace the colored street zone with a photorealistic paved multi-use trail through a green corridor. Smooth pale gray asphalt or concrete path 3-4 meters wide with a yellow center line. Mature deciduous trees lining both sides creating dappled shade canopy. Open meadow or lawn beyond the tree line. Benches at intervals. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a smooth pale gray ribbon threading through green landscape. Yellow center line. Dense tree canopy overhanging from both sides. Open bright green lawn between canopy gaps. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, motorized vehicles"},
    "pedestrian_promenade": {"mapOverlay": "Replace the colored street zone with a photorealistic wide pedestrian promenade. Decorative stone or tile paving in warm tones with herringbone or banded pattern. Central row of mature plane trees. Cafe terraces with round table umbrellas. Ornamental lamp posts. No vehicle lanes. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a wide warm-toned patterned band of decorative paving. Central spine of large circular tree canopies. Colorful umbrella dot clusters along building edges. No vehicle lanes or asphalt. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, vehicle lanes, car traffic"},
    "woonerf_shared_street": {"mapOverlay": "Replace the colored street zone with a photorealistic Dutch-style woonerf shared street. Single flush surface with no raised curbs. Mixed paving materials: warm brick pavers, stone accents, permeable pavers around tree pits. Trees, planters, and bollards in a chicane pattern. Cars parked informally between planting beds. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a textured mosaic of warm-toned mixed paving. Tree canopies and green planter rectangles in a staggered chicane pattern. No curb lines, no lane markings. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, standard lane markings, raised curbs"},
    "brt_corridor": {"mapOverlay": "Replace the colored street zone with a photorealistic bus rapid transit corridor. Wide arterial roadway with center-running dedicated bus lanes painted red or terra-cotta. Raised median station platforms with glass-canopy shelters. General-purpose travel lanes flanking both sides. White lane markings. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a symmetric road pattern. Red or terra-cotta painted center bus lanes. Dark gray outer travel lanes. White lane markings. Pale platform rectangles with canopy shelters at stations. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, rail tracks"},
    "light_rail_avenue": {"mapOverlay": "Replace the colored street zone with a photorealistic light rail transit avenue. A center median containing embedded rail tracks as two parallel steel lines through a green grass strip. Station platforms with canopy shelters at stops. General-purpose traffic lanes on both sides. Overhead catenary poles. Trees lining outer sidewalks. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a green-striped center band containing two parallel glinting rail lines. Dark gray travel lanes flanking both sides. Long pale station platform rectangles. Small catenary pole dots. Tree canopy circles along outer edges. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, heavy freight rail"},
    "main_street_complete": {"mapOverlay": "Replace the colored street zone with a photorealistic traditional main street complete street. Two-lane asphalt roadway with on-street parking on both sides. Wide concrete sidewalks with street trees in metal grates. Commercial awnings extending from storefronts. Crosswalk stripes at intersections. Bicycle sharrow markings. Transit stop shelter. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a dark gray asphalt road strip framed by white parking stall markings. Parked car rectangles. Wide pale concrete sidewalk bands with tree canopy dots. Colorful awning stripe patterns along building edges. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, highway-scale width"},
    "campus_pedestrian_spine": {"mapOverlay": "Replace the colored street zone with a photorealistic campus pedestrian spine. A wide formal walkway of pale stone or concrete paving flanked by double rows of mature deciduous trees forming a continuous canopy alley. Benches at regular intervals. Cross-paths branching to adjacent buildings. Open lawn panels beyond the tree rows. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a pale band of paving framed by two parallel rows of dark green tree canopy. Green lawn panels beyond the tree rows. Small bench rectangles at intervals. Cross-path lines branching off. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, vehicle traffic"},
    "scenic_parkway": {"mapOverlay": "Replace the colored street zone with a photorealistic scenic parkway curving through parkland. Narrow two-lane dark asphalt with double yellow center lines curving gently through a wooded setting. Generous grass shoulders and wide tree setbacks. No buildings, no curbs, no sidewalks. Mature trees at naturalistic spacing with canopies overhanging the roadway. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a thin dark asphalt curve with double yellow center lines threading through lush green landscape. Wide grass shoulders. Irregular tree canopies overhanging the road edges. No buildings adjacent. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, commercial development, highway-scale width"},
    "riverfront_promenade": {"mapOverlay": "Replace the colored street zone with a photorealistic riverfront promenade. Wide paved walkway of pale gray stone running parallel to a river. Metal or stone railing along the water edge. Ornamental lamp posts at regular intervals. Trees along the inland edge. Benches facing the water. A parallel bikeway. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a pale linear stone band running alongside dark reflective water. Thin railing line along the water edge. Lamp post circles. Linear row of tree canopies along the inland edge. Bench rectangles. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, vehicle traffic on promenade"},
    "custom_streets_pathways": {"mapOverlay": "Replace the colored street zone with a photorealistic custom street or pathway. A well-designed urban corridor with clearly legible movement hierarchy. Distinct paving materials and edge conditions. Premium urban design quality with appropriate lane markings, sidewalks, and planting. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a clearly defined street or pathway corridor. Paving materials, lane markings, and edge conditions clearly visible. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors"},
    "downtown_thoroughfare": {"mapOverlay": "Replace the colored street zone with a photorealistic wide downtown thoroughfare. Six lanes of dark asphalt with white lane markings. Concrete sidewalks with street trees in metal grates. Commercial buildings with ground-floor retail and awnings. Transit bus at shelter stop. Parallel parked cars. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a wide six-lane dark gray asphalt road with white lane markings. Parked car rectangles along curbs. Pale concrete sidewalk strips with tree canopy dots. Building shadow patterns from flanking structures. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, residential houses"},
    "pedestrian_only_street": {"mapOverlay": "Replace the colored street zone with a photorealistic pedestrian-only shopping street. Full-width granite sett, limestone, or concrete paver surface with no vehicle lanes. Ground-floor retail and cafe frontages with outdoor seating. Street trees and seasonal plantings. A fountain or public art focal point. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a warm-toned stone paving surface filling the full width. Tree canopy circles. Cafe umbrella dot clusters along building edges. No vehicles, no lane markings. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, vehicles, road markings, asphalt"},
    "green_alley": {"mapOverlay": "Replace the colored street zone with a photorealistic green alley. Permeable concrete pavers or permeable asphalt. Bioswales and rain gardens with native sedges and wildflowers lining the edges. Mature trees overhanging from backyards. Wood privacy fences. Rain barrels and garage entrances. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a narrow strip of permeable pavers in lighter tone. Green bioswale strips along edges. Overhanging tree canopies from adjacent yards. Wood fence lines along property boundaries. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, standard asphalt, curbs"},
    "commercial_alley_laneway": {"mapOverlay": "Replace the colored street zone with a photorealistic narrow commercial laneway. Narrow passage between tall brick building walls. Bluestone flagstone or cobblestone paving. Ground-floor cafes and bars with tiny frontages. Overhead string lights. Street art and murals on walls. Potted plants. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a very narrow strip of stone paving between tall building walls. Overhead string light wires. Tiny cafe table dots along walls. Colorful mural patches. No vehicles. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, vehicles, wide road"},
    "yield_street": {"mapOverlay": "Replace the colored street zone with a photorealistic narrow yield street. Continuous clay brick pavers or cobblestone with no curbs. Bollards and planters defining the driving lane in a chicane pattern. Buildings fronting directly onto the street. Street trees creating canopy. Potted plants and bicycles along building edges. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a narrow continuous brick or stone paved surface with no curb lines or lane markings. Bollard dots and green planter rectangles in a staggered chicane. Tree canopies partially covering the street. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, lane markings, traffic signals, wide road"},
    "neighborhood_main_street": {"mapOverlay": "Replace the colored street zone with a photorealistic neighborhood main street. Two asphalt travel lanes with on-street parking. Wide sidewalks with street trees and flower baskets on lamp posts. 2-3 story mixed-use buildings with ground-floor retail, awnings, and blade signs. Active neighborhood commercial character. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a dark gray two-lane road with parking stall markings. Wide pale sidewalk bands with tree canopy dots and lamp post circles. Colorful awning stripes along building edges. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, highway-scale width, high-rise buildings"},
    "elevated_rail_transit": {"mapOverlay": "Replace the colored street zone with a photorealistic elevated rail transit corridor. A slender concrete or steel guideway structure rising above the street on sculptural piers. An architecturally dramatic station with a sweeping canopy. Activated public space beneath the viaduct with landscaping. Modern rail vehicles on the guideway. Surrounding mid-rise urban buildings. Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k", "roofView": "Replace the colored zone viewed from directly above with a slender elevated guideway ribbon. Two parallel rail lines on the deck. Sculptural pier bases at regular intervals. Station canopy as a dramatic footprint. Green landscaping beneath the viaduct. Keep surrounding context exactly as-is.", "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, ugly brutalist concrete, oppressive shadows"},
}

# Parks - abbreviated for file size, using key descriptions
parks_prompts = {}
park_data_raw = {
    "urban_pocket_park": ("compact urban pocket park. Two to four mature deciduous shade trees with broad rounded canopies casting dappled shadows across a small central lawn panel. A curving decomposed-granite path loops through the space. Wooden benches beneath tree canopies. Low ornamental hedge borders the perimeter.", "two to four overlapping dark-green circular tree canopies against a bright emerald lawn rectangle. Thin tan curving path. Low dark hedge line at perimeter."),
    "neighborhood_park": ("mid-sized neighborhood park. Large open bright-green mowed lawn field with mowing stripes. Clusters of mature deciduous trees along edges. Continuous dark-gray asphalt walking loop around perimeter. Compact playground cluster with colorful equipment on tan rubber-mulch surface. Benches along path.", "large bright-green striped mowed lawn center. Dark-green tree canopy clusters along borders. Dark-gray asphalt loop path. Small colorful playground patch in one corner."),
    "community_park": ("large community park with multiple activity zones. Wide open sports lawn with faint white line markings. Dense picnic grove of mature trees. Curving network of paved trails. Naturalized stormwater pond with emergent rushes. Small pavilion structure.", "mosaic of green textures: dark canopy groves, medium-green lawns, light meadow at edges. Gray trail ribbons. Dark water pond with green rushes. Small pale-roofed pavilion."),
    "regional_park": ("large-scale regional park with rolling natural terrain. Patchwork of dark forested areas, bright open meadows, and mid-green recreation fields. Thin unpaved trails through forest. Large lake with dark reflective water. Rolling terrain with shadow gradients.", "patchwork of dark forest canopy blocks, bright meadow panels, and mid-green lawn areas. Thin tan trail lines through woodland. Large dark reflective lake surface."),
    "dog_park": ("fenced dog park. Perimeter chain-link fence with internal fence dividing into two zones. Mix of compacted earth and worn grass. Tan decomposed-granite path inside the fence. Shade canopy structures. Scattered trees. Double-gate entry vestibules.", "fenced enclosure divided into two sections. Mixed worn grass and bare earth. Tan path along inside perimeter. Rectangular shade structure shadows. Double-gate rectangles at entries."),
    "skate_park": ("concrete skate park. Smooth gray poured concrete surfaces with sculptural bowl depressions. Quarter-pipes and half-pipes. Rails and ledges as thin dark lines. Spectator benches along one edge. Surrounding grass framing the concrete pad.", "smooth gray concrete pad. Curved bowl shadow gradients. Ramp edges as curved lines. Rails as thin dark lines. Bench row along one edge. Grass buffer at perimeter."),
    "sports_field_complex": ("multi-field sports complex. Bright green rectangular soccer fields with crisp white line markings. Baseball diamond with brown infield dirt. Red-brown synthetic running track oval. Aluminum bleacher rows. Pole-mounted field lights.", "bright green rectangular fields with white line markings. Brown dirt baseball diamond fan. Red-brown track oval with white lane stripes. Thin metallic bleacher strips."),
    "tennis_court_cluster": ("cluster of four to six tennis courts. Vivid blue or green acrylic rectangles with precise white boundary lines. Chain-link fencing. Nets as thin white horizontal lines. Narrow walkways between courts. Maintained grass buffer at perimeter.", "grid of vivid blue or green rectangular court surfaces with white line markings. Darker surround bands. Faint chain-link grid. Thin white net lines at mid-court."),
    "botanical_garden": ("curated botanical garden. Rich tapestry of diverse planting beds in geometric and organic shapes with distinct colors and textures. Winding pale gravel paths. Glass conservatory with translucent roof. Specimen trees of varying species. Formal rose garden section.", "tapestry of distinct planting beds in varied colors. Pale gravel path lines winding between beds. Translucent glass conservatory rectangle. Varied tree canopy shapes. Concentric circular rose garden beds."),
    "japanese_garden": ("contemplative Japanese garden. Central koi pond with dark still water edged by carefully placed boulders. Red-painted arched bridge. Raked gravel areas with concentric wave patterns. Japanese maple trees with deep red canopy alongside cloud-pruned pines. Stepping-stone paths through emerald moss. Stone lantern. Dense bamboo groves.", "dark koi pond water surface with boulder-edged shoreline. Red arched bridge. Pale beige raked gravel panels with wave patterns. Deep red-orange maple canopies and dark green rounded pine canopies. Gray stepping-stone dot chains."),
    "memorial_garden": ("solemn memorial garden with formal axial layout. Central axis with long narrow reflecting pool flanked by polished stone paving. Rows of identical dark conical evergreen trees in formal symmetry. Commemorative wall or monument at axis terminus. Low clipped hedges. Stone benches.", "bilaterally symmetrical layout. Long narrow dark reflecting pool along central axis. Rows of identical dark conical evergreen shapes on both sides. Dark monument rectangle at terminus."),
    "urban_forest": ("dense urban woodland. Nearly continuous canopy of overlapping crowns forming a dense dark-green mat. Narrow dirt footpath as thin brown line. Variation in canopy tone. No lawn, no formal paths, no structures.", "dense continuous tree canopy mat of overlapping dark-green crowns. Tiny canopy gaps revealing forest floor. Barely visible thin brown footpath line."),
    "riparian_buffer": ("naturalistic riparian corridor. Sinuous creek winding through center with dark water surface. Dense vegetation with willow canopies, native shrub thickets, and tall riparian grasses. Narrow crushed-gravel trail parallel to creek. Erosion-control boulders.", "sinuous dark water channel. Weeping willow canopies draping over water edge. Dense shrub thickets along banks. Thin tan trail line parallel to creek."),
    "wetland_rain_garden": ("constructed wetland rain garden. Shallow standing water pools reflecting sky as dark mirrors interspersed with dense emergent vegetation — cattails, bulrushes, sedges. Wooden boardwalk elevated above water surface. Gravel edge transition with native meadow buffer.", "organic mosaic of dark reflective water pools and bright yellow-green marsh vegetation tufts. Thin tan boardwalk line weaving through. Gravel edge at perimeter. Native meadow buffer ring."),
    "playground_adventure": ("children's playground. Tan or rust-colored rubber safety surfacing. Colorful playground equipment in red, blue, yellow, green. Shade canopy structure. Low perimeter fence. Surrounding grass buffer. Parent benches facing equipment.", "tan or rust rubber safety surface. Colorful confetti-like dots of playground equipment. Triangular shade canopy shadow. Thin dark perimeter fence line. Green grass buffer."),
    "splash_pad_area": ("interactive splash pad water play area. Colored concrete or rubber surface in blues and grays. Ground-level spray nozzles with bright white water spray. Wet reflective surface. Low curved seat wall. Parent seating area with shade canopy.", "circular colored concrete pad in blues and grays. Bright white spray jet streaks. Darker wet reflective surface. Low curved seat wall border. Adjacent shade canopy rectangle."),
    "amphitheater_lawn": ("sloped grass amphitheater. Gently sloped bright-green grass bowl descending toward a flat performance area. Stage platform in smooth pale concrete. Curved tier lines in grass. Paved path along top rim. Shade trees along upper perimeter.", "green semicircular bowl depression. Concentric curved tier lines. Pale concrete stage rectangle at focal point. Paved path arc along top rim. Tree canopy circles along perimeter."),
    "community_garden": ("community garden with allotment plots. Grid of individual raised-bed plots in various states of cultivation. Narrow gravel or woodchip paths in grid pattern. Small tool shed. Compost bin rectangles. Colorful patchwork of greens and browns.", "geometric grid of small rectangular raised beds. Varied fill colors: greens, bare brown soil. Narrow tan path grid between plots. Small shed rectangle. Dark brown compost rectangles."),
    "cemetery_memorial_grounds": ("maintained cemetery grounds. Orderly rows of small gray headstone markers across bright green manicured lawn. Mature trees with broad canopies. Narrow pale gray service lanes. Occasional larger monuments. Wrought-iron or stone perimeter fence.", "precise grid of small gray headstone dots on bright green lawn. Broad circular tree canopy shadows. Narrow pale gray lane lines. Perimeter fence line."),
    "formal_civic_plaza": ("formal civic plaza. Large rectangular hardscape of cut stone pavers in warm gray and beige in geometric pattern centered on a prominent circular fountain. Rows of formally spaced deciduous trees in planters. Stone benches and bollards. Flagpoles.", "geometric stone paver pattern in warm gray and beige. Concentric rings from central dark circular fountain basin. Formal rows of round tree canopy circles along edges."),
    "market_square": ("flexible market square. Large flat open hardscape of uniform warm-toned unit pavers. Rows of white market tent canopies. Mature trees in flush tree grates along edges. Cafe seating clusters. Small stage at one end.", "uniform warm-toned paver surface. White tent canopy rectangles in grid. Tree canopy circles in flush grates along edges. Small umbrella clusters near building frontages."),
    "courtyard_plaza": ("intimate enclosed courtyard. Compact rectangular hardscape of warm-toned stone or brick in herringbone pattern enclosed by building walls. Central fountain, sculpture, or ornamental tree. Raised planters with lush green shrubs. Small cafe tables. String lights.", "compact warm-toned herringbone paving. Building wall shadows from three or four sides. Central feature at focal point. Green planter rectangles along edges. Small cafe table clusters."),
    "promenade_boardwalk": ("waterfront promenade or boardwalk. Wide linear strip of warm brown timber decking with visible plank lines parallel to water. Railing along water edge. Benches facing the water. Ornamental lamp posts. Row of trees along inland edge. Dark blue-gray water surface adjacent.", "wide warm brown linear timber deck strip. Thin dark railing line along water edge. Small bench rectangles. Lamp post circles. Tree canopy circles along inland edge. Dark water surface adjacent."),
    "transit_plaza": ("transit-oriented plaza. Glass and steel transit shelters as translucent rectangles. Wide concrete waiting area. Bike rack clusters. Yellow or white painted curb lines. Contrasting tactile paving strip. Trees in raised planters.", "concrete or paver hardscape. Elongated translucent shelter rectangles. Bike rack clusters. Yellow or white curb lines. Contrasting tactile strip. Tree canopy circles in raised planters."),
    "amphitheater_performance_space": ("built outdoor amphitheater. Semicircular tiered stone or concrete seating radiating from a flat stage platform. Tiers as concentric curved lines with shadow on risers. Curved acoustic shell behind stage. Aisle stairs as radial lines. Trees at perimeter.", "semicircular concentric stone tier arcs focused on central pale stage rectangle. Shadow stripes on risers. Curved dark acoustic shell arc behind stage. Radial aisle stair lines."),
    "surface_parking_lot": ("surface parking lot. Dark gray asphalt covering entire area. White or yellow painted lines delineating parking stalls in grid. Drive aisles between rows. Parked cars as colored rectangles. Concrete curb at perimeter. Trees in small planter islands. Pole-mounted lights.", "dark gray asphalt surface. White or yellow painted stall line grid. Small colored car rectangles. Drive aisle gaps. Concrete curb line at perimeter. Small green tree canopy circles."),
    "structured_parking_garage": ("multi-level parking garage. Top deck with flat concrete surface and painted stall lines and parked cars. Helical or straight ramp at one corner. Concrete parapet walls. Stairwell towers at corners.", "flat concrete top deck with painted stall lines and parked car rectangles. Ramp opening at one corner. Concrete parapet edges. Stairwell boxes at corners."),
    "underground_parking_entry": ("landscaped surface above underground parking garage. Green lawn, trees, or paved plaza on top. A dark rectangular vehicle ramp entry opening with concrete retaining walls. Ventilation grate rectangles flush with surface. Small pedestrian kiosk.", "green landscaped surface or paved plaza. Dark rectangular ramp opening. Dark metal ventilation grates flush with surface. Small pedestrian kiosk structure."),
    "green_parking_lot": ("eco-friendly green parking lot. Permeable grass pavers creating a checker pattern of green grass cells within a concrete or plastic grid. Tree islands at row ends. Bioswale channels between rows. Rain garden basins. Native planting buffer at perimeter.", "distinctive green-and-gray checker grid pattern. Dark tree canopy circles at row ends. Narrow green bioswale depressions between rows. Rain garden patches. Native planting buffer at perimeter."),
    "pond_lake": ("naturalistic pond or small lake. Dark reflective water surface in deep blue-black tones. Soft irregular shoreline with gentle grass slopes. Lily pad and reed patches along shallow margins. Mature trees overhanging shoreline. Small wooden fishing pier. Walking path tracing shoreline.", "dark reflective water surface. Soft irregular shoreline with green grass. Bright green lily pad and reed patches. Tree canopy circles overhanging water edge. Thin brown pier rectangle."),
    "fountain_water_feature": ("decorative fountain in plaza setting. Circular polished stone basin with dark reflective water. Multiple vertical water jets creating bright white spray columns. Wet reflective paving around fountain. Concentric rings of stone paving. Bench seating in circle.", "concentric rings of warm-toned stone paving from central dark circular fountain basin. Bright white spray column dots. Wet reflective paving halo. Bench dots in circle."),
    "stormwater_retention_pond": ("engineered stormwater retention pond. Shallow depression with gently sloped mowed grass banks. Partial dark reflective water patch at bottom. Inlet pipe or channel. Concrete outlet structure. Native meadow grasses ringing waterline. Gravel maintenance track.", "broad shallow oval depression. Green mowed grass slopes. Dark reflective water patch at bottom. Inlet channel line. Small gray outlet structure. Golden-green native grass band. Thin gravel track."),
    "swimming_pool_complex": ("outdoor swimming pool complex. Large rectangular lap pool with vivid turquoise-blue water and white lane lines. Adjacent smaller wading pool. Wide warm-gray concrete sun deck with lounge chairs. Continuous dark fence enclosure. Small pool house. Diving boards. Green grass and trees outside fence.", "vivid turquoise-blue rectangular lap pool with white lane lines. Smaller lighter blue wading pool. Wide warm-gray concrete deck. Rows of lounge chair rectangles. Dark fence enclosure line. Green grass outside fence."),
    "canal_waterway": ("linear canal or urban waterway. Straight or gently curving dark blue-gray water channel with reflective surface. Stone or concrete quay walls. Pale paved towpath along one or both banks. Moored narrowboats as elongated colored shapes. Deciduous trees lining far bank. Narrow pedestrian bridges. Cafe terraces near water edge.", "dark blue-gray water ribbon. Stone quay wall lines. Pale towpath strips. Elongated colored boat shapes. Tree canopy circles along one bank. Narrow bridge bands crossing water."),
    "custom_parks_plazas": ("custom open space. Well-designed public landscape with a mix of paved areas and planted zones. Paths with mature shade trees. Seating areas and gathering spaces. Premium material realism.", "mixed-use open space landscape. Paved path networks and planted zones. Tree canopy circles. Seating nodes. Well-maintained planting."),
    "linear_park_greenway": ("linear park greenway along a corridor. Paved multi-use trail following a narrow corridor. Native wildflower meadows and riparian plantings flanking the trail. Shade trees along the corridor. Small bridges or overlook platforms. Creek or stormwater features alongside.", "narrow linear corridor. Gray or tan trail line running the length. Native wildflower meadow strips flanking. Tree canopy circles along corridor. Small bridge structures."),
    "nature_preserve": ("protected nature preserve. Undisturbed natural ecosystem with minimal built intervention. Narrow timber boardwalk or crushed-stone trail threading through. Observation platform at scenic point. Native vegetation dominating.", "undisturbed natural ecosystem surface. Thin boardwalk or trail line threading through. Small observation platform rectangle. Native vegetation textures dominant."),
    "rooftop_garden": ("rooftop garden atop a multi-story building. Intensive planted beds with small trees, shrubs, and ornamental grasses. Ipe deck or porcelain tile paving with seating areas. Pergola or shade structure. Glass railings at building edge. Reflecting pool or water feature.", "rooftop surface divided into planted bed zones and paved deck areas. Seating furniture clusters. Pergola structure rectangle. Glass railing at building edge. Small water feature."),
    "riverfront_park_beach": ("waterfront park with beach. Sand beach area along the shoreline in warm golden tones. Stepped concrete terraces or timber deck promenade. Parasols and deck chairs on sand. Plane trees along upland edge. Promenade walkway. Water surface in dark tones.", "golden sand beach strip along water edge. Dark water surface. Stepped terrace or deck strip above beach. Small parasol and chair dots. Tree canopy circles along upland edge."),
    "street_plaza_parklet": ("small street plaza or parklet reclaimed from roadway. Painted asphalt, timber deck, or granite pavers. Bistro tables and chairs. Planters with small trees. Bollards or painted barriers separating from active roadway. Colorful furniture and plantings.", "small reclaimed street space. Painted or paved surface distinct from surrounding roadway. Small table and chair clusters. Planter rectangles with tree canopies. Bollard dots or painted barrier lines."),
}

for park_id, (overlay_desc, roof_desc) in park_data_raw.items():
    parks_prompts[park_id] = {
        "mapOverlay": f"Replace the colored park zone with a photorealistic {overlay_desc} Keep surrounding satellite map context exactly as-is. Oblique aerial view, sunny day, sharp shadows, photorealistic, 8k",
        "roofView": f"Replace the colored zone viewed from directly above with {roof_desc} Keep surrounding context exactly as-is.",
        "negative": "cartoon, illustration, sketch, low quality, blurry, text, watermark, unrealistic colors, buildings inside the park"
    }


# ── Apply to JSON files ──

# Streets
streets_path = "frontend/src/data/streetPathArchetypes.json"
streets_data = json.loads(open(streets_path, encoding="utf-8").read())
s_updated = 0
for arch in streets_data["archetypes"]:
    if arch["id"] in streets_prompts:
        arch["renderPrompt"] = streets_prompts[arch["id"]]
        s_updated += 1

with open(streets_path, "w", encoding="utf-8") as f:
    json.dump(streets_data, f, indent=2, ensure_ascii=False)
print(f"Streets: updated {s_updated}/{len(streets_prompts)} archetypes with renderPrompt")

# Parks
parks_path = "frontend/src/data/openSpaceArchetypes.json"
parks_data = json.loads(open(parks_path, encoding="utf-8").read())
p_updated = 0
for arch in parks_data["archetypes"]:
    if arch["id"] in parks_prompts:
        arch["renderPrompt"] = parks_prompts[arch["id"]]
        p_updated += 1

with open(parks_path, "w", encoding="utf-8") as f:
    json.dump(parks_data, f, indent=2, ensure_ascii=False)
print(f"Parks: updated {p_updated}/{len(parks_prompts)} archetypes with renderPrompt")
print(f"\nTotal: {s_updated + p_updated} archetypes now have renderPrompt (local only)")
