"""Compile a real archetype export (export_catalog.ts output) into a Building Grammar.

Every derivation decision is recorded in ``grammar.notes`` so aesthetic review can
trace a generated building back to the catalogue prose that produced it.
"""
from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from typing import Any

try:  # package-style import (tests) and script-style import (blender/CLI) both work
    from .schema import (
        AttachmentSpec,
        BaySpec,
        BuildingGrammar,
        Dimensions,
        Facade,
        FacadeGraph,
        FacadeZone,
        FloorVariant,
        GrammarError,
        GrammarSource,
        Massing,
        Material,
        Materials,
        OpeningSpec,
        Roof,
    )
except ImportError:  # pragma: no cover - script mode
    from schema import (
        AttachmentSpec,
        BaySpec,
        BuildingGrammar,
        Dimensions,
        Facade,
        FacadeGraph,
        FacadeZone,
        FloorVariant,
        GrammarError,
        GrammarSource,
        Massing,
        Material,
        Materials,
        OpeningSpec,
        Roof,
    )


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "archetype"


def _num(value: Any, default: float | None = None) -> float | None:
    if isinstance(value, (int, float)) and math.isfinite(value) and value > 0:
        return float(value)
    return default


def _strings(value: Any) -> list[str]:
    return [str(item) for item in value] if isinstance(value, list) else []


def _clamp(value: float, lo: float | None, hi: float | None) -> float:
    if lo is not None:
        value = max(value, lo)
    if hi is not None:
        value = min(value, hi)
    return value


# ---------------------------------------------------------------------------
# Material derivation: catalogue prose -> deterministic PBR values.
# Ordered list — the FIRST matching keyword wins, so put specific phrases first.
# The third element is the canonical texture_key: aliases share one texture set
# in tools/archetype_compiler/textures/ (generated by generate_textures.py);
# blender_generate.py falls back to the flat colour when the set is absent.
# ---------------------------------------------------------------------------
_MATERIAL_KEYWORDS: list[tuple[str, tuple[str, float, float], str]] = [
    ("membrane", ("#4a4d4f", 0.85, 0.0), "roof_membrane"),
    ("terracotta barrel roof", ("#b45f35", 0.72, 0.0), "mediterranean_roof_tile"),
    ("terracotta roof tile", ("#b45f35", 0.72, 0.0), "mediterranean_roof_tile"),
    ("clay roof tile", ("#b45f35", 0.72, 0.0), "mediterranean_roof_tile"),
    ("barrel roof tile", ("#b45f35", 0.72, 0.0), "mediterranean_roof_tile"),
    ("shou sugi ban", ("#2e2a26", 0.62, 0.0), "charred_timber"),
    ("charred timber", ("#2e2a26", 0.62, 0.0), "charred_timber"),
    ("charred black", ("#26221f", 0.62, 0.0), "charred_timber"),
    ("black metal", ("#26282c", 0.4, 0.75), "black_metal"),
    ("dark metal", ("#33363b", 0.4, 0.7), "black_metal"),
    ("charcoal-black metal", ("#2c2e32", 0.4, 0.75), "black_metal"),
    ("corrugated steel", ("#7d8286", 0.5, 0.8), "corrugated_steel"),
    ("corten", ("#8a4a2e", 0.7, 0.35), "corten_steel"),
    ("weathering steel", ("#8a4a2e", 0.7, 0.35), "corten_steel"),
    ("bronze anodized", ("#83563f", 0.42, 0.72), "copper"),
    ("bronze-anodized", ("#83563f", 0.42, 0.72), "copper"),
    ("wrought-iron", ("#24282c", 0.46, 0.78), "black_metal"),
    ("wrought iron", ("#24282c", 0.46, 0.78), "black_metal"),
    ("dark iron", ("#24282c", 0.46, 0.78), "black_metal"),
    ("zinc", ("#8d939a", 0.45, 0.8), "zinc"),
    ("copper", ("#9a5b3c", 0.4, 0.85), "copper"),
    ("standing seam", ("#4c5257", 0.45, 0.75), "standing_seam"),
    ("welsh slate", ("#3e4651", 0.78, 0.0), "welsh_slate"),
    ("natural slate", ("#3e4651", 0.78, 0.0), "welsh_slate"),
    ("slate", ("#3e4651", 0.78, 0.0), "welsh_slate"),
    ("metal panel", ("#5a5e63", 0.45, 0.7), "metal_panel"),
    ("aluminium", ("#9aa0a6", 0.4, 0.8), "metal_panel"),
    ("aluminum", ("#9aa0a6", 0.4, 0.8), "metal_panel"),
    ("scandinavian larch", ("#b98248", 0.62, 0.0), "scandinavian_larch"),
    ("exposed larch", ("#b98248", 0.62, 0.0), "scandinavian_larch"),
    ("glulam", ("#c9a878", 0.6, 0.0), "glulam"),
    ("cross-laminated", ("#cbb089", 0.6, 0.0), "clt"),
    ("clt", ("#cbb089", 0.6, 0.0), "clt"),
    ("birch", ("#dcc9a3", 0.6, 0.0), "birch_wood"),
    ("pine", ("#d3b98a", 0.6, 0.0), "pine_wood"),
    ("larch", ("#b08a5a", 0.65, 0.0), "larch_wood"),
    ("cedar", ("#a87848", 0.65, 0.0), "cedar_wood"),
    ("oak", ("#a8845c", 0.65, 0.0), "oak_wood"),
    ("natural timber", ("#b08a5a", 0.65, 0.0), "natural_timber"),
    ("warm natural wood", ("#a97f52", 0.65, 0.0), "natural_timber"),
    ("timber", ("#a97f52", 0.65, 0.0), "natural_timber"),
    ("wood", ("#a97f52", 0.65, 0.0), "natural_timber"),
    ("victorian red brick", ("#7c3d30", 0.86, 0.0), "victorian_brick"),
    ("pressed clay brick", ("#7c3d30", 0.86, 0.0), "victorian_brick"),
    ("pressed brick", ("#7c3d30", 0.86, 0.0), "victorian_brick"),
    ("red brick", ("#8a4a3a", 0.85, 0.0), "red_brick"),
    ("redbrick", ("#8a4a3a", 0.85, 0.0), "red_brick"),
    ("buff brick", ("#c8a878", 0.85, 0.0), "buff_brick"),
    ("blonde brick", ("#cfb289", 0.85, 0.0), "buff_brick"),
    ("brick", ("#96503e", 0.85, 0.0), "red_brick"),
    ("white mineral render", ("#eeeae3", 0.82, 0.0), "white_plaster"),
    ("white plaster", ("#e8e6e0", 0.8, 0.0), "white_plaster"),
    ("white render", ("#e8e6e0", 0.8, 0.0), "white_plaster"),
    ("render", ("#ddd9d0", 0.8, 0.0), "stucco"),
    ("plaster", ("#e0dcd3", 0.8, 0.0), "stucco"),
    ("stucco", ("#ddd5c6", 0.8, 0.0), "stucco"),
    ("lutetian limestone", ("#d8d0c0", 0.76, 0.0), "heritage_portland_stone"),
    ("cream limestone", ("#d8d0c0", 0.76, 0.0), "heritage_portland_stone"),
    ("portland stone", ("#d8d0c0", 0.76, 0.0), "heritage_portland_stone"),
    ("brownstone", ("#875a43", 0.8, 0.0), "brownstone"),
    ("limestone", ("#d5cbb8", 0.75, 0.0), "limestone"),
    ("sandstone", ("#c9b090", 0.78, 0.0), "sandstone"),
    ("granite", ("#8c8c8c", 0.6, 0.0), "granite"),
    ("natural stone", ("#9a938a", 0.72, 0.0), "natural_stone"),
    ("stone", ("#9a938a", 0.72, 0.0), "natural_stone"),
    ("precast", ("#bcb8af", 0.8, 0.0), "precast_concrete"),
    ("concrete", ("#b5b1a8", 0.82, 0.0), "concrete"),
    ("curtain wall", ("#6e8ea4", 0.1, 0.1), "curtain_wall"),
    ("glass", ("#6e8ea4", 0.1, 0.1), "curtain_wall"),
    ("fiber cement", ("#a8a49c", 0.75, 0.0), "fiber_cement"),
    ("glazed architectural terracotta", ("#d5c7a5", 0.43, 0.0), "art_deco_terracotta"),
    ("glazed terracotta", ("#d5c7a5", 0.43, 0.0), "art_deco_terracotta"),
    ("terracotta", ("#b06a48", 0.75, 0.0), "terracotta"),
]

# Texture sets for material slots that never go through the keyword match:
# the concrete plinth/slab default, the flat-roof default, and the green roof.
_DEFAULT_TEXTURE_ANCHORS: dict[str, tuple[str, float]] = {
    "concrete": ("#b5b1a8", 0.82),
    "roof_membrane": ("#4a4d4f", 0.85),
    "sedum_roof": ("#5f7a48", 0.9),
    # Signature-only roof material used by historic Chateauesque families.
    # It is not a generic prose keyword because ordinary catalogue mentions
    # of copper should continue to resolve to warm unfinished copper.
    "verdigris_copper": ("#6f9a8b", 0.56),
}


def texture_anchor_table() -> dict[str, tuple[str, float]]:
    """texture_key -> (base colour, roughness) for every canonical texture.

    The first keyword row naming a texture_key anchors it (rows are ordered
    specific-first, so that row is the texture's defining material).
    """
    anchors = dict(_DEFAULT_TEXTURE_ANCHORS)
    for _, (color, rough, _metal), texture_key in _MATERIAL_KEYWORDS:
        anchors.setdefault(texture_key, (color, rough))
    return anchors

_DEFAULT_MATERIAL_COLORS = {
    "primary": ("#c9c2b4", 0.7, 0.0),
    "secondary": ("#8a8176", 0.7, 0.0),
    "accent": ("#2b2e33", 0.45, 0.6),
}


def _derive_material(slot: str, text: str | None, mat_name: str, notes: list[str]) -> Material:
    fallback_color, fallback_rough, fallback_metal = _DEFAULT_MATERIAL_COLORS.get(slot, ("#c9c2b4", 0.7, 0.0))
    if not text:
        notes.append(f"materials.{slot}: no facadeDetail text; using neutral default {fallback_color}")
        return Material(name=mat_name, base_color=fallback_color, roughness=fallback_rough, metallic=fallback_metal)

    lowered = text.lower()
    for keyword, (color, rough, metal), texture_key in _MATERIAL_KEYWORDS:
        if keyword in lowered:
            notes.append(f"materials.{slot}: '{keyword}' in \"{text[:60]}...\" -> {color} (texture {texture_key})")
            return Material(
                name=mat_name, base_color=color, roughness=rough, metallic=metal,
                source_text=text, texture_key=texture_key,
            )
    notes.append(f"materials.{slot}: no keyword matched \"{text[:60]}...\"; using neutral default {fallback_color}")
    return Material(name=mat_name, base_color=fallback_color, roughness=fallback_rough, metallic=fallback_metal, source_text=text)


def _derive_glass(palette: dict[str, Any], notes: list[str]) -> Material:
    window = palette.get("window") if isinstance(palette, dict) else None
    if isinstance(window, str) and re.match(r"^#[0-9a-fA-F]{6}$", window):
        notes.append(f"materials.glass: from catalogue palette.window {window}")
        return Material(name="MAT_Glass", base_color=window, roughness=0.08, metallic=0.0, source_text="palette.window")
    notes.append("materials.glass: default cool blue-grey")
    return Material(name="MAT_Glass", base_color="#5f7f95", roughness=0.08, metallic=0.0)


# ---------------------------------------------------------------------------
# Roof / balcony / retail inference from catalogue prose + tags
# ---------------------------------------------------------------------------

def _derive_roof(roof_detail: dict[str, Any], style_profile: dict[str, Any], notes: list[str]) -> Roof:
    primary_form_text = str(roof_detail.get("form") or "").lower()
    form_text = " ".join(
        str(v) for v in [roof_detail.get("form"), roof_detail.get("aerialAppearance"), style_profile.get("roofForm")]
        if isinstance(v, str)
    ).lower()
    material_text = str(roof_detail.get("material") or "").lower()
    features_text = str(roof_detail.get("features") or "").lower()

    # The selected variant's explicit form is authoritative over a parent
    # profile that merely lists mansard as one possible family alternative.
    if "mansard" in primary_form_text:
        # A mansard may legitimately describe its upper termination as a
        # "flat top"; that phrase must not collapse the silhouette to flat.
        roof_type = "mansard"
    elif "flat" in primary_form_text:
        # The selected variant's explicit roof description is authoritative.
        # Parent style profiles often list several family-level alternatives
        # (for example "flat or shallow-pitched"); those must not turn an
        # explicitly flat green-roof addition into a generic gable.
        roof_type = "flat"
    # Hipped roofs still use the closest supported pitched silhouette.
    elif "mansard" in form_text:
        roof_type = "mansard"
    elif re.search(r"\bgable|pitched|asymmetric pitch|hipped", form_text) and "flat" not in form_text.split(" or ")[0]:
        roof_type = "gabled"
    elif "mono-pitch" in form_text or "monopitch" in form_text or "shed roof" in form_text:
        # "flat or shallow mono-pitch" reads as flat-first; only pick mono when flat is absent
        roof_type = "mono_pitch" if "flat" not in form_text else "flat"
    elif re.search(r"\bgable|pitched|hipped", form_text):
        roof_type = "gabled"
    else:
        roof_type = "flat"

    green = any(k in material_text or k in features_text or k in form_text for k in ("green roof", "sedum", "meadow", "roof garden"))
    mech = "mechanical" in features_text or "mechanical" in form_text
    parapet = roof_type == "flat"
    notes.append(
        f"roof: type={roof_type} green_roof={green} mechanical_screen={mech} "
        f"from roofDetail.form=\"{str(roof_detail.get('form'))[:60]}\""
    )
    return Roof(
        type=roof_type,
        parapet=parapet,
        green_roof=green,
        mechanical_screen=mech or roof_type == "flat",
        pitch_height_m=6.2 if roof_type == "mansard" else 2.4,
    )


def _derive_balconies(combined: str, development_type: str, facade_text: str, notes: list[str]) -> tuple[str, int]:
    residential = "residential" in development_type or "residential" in combined or "apartment" in combined
    mentions_balcony = "balcon" in combined or "balcon" in facade_text
    if not (residential or mentions_balcony):
        notes.append("balconies: none (no residential use or balcony mention)")
        return "none", 2
    if "recessed" in facade_text or "recessed" in combined:
        mode = "recessed"
    else:
        # 'deep balconies', 'cantilevered', or unspecified residential -> projecting
        mode = "projecting"
    frequency = 1 if ("deep" in facade_text and "balcon" in facade_text) else 2
    notes.append(f"balconies: mode={mode} every {frequency} bay(s) (residential={residential})")
    return mode, frequency


def _derive_retail(development_type: str, combined: str, ground_text: str, notes: list[str]) -> bool:
    retail = (
        "mixed_use" in development_type
        or "mixed-use" in combined
        or "mixed use" in combined
        or any(k in ground_text for k in ("retail", "storefront", "shopfront", "cru", "restaurant", "commercial"))
        or any(k in combined for k in ("ground_floor_retail", "storefront"))
    )
    notes.append(f"podium retail: {retail} (developmentType={development_type or 'n/a'}, groundFloor=\"{ground_text[:50]}\")")
    return retail


def _derive_facade_system(
    combined: str,
    primary_text: str,
    secondary_text: str,
    ground_text: str,
    notes: list[str],
) -> dict[str, Any]:
    """Translate catalogue prose into a buildable facade kit.

    This is deliberately semantic rather than tied to four variant ids, so the
    same rules can be reused by future archetypes with equivalent materials.
    """
    text = " ".join((combined, primary_text, secondary_text, ground_text)).lower()
    heritage_tokens = (
        "mansard", "rusticated", "ashlar", "sash window", "sash_windows",
        "dentil", "modillion", "classical window", "heritage mansion",
    )
    if any(token in text for token in heritage_tokens) and any(
        token in text for token in ("portland stone", "limestone", "stucco", "stone", "classical", "heritage")
    ):
        result = {
            "system": "heritage_stone", "entrance_type": "arched", "balcony_guard": "metal",
            "window_recess_m": 0.38, "panel_projection_m": 0.32,
            "material_bay_frequency": 2, "feature_bay_frequency": 4, "planter_frequency": 0,
            "window_width_ratio": 0.46, "window_height_ratio": 0.66,
        }
    elif ("cross-laminated" in text or "mass timber" in text) and any(
        token in text for token in ("curtain wall", "floor-to-ceiling", "glazing")
    ):
        result = {
            "system": "timber_grid", "entrance_type": "portal", "balcony_guard": "planter",
            "window_recess_m": 0.12, "panel_projection_m": 0.16,
            # One or two staggered planted bays per floor matches the reference
            # much more closely than a checkerboard balcony on every other bay.
            "material_bay_frequency": 1, "feature_bay_frequency": 4, "planter_frequency": 4,
            "window_width_ratio": 0.76, "window_height_ratio": 0.76,
        }
    elif any(token in text for token in ("white mineral render", "smooth white", "white render")):
        result = {
            "system": "punched_render", "entrance_type": "recessed", "balcony_guard": "metal",
            "window_recess_m": 0.28, "panel_projection_m": 0.05,
            "material_bay_frequency": 3, "feature_bay_frequency": 3, "planter_frequency": 0,
            "window_width_ratio": 0.48, "window_height_ratio": 0.68,
        }
    elif "brick" in text:
        result = {
            "system": "brick_bays", "entrance_type": "arched", "balcony_guard": "solid",
            "window_recess_m": 0.24, "panel_projection_m": 0.22,
            "material_bay_frequency": 2, "feature_bay_frequency": 3, "planter_frequency": 0,
            "window_width_ratio": 0.46, "window_height_ratio": 0.64,
        }
    elif any(token in text for token in ("limestone", "precast", "terracotta", "corten")):
        result = {
            "system": "stone_frame", "entrance_type": "colonnade", "balcony_guard": "metal",
            "window_recess_m": 0.26, "panel_projection_m": 0.18,
            "material_bay_frequency": 2, "feature_bay_frequency": 2, "planter_frequency": 0,
            "window_width_ratio": 0.5, "window_height_ratio": 0.66,
        }
    else:
        result = {
            "system": "regular", "entrance_type": "canopy", "balcony_guard": "metal",
            "window_recess_m": 0.18, "panel_projection_m": 0.08,
            "material_bay_frequency": 3, "feature_bay_frequency": 3, "planter_frequency": 0,
            "window_width_ratio": 0.55, "window_height_ratio": 0.52,
        }
    notes.append(
        "facade system: "
        f"{result['system']} / entrance={result['entrance_type']} / guard={result['balcony_guard']}"
    )
    return result


def _build_facade_graph(facade: Facade, floors: int) -> FacadeGraph:
    """Compile the v2 facade controls into a renderer-neutral v3 graph."""
    standard = OpeningSpec(
        id="standard_window",
        kind="curtain_wall" if facade.system == "timber_grid" else "window",
        width_ratio=facade.window_width_ratio,
        height_ratio=facade.window_height_ratio,
        sill_m=facade.sill_height_m,
        reveal_depth_m=facade.window_recess_m,
        frame_profile_id="slim" if facade.system in ("timber_grid", "punched_render") else "deep",
        mullion_pattern="double" if facade.system in ("timber_grid", "heritage_stone") else "single",
    )
    balcony_door = OpeningSpec(
        id="balcony_door",
        kind="juliet_door" if facade.system == "punched_render" else "door",
        width_ratio=min(0.8, max(facade.window_width_ratio, 0.58)),
        height_ratio=max(0.72, facade.window_height_ratio),
        sill_m=0.18,
        reveal_depth_m=facade.window_recess_m,
        frame_profile_id="slim",
        mullion_pattern="double",
    )
    shopfront = OpeningSpec(
        id="shopfront",
        kind="shopfront",
        width_ratio=0.84,
        height_ratio=facade.storefront_height_ratio,
        sill_m=0.18,
        reveal_depth_m=max(0.08, facade.window_recess_m * 0.6),
        frame_profile_id="storefront",
        mullion_pattern="double",
    )

    attachment_by_system = {
        "timber_grid": [
            AttachmentSpec("balcony", "balcony", "timber_planter_balcony", ["primary", "glass", "accent"], "bay"),
            AttachmentSpec("entrance", "portal", "timber_portal", ["primary", "glass"], "base"),
            AttachmentSpec("crown_feature", "planter", "green_roof_crown", ["primary", "green_roof"], "crown"),
        ],
        "punched_render": [
            AttachmentSpec("balcony", "balcony", "slender_metal_balcony", ["concrete", "accent"], "bay"),
            AttachmentSpec("juliet", "juliet", "slender_juliet", ["accent"], "bay"),
            AttachmentSpec("entrance", "portal", "recessed_lobby", ["primary", "accent", "glass"], "base"),
            AttachmentSpec("crown_feature", "planter", "terrace_crown", ["primary", "green_roof"], "crown"),
        ],
        "brick_bays": [
            AttachmentSpec("oriel", "oriel", "brick_oriel", ["primary", "secondary", "glass"], "bay", 1, min(40, max(2, floors - 2))),
            AttachmentSpec("entrance", "arch", "masonry_arch", ["primary", "secondary"], "base"),
            AttachmentSpec("crown_feature", "cornice", "brick_cornice", ["primary", "secondary"], "crown"),
        ],
        "stone_frame": [
            AttachmentSpec("balcony", "balcony", "timber_perforated_balcony", ["accent", "secondary"], "bay"),
            AttachmentSpec("entrance", "colonnade", "tripartite_colonnade", ["primary", "concrete"], "base"),
            AttachmentSpec("crown_feature", "screen", "corten_wrap", ["secondary"], "crown"),
        ],
        "heritage_stone": [
            AttachmentSpec("entrance", "arch", "grand_stone_portal", ["primary", "secondary", "accent"], "base"),
            AttachmentSpec("crown_feature", "cornice", "dentilled_stone_cornice", ["primary", "secondary"], "crown"),
        ],
        "regular": [
            AttachmentSpec("balcony", "balcony", "standard_balcony", ["concrete", "accent"], "bay"),
            AttachmentSpec("entrance", "canopy", "standard_canopy", ["accent"], "base"),
            AttachmentSpec("crown_feature", "cornice", "standard_cornice", ["primary"], "crown"),
        ],
    }
    attachments = attachment_by_system[facade.system]

    feature_attachment = "oriel" if facade.system == "brick_bays" else "balcony"
    bays = [
        BaySpec("standard", "standard_window", "primary"),
        BaySpec(
            "feature",
            "standard_window" if facade.system == "heritage_stone" else "balcony_door",
            "primary",
            facade.panel_projection_m,
            [] if facade.system == "heritage_stone" else [feature_attachment],
        ),
        BaySpec("material", "standard_window", "secondary", facade.panel_projection_m * 0.35),
        BaySpec("upper", "standard_window", "secondary" if facade.system in ("stone_frame", "timber_grid") else "primary"),
        BaySpec("crown", "standard_window", "secondary" if facade.system == "stone_frame" else "primary", 0.0, ["crown_feature"]),
    ]

    def sequence(offset: int, *, include_features: bool = True) -> list[str]:
        result: list[str] = []
        feature_every = max(1, facade.feature_bay_frequency)
        material_every = max(1, facade.material_bay_frequency)
        for index in range(facade.front_bay_count):
            if include_features and (index - offset) % feature_every == 0:
                result.append("feature")
            elif facade.system in ("punched_render", "stone_frame") and index % material_every == material_every - 1:
                result.append("material")
            else:
                result.append("standard")
        return result

    typical_a = sequence(0)
    typical_b = sequence(1 if facade.system != "brick_bays" else 0)
    upper = ["upper"] * facade.front_bay_count
    crown = ["crown"] * facade.front_bay_count
    middle_end = max(1, floors - 3)
    upper_level = max(1, floors - 2)
    crown_level = max(1, floors - 1)
    side_sequence = ["standard"] * max(1, facade.side_bay_count)
    return FacadeGraph(
        openings=[standard, balcony_door, shopfront],
        attachments=attachments,
        bays=bays,
        floor_variants=[
            FloorVariant("typical_a", typical_a, "middle", repeat_every=2),
            FloorVariant("typical_b", typical_b, "middle", repeat_every=2),
            FloorVariant("upper", upper, "upper", allowed_levels=[upper_level]),
            FloorVariant("crown", crown, "crown", allowed_levels=[crown_level]),
        ],
        zones=[
            FacadeZone("base", 0, 0, "primary", ["typical_a"]),
            FacadeZone("middle", 1, middle_end, "primary", ["typical_a", "typical_b"]),
            FacadeZone("upper", upper_level, upper_level, "primary", ["upper"], inset_m=0.8),
            FacadeZone(
                "crown", crown_level, crown_level,
                "secondary" if facade.system in ("stone_frame", "heritage_stone") else "primary",
                ["crown"], inset_m=0.4,
            ),
        ],
        sides={
            "front": typical_a,
            "rear": ["standard"] * facade.front_bay_count,
            "left": side_sequence,
            "right": side_sequence,
        },
    )


def compile_archetype(
    payload: dict[str, Any],
    *,
    floors: int | None = None,
    width_m: float | None = None,
    depth_m: float | None = None,
    allow_outside_bounds: bool = False,
) -> BuildingGrammar:
    """Derive a BuildingGrammar from an export_catalog.ts payload.

    Also accepts the older ``generation_style_input``-style dicts for backward
    compatibility with zone properties captured at runtime.
    """
    notes: list[str] = []

    style_input = payload.get("generationStyleInput") or payload.get("generation_style_input") or {}
    hints = style_input.get("downstreamHints") or {}
    style_profile = payload.get("styleProfile") or style_input.get("styleProfile") or {}
    dims = payload.get("dimensions") or payload  # runtime dicts carry dims at top level

    variant = payload.get("selectedVariant") or None
    variant_facade = (variant or {}).get("facadeDetail") or {}
    variant_roof = (variant or {}).get("roofDetail") or {}
    facade_detail = {**(payload.get("facadeDetail") or {}), **variant_facade}
    roof_detail = {**(payload.get("roofDetail") or {}), **variant_roof}
    palette = (variant or {}).get("palette") or payload.get("palette") or {}

    archetype_id = str(
        payload.get("archetypeId")
        or style_input.get("archetypeId")
        or payload.get("development_archetype_id")
        or ""
    )
    if not archetype_id:
        raise GrammarError("payload has no archetypeId — export it with export_catalog.ts first")

    archetype_label = str(payload.get("archetypeLabel") or style_input.get("archetypeLabel") or archetype_id)
    corner_condition = "corner" if "corner" in f"{archetype_id} {archetype_label}".lower() else "midblock"
    if corner_condition == "corner":
        notes.append("corner condition: corner archetype receives a wrapped hero elevation")

    reuse_keys = list(dict.fromkeys(
        _strings(hints.get("reuseKeys"))
        + [archetype_id, str(payload.get("aestheticCategoryId") or "")]
    ))
    reuse_keys = [key for key in reuse_keys if key]

    # --- dimensions ---------------------------------------------------------
    min_w, max_w = _num(dims.get("minWidth_m")), _num(dims.get("maxWidth_m"))
    min_d, max_d = _num(dims.get("minDepth_m")), _num(dims.get("maxDepth_m"))
    width = _num(width_m) or _num(dims.get("suggestedWidth_m")) or 24.0
    depth = _num(depth_m) or _num(dims.get("suggestedDepth_m")) or 18.0
    clamped_width = width if allow_outside_bounds and width_m is not None else _clamp(width, min_w, max_w)
    clamped_depth = depth if allow_outside_bounds and depth_m is not None else _clamp(depth, min_d, max_d)
    if clamped_width != width:
        notes.append(f"width {width}m clamped to {clamped_width}m (catalogue bounds {min_w}-{max_w}m)")
    if clamped_depth != depth:
        notes.append(f"depth {depth}m clamped to {clamped_depth}m (catalogue bounds {min_d}-{max_d}m)")
    width_outside = width_m is not None and (
        (min_w is not None and width < min_w) or (max_w is not None and width > max_w)
    )
    depth_outside = depth_m is not None and (
        (min_d is not None and depth < min_d) or (max_d is not None and depth > max_d)
    )
    if allow_outside_bounds and (width_outside or depth_outside):
        notes.append(
            f"dimension tier {width}x{depth}m intentionally exceeds catalogue recommendations "
            f"({min_w}-{max_w}m x {min_d}-{max_d}m)"
        )
    width, depth = clamped_width, clamped_depth

    variant_min_floors = _num((variant or {}).get("minFloors"))
    variant_max_floors = _num((variant or {}).get("maxFloors"))
    min_floors = int(variant_min_floors or _num(dims.get("minFloors")) or 1)
    max_floors = int(variant_max_floors or _num(dims.get("maxFloors")) or max(min_floors, 8))
    default_floors = int(floors) if floors else int(round((min_floors + max_floors) / 2))
    if not (min_floors <= default_floors <= max_floors):
        clamped = max(min_floors, min(max_floors, default_floors))
        notes.append(f"floors {default_floors} clamped to {clamped} (catalogue range {min_floors}-{max_floors})")
        default_floors = clamped

    floor_height = (
        _num((variant or {}).get("suggestedFloorHeight"))
        or _num(dims.get("suggestedFloorHeight"))
        or 3.2
    )

    # --- semantic inference --------------------------------------------------
    development_type = str(payload.get("developmentType") or style_input.get("developmentType") or "").lower()
    tags = " ".join(_strings(payload.get("generationTags") or style_input.get("generationTags"))).lower()
    profile_text = " ".join(str(v) for v in style_profile.values() if isinstance(v, str)).lower()
    variant_desc = str((variant or {}).get("description") or "").lower()
    combined = f"{archetype_id.lower()} {development_type} {tags} {profile_text} {variant_desc}"

    ground_text = str(facade_detail.get("groundFloor") or "").lower()
    upper_text = str(facade_detail.get("upperFloors") or "").lower()

    retail = _derive_retail(development_type, combined, ground_text, notes)
    podium_height = 4.5 if retail else max(3.8, round(floor_height * 1.25, 2))
    podium_height = _clamp(podium_height, 3.6, 5.2)

    balcony_mode, balcony_frequency = _derive_balconies(combined, development_type, upper_text, notes)

    roof = _derive_roof(roof_detail, style_profile, notes)

    # Setbacks are a massing decision, so infer them only from explicit
    # massing language. Looking through the entire archetype prose made roof
    # phrases such as "stepped gabled dormers" create an unrelated two-metre
    # upper-floor terrace on otherwise continuous historic streetwalls.
    massing_text = str(style_profile.get("massing") or "").lower()
    explicit_variant_massing = f"{variant_desc} {upper_text}"
    setback_phrases = (
        "upper-floor setback", "upper floor setback", "setback", "set back",
        "stepped massing", "stepped terrace", "stepped terraces", "steps down",
        "terraced upper", "recessed penthouse",
    )
    explicit_variant_setback = any(phrase in explicit_variant_massing for phrase in setback_phrases)
    explicit_parent_setback = any(phrase in massing_text for phrase in setback_phrases)
    # A selected image variant is more specific than the parent archetype's
    # broad style profile. Do not invent a two-storey setback simply because a
    # generic midrise description says some taller variants may have one.
    has_setback = explicit_variant_setback if variant else explicit_parent_setback
    rooftop_addition_phrases = (
        "rooftop addition", "penthouse addition", "rooftop penthouse", "set back from the facade",
    )
    rooftop_pavilion = any(
        phrase in explicit_variant_massing for phrase in rooftop_addition_phrases
    )
    # A rooftop pavilion is represented by the fixed crown at the catalogue's
    # canonical height. Only insert a second modular setback storey when the
    # user makes the building taller than that canonical target. This keeps a
    # four-storey adaptive-reuse block as three preserved brick levels plus one
    # recessed glass pavilion, matching the approved City Prompt render.
    setback_min_floors = max(5, default_floors + 1) if rooftop_pavilion else 5
    notes.append(
        f"setback: {has_setback} "
        f"(default_floors={default_floors}, explicit massing language={explicit_variant_setback if variant else explicit_parent_setback})"
    )

    # bays: Nordic/tall-window styles read better slightly narrower
    bay = 3.0
    if "townhouse" in combined or "rowhouse" in combined or "row house" in combined:
        bay = 5.4  # one unit-ish per bay
    elif "tower" in combined or "curtain wall" in profile_text:
        bay = 2.4
    front_bays = max(1, round(width / bay))
    side_bays = max(1, round(depth / bay))

    window_height_ratio = 0.62 if any(k in combined for k in ("tall window", "floor-to-ceiling", "nordic", "scandinavian")) else 0.52
    facade_system = _derive_facade_system(
        combined,
        str(facade_detail.get("primaryMaterial") or ""),
        str(facade_detail.get("secondaryMaterial") or ""),
        ground_text,
        notes,
    )

    facade = Facade(
        bay_width_m=bay,
        front_bay_count=front_bays,
        side_bay_count=side_bays,
        window_width_ratio=facade_system["window_width_ratio"],
        window_height_ratio=max(window_height_ratio, facade_system["window_height_ratio"]),
        balcony_mode=balcony_mode,
        balcony_frequency=balcony_frequency,
        storefront_height_ratio=0.78 if retail else 0.6,
        system=facade_system["system"],
        window_recess_m=facade_system["window_recess_m"],
        panel_projection_m=facade_system["panel_projection_m"],
        material_bay_frequency=facade_system["material_bay_frequency"],
        feature_bay_frequency=facade_system["feature_bay_frequency"],
        planter_frequency=facade_system["planter_frequency"],
        balcony_guard=facade_system["balcony_guard"],
        entrance_type=facade_system["entrance_type"],
    )

    primary_material = _derive_material(
        "primary", facade_detail.get("primaryMaterial"), "MAT_Facade_Primary", notes,
    )
    secondary_material = _derive_material(
        "secondary", facade_detail.get("secondaryMaterial"), "MAT_Facade_Secondary", notes,
    )
    secondary_text = str(facade_detail.get("secondaryMaterial") or "").lower()
    # Classical carving is normally cut from the same stone as the wall. A
    # generic "carved stone" description should therefore inherit the named
    # limestone/sandstone finish instead of becoming a contrasting rubble map.
    if (
        facade.system == "heritage_stone"
        and secondary_material.texture_key == "natural_stone"
        and primary_material.texture_key in {"heritage_portland_stone", "limestone", "sandstone"}
        and "stone" in secondary_text
    ):
        secondary_material = Material(
            name="MAT_Facade_Secondary",
            base_color=primary_material.base_color,
            roughness=primary_material.roughness,
            metallic=primary_material.metallic,
            source_text=str(facade_detail.get("secondaryMaterial") or ""),
            texture_key=primary_material.texture_key,
        )
        notes.append("materials.secondary: inherited the primary heritage stone finish for carved ornament")

    grammar = BuildingGrammar(
        family_id=_slug((variant or {}).get("id") or archetype_id),
        source=GrammarSource(
            archetype_id=archetype_id,
            archetype_label=archetype_label,
            variant_id=(variant or {}).get("id"),
            variant_label=(variant or {}).get("label"),
            generation_archetype_id=style_input.get("archetypeId"),
            aesthetic_category_id=payload.get("aestheticCategoryId") or style_input.get("aestheticCategoryId"),
            aesthetic_category_label=payload.get("aestheticCategoryLabel") or style_input.get("aestheticCategoryLabel"),
            development_type=development_type or None,
            building_subcategory=payload.get("buildingSubcategory") or style_input.get("buildingSubcategory"),
            reuse_keys=reuse_keys,
            generation_tags=_strings(payload.get("generationTags") or style_input.get("generationTags")),
            catalog_palette={k: v for k, v in palette.items() if isinstance(v, str)},
            thumbnail_url=payload.get("thumbnailUrl"),
            exported_at=payload.get("exportedAt"),
        ),
        dimensions=Dimensions(
            width_m=round(width, 2),
            depth_m=round(depth, 2),
            podium_height_m=round(podium_height, 2),
            floor_height_m=round(floor_height, 2),
            setback_height_m=round(floor_height, 2),
            roof_height_m=1.2 if roof.type == "flat" else roof.pitch_height_m,
            default_floors=default_floors,
            min_floors=min_floors,
            max_floors=max_floors,
        ),
        facade=facade,
        facade_graph=_build_facade_graph(facade, default_floors),
        massing=Massing(
            has_setback=has_setback,
            setback_min_floors=setback_min_floors,
            rooftop_pavilion=rooftop_pavilion,
            has_podium_retail=retail,
            # Adaptive-reuse rooftop pavilions need a legible terrace on all
            # exposed sides.  The generic setback was visually too slight at
            # City Prompt scale, making the addition read as another flush
            # brick storey instead of the recessed glass volume in the
            # approved render.
            setback_front_m=min(3.2 if rooftop_pavilion else 2.0, depth / 6),
            setback_side_m=min(2.4 if rooftop_pavilion else 1.2, width / 10),
            corner_condition=corner_condition,
        ),
        roof=roof,
        materials=Materials(
            primary=primary_material,
            secondary=secondary_material,
            accent=_derive_material("accent", facade_detail.get("accentMaterial"), "MAT_Accent", notes),
            glass=_derive_glass(palette, notes),
            roof=_derive_material("roof", roof_detail.get("material"), "MAT_Roof", notes)
            if not roof.green_roof
            else Material(name="MAT_Roof", base_color="#4a4d4f", roughness=0.85, metallic=0.0, texture_key="roof_membrane"),
        ),
        notes=notes,
    )
    grammar.validate()
    return grammar


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile an archetype export into a Building Grammar")
    parser.add_argument("input", type=Path, help="archetype-source.json from export_catalog.ts")
    parser.add_argument("output", type=Path, help="compiled grammar JSON path")
    parser.add_argument("--floors", type=int, default=None, help="override default floor count")
    parser.add_argument("--width", type=float, default=None, help="override width in metres")
    parser.add_argument("--depth", type=float, default=None, help="override depth in metres")
    args = parser.parse_args()

    payload = json.loads(args.input.read_text(encoding="utf-8"))
    grammar = compile_archetype(payload, floors=args.floors, width_m=args.width, depth_m=args.depth)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(grammar.to_dict(), indent=2), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
