"""Reusable physical-glazing profiles for generated LEGO buildings.

The profiles describe construction intent rather than renderer-specific shader
objects.  Blender consumes the optical values when exporting glTF; the profile
name is also exported as material metadata so City Prompt can preserve the
same classification when it switches between near and city-scale glazing LODs.
"""
from __future__ import annotations

from copy import deepcopy


GLASS_PROFILES: dict[str, dict[str, float | str]] = {
    "low_iron_clear": {
        "label": "Low-iron clear lobby glass",
        "tint": "#f1eee4",
        "roughness": 0.055,
        "transmission": 0.96,
        "ior": 1.52,
        "clearcoat": 0.32,
        "clearcoat_roughness": 0.045,
        "specular_ior_level": 0.50,
        "interior_depth_m": 0.72,
        "frame_depth_m": 0.12,
        "pane_recess_m": 0.065,
        "environment_intensity": 1.30,
        "interior_light_color": "#ffe1b5",
        "interior_light_strength": 0.58,
        "glass_emission_strength": 0.015,
        "baked_glass_emission": 0.05,
        "baked_glass_mix": 0.64,
    },
    "office_clear_occupied": {
        "label": "Ultra-clear occupied office glazing",
        "tint": "#f3f0e8",
        "roughness": 0.045,
        "transmission": 0.97,
        "ior": 1.52,
        "clearcoat": 0.38,
        "clearcoat_roughness": 0.038,
        "specular_ior_level": 0.52,
        "interior_depth_m": 0.88,
        "frame_depth_m": 0.24,
        "pane_recess_m": 0.14,
        "environment_intensity": 1.38,
        "interior_light_color": "#ffe0b0",
        "interior_light_strength": 0.68,
        "glass_emission_strength": 0.012,
        "baked_glass_emission": 0.075,
        "baked_glass_mix": 0.52,
    },
    "museum_atrium_low_iron": {
        "label": "Low-iron museum atrium glazing with deep public interior",
        "tint": "#555d5e",
        "roughness": 0.038,
        "transmission": 0.62,
        "ior": 1.52,
        "clearcoat": 0.76,
        "clearcoat_roughness": 0.030,
        "specular_ior_level": 0.62,
        "interior_depth_m": 1.40,
        "frame_depth_m": 0.24,
        "pane_recess_m": 0.18,
        "environment_intensity": 1.52,
        "interior_light_color": "#e8c79d",
        "interior_light_strength": 0.30,
        "glass_emission_strength": 0.004,
        "baked_glass_emission": 0.022,
        "baked_glass_mix": 0.34,
        "pane_variation_mode": "atrium",
    },
    "terracotta_office_low_e": {
        "label": "Neutral low-e office glazing behind terracotta solar fins",
        "tint": "#a2aaa8",
        "roughness": 0.058,
        "transmission": 0.62,
        "ior": 1.51,
        "clearcoat": 0.66,
        "clearcoat_roughness": 0.038,
        "specular_ior_level": 0.60,
        "interior_depth_m": 0.92,
        "frame_depth_m": 0.18,
        "pane_recess_m": 0.12,
        "environment_intensity": 1.44,
        "interior_light_color": "#f0d2aa",
        "interior_light_strength": 0.31,
        "glass_emission_strength": 0.004,
        "baked_glass_emission": 0.028,
        "baked_glass_mix": 0.60,
        "pane_variation_mode": "office",
    },
    "civic_recessed_smoked": {
        "label": "Recessed smoked civic glazing with occupied lobby depth",
        "tint": "#303434",
        "roughness": 0.082,
        "transmission": 0.19,
        "ior": 1.50,
        "clearcoat": 0.55,
        "clearcoat_roughness": 0.058,
        "specular_ior_level": 0.56,
        "interior_depth_m": 1.15,
        "frame_depth_m": 0.28,
        "pane_recess_m": 0.34,
        "environment_intensity": 1.25,
        "interior_light_color": "#e2c098",
        "interior_light_strength": 0.24,
        "glass_emission_strength": 0.003,
        "baked_glass_emission": 0.018,
        "baked_glass_mix": 0.68,
        "pane_variation_mode": "ribbon",
    },
    "reflective_curtain_wall": {
        "label": "Neutral reflective curtain wall",
        "tint": "#d9e0dc",
        "roughness": 0.085,
        "transmission": 0.82,
        "ior": 1.50,
        "clearcoat": 0.42,
        "clearcoat_roughness": 0.075,
        "specular_ior_level": 0.58,
        "interior_depth_m": 0.82,
        "frame_depth_m": 0.15,
        "pane_recess_m": 0.09,
        "environment_intensity": 1.45,
        "interior_light_color": "#ffd9a6",
        "interior_light_strength": 0.55,
        "glass_emission_strength": 0.012,
        "baked_glass_emission": 0.02,
        "baked_glass_mix": 0.82,
    },
    "industrial_sash": {
        "label": "Industrial steel-sash glass",
        "tint": "#e7e1d6",
        "roughness": 0.10,
        "transmission": 0.86,
        "ior": 1.47,
        "clearcoat": 0.18,
        "clearcoat_roughness": 0.16,
        "specular_ior_level": 0.44,
        "interior_depth_m": 0.58,
        "frame_depth_m": 0.21,
        "pane_recess_m": 0.16,
        "environment_intensity": 1.18,
        "interior_light_color": "#ffd39a",
        "interior_light_strength": 0.78,
        "glass_emission_strength": 0.020,
        "baked_glass_emission": 0.09,
        "baked_glass_mix": 0.78,
    },
    "residential_low_e": {
        "label": "Residential low-e glazing",
        "tint": "#e9e4da",
        "roughness": 0.105,
        "transmission": 0.80,
        "ior": 1.49,
        "clearcoat": 0.28,
        "clearcoat_roughness": 0.11,
        "specular_ior_level": 0.48,
        "interior_depth_m": 0.62,
        "frame_depth_m": 0.13,
        "pane_recess_m": 0.085,
        "environment_intensity": 1.20,
        "interior_light_color": "#ffe0b8",
        "interior_light_strength": 0.52,
        "glass_emission_strength": 0.016,
        "baked_glass_emission": 0.09,
        "baked_glass_mix": 0.88,
    },
    "bronze_recessed_occupied": {
        "label": "Bronze-framed recessed occupied low-e glazing",
        "tint": "#29383e",
        "roughness": 0.064,
        "transmission": 0.16,
        "ior": 1.50,
        "clearcoat": 0.68,
        "clearcoat_roughness": 0.035,
        "specular_ior_level": 0.62,
        "interior_depth_m": 0.16,
        "frame_depth_m": 0.09,
        "pane_recess_m": 0.065,
        "environment_intensity": 1.35,
        "interior_light_color": "#ffd6a1",
        "interior_light_strength": 0.36,
        "glass_emission_strength": 0.006,
        "baked_glass_emission": 0.035,
        "baked_glass_mix": 0.76,
    },
    "heritage_sash_occupied": {
        "label": "Painted heritage sash with warm occupied rooms",
        "tint": "#454a49",
        "roughness": 0.095,
        "transmission": 0.18,
        "ior": 1.49,
        "clearcoat": 0.46,
        "clearcoat_roughness": 0.080,
        "specular_ior_level": 0.54,
        "interior_depth_m": 0.16,
        "frame_depth_m": 0.095,
        "pane_recess_m": 0.070,
        "environment_intensity": 1.15,
        "interior_light_color": "#f1c58f",
        "interior_light_strength": 0.30,
        "glass_emission_strength": 0.004,
        "baked_glass_emission": 0.040,
        "baked_glass_mix": 0.70,
        "pane_variation_mode": "window",
    },
    "industrial_crittall_occupied": {
        "label": "Steel Crittall workshop glazing with occupied depth",
        "tint": "#303b3e",
        "roughness": 0.085,
        "transmission": 0.18,
        "ior": 1.48,
        "clearcoat": 0.42,
        "clearcoat_roughness": 0.070,
        "specular_ior_level": 0.52,
        "interior_depth_m": 0.16,
        "frame_depth_m": 0.085,
        "pane_recess_m": 0.070,
        "environment_intensity": 1.24,
        "interior_light_color": "#efbf82",
        "interior_light_strength": 0.34,
        "glass_emission_strength": 0.004,
        "baked_glass_emission": 0.045,
        "baked_glass_mix": 0.72,
        "pane_variation_mode": "window",
    },
    "nordic_clear_occupied": {
        "label": "Neutral Nordic residential glazing with linen shade depth",
        "tint": "#2e3b40",
        "roughness": 0.060,
        "transmission": 0.17,
        "ior": 1.50,
        "clearcoat": 0.62,
        "clearcoat_roughness": 0.042,
        "specular_ior_level": 0.58,
        "interior_depth_m": 0.16,
        "frame_depth_m": 0.080,
        "pane_recess_m": 0.065,
        "environment_intensity": 1.30,
        "interior_light_color": "#f3d2a7",
        "interior_light_strength": 0.28,
        "glass_emission_strength": 0.004,
        "baked_glass_emission": 0.035,
        "baked_glass_mix": 0.76,
        "pane_variation_mode": "window",
    },
    "heritage_leaded_occupied": {
        "label": "Warm occupied heritage leaded glass",
        "tint": "#756c5b",
        "roughness": 0.13,
        "transmission": 0.62,
        "ior": 1.49,
        "clearcoat": 0.24,
        "clearcoat_roughness": 0.12,
        "specular_ior_level": 0.46,
        "interior_depth_m": 0.78,
        "frame_depth_m": 0.18,
        "pane_recess_m": 0.18,
        "environment_intensity": 1.12,
        "interior_light_color": "#ffc77d",
        "interior_light_strength": 0.66,
        "glass_emission_strength": 0.010,
        "baked_glass_emission": 0.075,
        "baked_glass_mix": 0.46,
    },
}

DEFAULT_GLASS_PROFILE = "low_iron_clear"


def glass_profile(name: str | None) -> dict[str, float | str]:
    """Return a defensive copy of a known profile, raising on misspellings."""
    key = name or DEFAULT_GLASS_PROFILE
    try:
        profile = deepcopy(GLASS_PROFILES[key])
    except KeyError as exc:
        raise ValueError(f"unknown glass profile {key!r}; choose one of {sorted(GLASS_PROFILES)}") from exc
    profile["id"] = key
    return profile


def glass_profile_for_grammar(grammar: dict) -> str:
    signature = grammar.get("architectural_signature") or {}
    return str(signature.get("glass_profile") or DEFAULT_GLASS_PROFILE)
