"""Catalogue contracts for ten commonplace Wave 16 building families.

This is the third user-facing catalogue expansion wave.  The compiler wave
number follows the repository's existing sequence.  Each family binds to an
already-selectable CityPrompt variant and supplies a fixed landmark plus a
six-part LEGO fallback without changing the catalogue JSON.
"""
from __future__ import annotations


def _spec(
    *,
    archetype_id: str,
    variant_id: str,
    label: str,
    shape: str,
    native: tuple[float, float, float],
    floors: int,
    min_floors: int,
    max_floors: int,
    floor_height: float,
    podium_height: float,
    crown_height: float,
    roof_height: float,
    catalogue_slug: str,
    catalogue_variant_index: int,
    source_path: str,
    building_crop: tuple[float, float, float, float],
    occupied_crop: tuple[float, float, float, float],
    identity: str,
    materials: str,
    glass_profile: str,
    aliases: list[str],
    reuse_keys: list[str],
    design_lock: str,
    palette: dict[str, tuple[str, tuple[int, int, int], str]],
    material_crops: dict[str, tuple[float, float, float, float]],
    development_type: str,
    aesthetic: str,
) -> dict:
    return {
        "archetype_id": archetype_id,
        "variant_id": variant_id,
        "label": label,
        "shape": shape,
        "cohort": "commonplace_standard",
        "native": native,
        "native_floors": floors,
        "min_floors": min_floors,
        "max_floors": max_floors,
        "floor_height": floor_height,
        "podium_height": podium_height,
        "crown_height": crown_height,
        "roof_height": roof_height,
        "catalogue_slug": catalogue_slug,
        "catalogue_variant_index": catalogue_variant_index,
        "source_path": source_path,
        "building_crop": building_crop,
        "occupied_crop": occupied_crop,
        "identity": identity,
        "material_zones": materials,
        "glass_profile": glass_profile,
        "aliases": aliases,
        "reuse_keys": reuse_keys,
        "design_lock": design_lock,
        "palette": palette,
        "material_crops": material_crops,
        "development_type": development_type,
        "aesthetic": aesthetic,
    }


FAMILIES: dict[str, dict] = {
    "craftsman-brick-bungalow": _spec(
        archetype_id="calgary_inner_city_bungalow",
        variant_id="bungalow_craftsman_original",
        label="Craftsman Brick Bungalow",
        shape="craftsman_bungalow",
        native=(10.0, 12.0, 6.4),
        floors=1,
        min_floors=1,
        max_floors=2,
        floor_height=3.15,
        podium_height=3.15,
        crown_height=0.25,
        roof_height=3.0,
        catalogue_slug="calgary-inner-city-bungalow",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/calgary-inner-city-bungalow/variant_0.png",
        building_crop=(0.12, 0.18, 0.82, 0.74),
        occupied_crop=(0.34, 0.43, 0.55, 0.64),
        identity="A one-storey brick-and-stucco Craftsman bungalow has a broad front gable, deep shingled eaves, a smaller cross-gabled porch, tapered timber posts, a raised masonry base and room-scale divided-light sash windows.",
        materials="warm red common brick; pale textured stucco; honey-brown porch timber; white painted sash and fascia; neutral residential glass with warm occupied depth; weathered charcoal asphalt shingles",
        glass_profile="clear_residential_sash_with_warm_room_depth",
        aliases=["calgary_inner_city_bungalow", "bungalow_craftsman_original", "craftsman_brick_bungalow"],
        reuse_keys=["Craftsman Bungalow", "Detached House", "Single-Family Residential"],
        design_lock="10 m by 12 m one-storey house; one broad front-facing main gable, one smaller projecting porch gable, four grounded porch posts, a visible stair and threshold, divided sash, deep eaves and one masonry chimney remain fixed.",
        palette={
            "primary": ("warm red common brick", (144, 72, 48), "stone"),
            "secondary": ("pale textured stucco", (205, 198, 177), "stone"),
            "ornament": ("honey brown porch timber", (116, 76, 43), "wood"),
            "frame": ("white painted sash and fascia", (222, 220, 207), "wood"),
            "glass": ("neutral residential glass", (103, 126, 126), "glass"),
            "roof": ("weathered charcoal asphalt shingle", (77, 73, 67), "stone"),
        },
        material_crops={"primary": (0.30, 0.43, 0.43, 0.61), "secondary": (0.20, 0.42, 0.30, 0.61), "ornament": (0.60, 0.39, 0.71, 0.62), "roof": (0.31, 0.23, 0.58, 0.36)},
        development_type="residential_single_family",
        aesthetic="craftsman_bungalow",
    ),
    "red-brick-edwardian-foursquare": _spec(
        archetype_id="edwardian_foursquare",
        variant_id="classic_red_brick_foursquare",
        label="Red-Brick Edwardian Foursquare",
        shape="edwardian_foursquare",
        native=(11.0, 13.0, 9.5),
        floors=2,
        min_floors=1,
        max_floors=3,
        floor_height=3.05,
        podium_height=3.05,
        crown_height=0.35,
        roof_height=3.0,
        catalogue_slug="edwardian-foursquare",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/edwardian-foursquare/variant_0.png",
        building_crop=(0.19, 0.06, 0.87, 0.83),
        occupied_crop=(0.40, 0.30, 0.58, 0.53),
        identity="A compact two-storey red-brick foursquare sits beneath one deep hipped roof and front dormer, with a full-width timber porch, stout classical posts, stone lintels and sills, tall divided sash and a side chimney.",
        materials="warm pressed red brick; pale limestone lintels and sills; dark stained porch timber; cream painted sash and columns; neutral heritage glass with warm room depth; dark brown asphalt shingle roof",
        glass_profile="heritage_double_hung_sash_with_warm_room_depth",
        aliases=["edwardian_foursquare", "classic_red_brick_foursquare", "red_brick_edwardian_foursquare"],
        reuse_keys=["Edwardian Foursquare", "Detached House", "Single-Family Residential"],
        design_lock="11 m by 13 m, two occupied storeys; one square red-brick body, deep four-sided hip, centred front dormer, continuous full-width porch, symmetrical stair and tall vertically proportioned sash remain one composition.",
        palette={
            "primary": ("warm pressed red brick", (151, 72, 48), "stone"),
            "secondary": ("pale limestone sill and lintel", (190, 181, 159), "stone"),
            "ornament": ("dark stained porch timber", (83, 53, 36), "wood"),
            "frame": ("cream painted sash and column", (222, 215, 194), "wood"),
            "glass": ("neutral heritage sash glass", (104, 126, 125), "glass"),
            "roof": ("dark brown asphalt shingle", (72, 61, 52), "stone"),
        },
        material_crops={"primary": (0.38, 0.34, 0.60, 0.60), "secondary": (0.37, 0.31, 0.57, 0.40), "ornament": (0.39, 0.62, 0.66, 0.76), "roof": (0.35, 0.10, 0.63, 0.25)},
        development_type="residential_single_family",
        aesthetic="edwardian_foursquare",
    ),
    "plateau-stone-montreal-duplex": _spec(
        archetype_id="montreal_duplex",
        variant_id="montreal_duplex_plateau",
        label="Plateau Stone Montreal Duplex",
        shape="montreal_duplex",
        native=(9.0, 12.0, 7.2),
        floors=2,
        min_floors=2,
        max_floors=3,
        floor_height=3.05,
        podium_height=3.05,
        crown_height=0.7,
        roof_height=0.35,
        catalogue_slug="montreal-duplex",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/montreal-duplex/variant_0.png",
        building_crop=(0.10, 0.12, 0.90, 0.85),
        occupied_crop=(0.42, 0.27, 0.61, 0.56),
        identity="A two-storey pale-grey Montreal stone duplex has paired shallow canted bays, tall sash, a flat corniced roof and an unmistakable black steel exterior stair rising from the sidewalk to the upper dwelling.",
        materials="pale grey Montreal limestone; smooth pale stone trim; black painted steel stair and guards; charcoal sash frames; neutral heritage glass with warm occupied depth; dark flat membrane roof",
        glass_profile="clear_heritage_sash_with_warm_duplex_depth",
        aliases=["montreal_duplex", "montreal_duplex_plateau", "plateau_stone_montreal_duplex"],
        reuse_keys=["Montreal Duplex", "Duplex", "Missing Middle Housing"],
        design_lock="9 m by 12 m, two occupied levels; paired shallow stone bays, two independent ground thresholds, one complete exterior steel stair and landing, flat roof cornice and narrow party-lot proportions remain fixed.",
        palette={
            "primary": ("pale grey Montreal limestone", (166, 164, 153), "stone"),
            "secondary": ("smooth pale stone trim", (196, 191, 177), "stone"),
            "ornament": ("black painted exterior stair steel", (43, 45, 44), "metal"),
            "frame": ("charcoal sash and guard frame", (52, 55, 54), "metal"),
            "glass": ("neutral heritage glazing", (105, 125, 124), "glass"),
            "roof": ("dark flat membrane", (66, 66, 63), "stone"),
        },
        material_crops={"primary": (0.29, 0.32, 0.45, 0.58), "secondary": (0.55, 0.28, 0.68, 0.52), "ornament": (0.48, 0.46, 0.64, 0.76), "roof": (0.36, 0.14, 0.65, 0.24)},
        development_type="residential_duplex",
        aesthetic="montreal_plateau_stone",
    ),
    "victorian-brick-rowhouse-terrace": _spec(
        archetype_id="toronto_brick_rowhouse",
        variant_id="toronto_rowhouse_victorian",
        label="Victorian Brick Rowhouse Terrace",
        shape="victorian_rowhouse",
        native=(22.0, 12.0, 9.0),
        floors=2,
        min_floors=2,
        max_floors=3,
        floor_height=3.1,
        podium_height=3.1,
        crown_height=0.8,
        roof_height=2.0,
        catalogue_slug="toronto-brick-rowhouse",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/toronto-brick-rowhouse/variant_0.png",
        building_crop=(0.12, 0.12, 0.94, 0.84),
        occupied_crop=(0.38, 0.32, 0.55, 0.56),
        identity="A four-home Victorian brick terrace forms a continuous streetwall of warm red masonry, projecting party-wall piers, stone-trimmed tall sash, individual stoops and recessed doors, alternating parapets and steep front gables.",
        materials="warm red Toronto brick; pale grey sandstone trim; black painted stoop rails; dark bronze sash and door frames; neutral residential glass with varied occupied rooms; dark slate and membrane roofs",
        glass_profile="heritage_rowhouse_sash_with_varied_room_depth",
        aliases=["toronto_brick_rowhouse", "toronto_rowhouse_victorian", "victorian_brick_rowhouse_terrace"],
        reuse_keys=["Victorian Rowhouse", "Brick Terrace", "Missing Middle Housing"],
        design_lock="22 m by 12 m two-storey terrace; exactly four complete dwellings repeat as whole 5.5 m bays with party-wall piers, separate stoops and doors, tall sash and alternating gabled/parapeted roof ends.",
        palette={
            "primary": ("warm red Toronto brick", (142, 68, 45), "stone"),
            "secondary": ("pale grey sandstone trim", (180, 174, 158), "stone"),
            "ornament": ("black painted stoop rail", (44, 45, 43), "metal"),
            "frame": ("dark bronze sash and door frame", (63, 53, 42), "wood"),
            "glass": ("neutral residential glazing", (104, 123, 121), "glass"),
            "roof": ("dark slate and membrane roof", (63, 64, 62), "stone"),
        },
        material_crops={"primary": (0.34, 0.30, 0.56, 0.57), "secondary": (0.33, 0.34, 0.54, 0.45), "ornament": (0.58, 0.60, 0.76, 0.78), "roof": (0.50, 0.16, 0.75, 0.29)},
        development_type="residential_rowhouse",
        aesthetic="victorian_brick_terrace",
    ),
    "new-law-brick-walkup": _spec(
        archetype_id="new_york_walk_up_tenement",
        variant_id="tenement_new_law",
        label="New-Law Brick Walk-Up Apartments",
        shape="new_law_tenement",
        native=(24.0, 20.0, 18.5),
        floors=5,
        min_floors=4,
        max_floors=6,
        floor_height=3.15,
        podium_height=3.5,
        crown_height=1.0,
        roof_height=0.45,
        catalogue_slug="new-york-walk-up-tenement",
        catalogue_variant_index=1,
        source_path="archetypes/buildings/new-york-walk-up-tenement/variant_1.png",
        building_crop=(0.08, 0.07, 0.98, 0.86),
        occupied_crop=(0.43, 0.24, 0.62, 0.49),
        identity="A five-storey red-brick corner walk-up combines a dark framed retail base, repetitive stone-trimmed sash, projecting metal fire escapes, a deep bracketed cornice and complete secondary street and rear elevations.",
        materials="aged warm red brick; carved brownstone lintels and cornice; black painted fire-escape steel; dark bronze storefront and sash frames; neutral apartment glass with varied occupied depth; dark built-up roof",
        glass_profile="heritage_apartment_sash_with_varied_occupied_depth",
        aliases=["new_york_walk_up_tenement", "tenement_new_law", "new_law_brick_walkup"],
        reuse_keys=["Walk-Up Apartment", "Brick Tenement", "Mixed-Use Residential"],
        design_lock="24 m by 20 m five-storey corner block; retail bays occupy the complete ground floor, four repetitive residential storeys sit above, two supported fire-escape stacks remain attached to real window bays and a deep bracketed cornice closes both street elevations.",
        palette={
            "primary": ("aged warm red brick", (133, 61, 43), "stone"),
            "secondary": ("carved brownstone trim", (148, 116, 84), "stone"),
            "ornament": ("black fire escape steel", (43, 44, 42), "metal"),
            "frame": ("dark bronze storefront and sash", (50, 47, 41), "metal"),
            "glass": ("neutral apartment glazing", (95, 116, 116), "glass"),
            "roof": ("dark built up roof", (59, 60, 57), "stone"),
        },
        material_crops={"primary": (0.42, 0.24, 0.62, 0.49), "secondary": (0.38, 0.18, 0.69, 0.30), "ornament": (0.59, 0.38, 0.74, 0.63), "roof": (0.40, 0.08, 0.74, 0.17)},
        development_type="residential_multifamily",
        aesthetic="new_york_new_law_tenement",
    ),
    "midcentury-balcony-apartment-slab": _spec(
        archetype_id="west_end_mid_century_tower",
        variant_id="midcentury_balcony_tower",
        label="Mid-Century Balcony Apartment Slab",
        shape="midcentury_balcony_tower",
        native=(20.0, 20.0, 39.0),
        floors=11,
        min_floors=8,
        max_floors=20,
        floor_height=3.15,
        podium_height=3.5,
        crown_height=1.0,
        roof_height=1.2,
        catalogue_slug="west-end-mid-century-tower",
        catalogue_variant_index=2,
        source_path="archetypes/buildings/west-end-mid-century-tower/variant_2.png",
        building_crop=(0.08, 0.00, 0.83, 0.89),
        occupied_crop=(0.37, 0.20, 0.63, 0.46),
        identity="An eleven-storey concrete apartment slab stacks continuous wraparound balcony plates, clear glass rails, dark occupied window walls and vertical perforated breeze-block screens above a transparent neighbourhood retail lobby.",
        materials="warm exposed concrete slabs; red-brown brick balcony planters; pale perforated concrete breeze block; dark aluminum frames; neutral clear balcony and apartment glass; pale concrete roof canopy and pergola",
        glass_profile="clear_midcentury_balcony_glass_with_deep_apartment_rooms",
        aliases=["west_end_mid_century_tower", "midcentury_balcony_tower", "midcentury_balcony_apartment_slab"],
        reuse_keys=["Mid-Century Apartment Tower", "Balcony Tower", "Residential High-Rise"],
        design_lock="20 m by 20 m, eleven occupied levels; continuous concrete balcony plates wrap all four sides, alternating perforated screens conceal service zones, planted brick upstands and clear guards stay attached to real slabs and a transparent retail lobby anchors the ground.",
        palette={
            "primary": ("warm exposed concrete slab", (158, 151, 137), "stone"),
            "secondary": ("red brown brick planter", (126, 75, 55), "stone"),
            "ornament": ("pale perforated concrete breeze block", (188, 184, 169), "stone"),
            "frame": ("dark aluminum window frame", (45, 51, 50), "metal"),
            "glass": ("neutral clear balcony and apartment glass", (99, 125, 126), "glass"),
            "roof": ("pale concrete canopy and pergola", (177, 173, 160), "stone"),
        },
        material_crops={"primary": (0.36, 0.25, 0.58, 0.48), "secondary": (0.35, 0.55, 0.60, 0.70), "ornament": (0.19, 0.23, 0.33, 0.54), "roof": (0.18, 0.04, 0.63, 0.13)},
        development_type="residential_highrise",
        aesthetic="midcentury_balcony_modernism",
    ),
    "classic-neighbourhood-strip-mall": _spec(
        archetype_id="commercial_strip_mall",
        variant_id="strip_single_storey_classic",
        label="Classic Neighbourhood Strip Mall",
        shape="classic_strip_mall",
        native=(60.0, 18.0, 7.0),
        floors=1,
        min_floors=1,
        max_floors=2,
        floor_height=4.8,
        podium_height=4.8,
        crown_height=1.1,
        roof_height=0.5,
        catalogue_slug="commercial-strip-mall",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/commercial-strip-mall/variant_0.png",
        building_crop=(0.06, 0.28, 0.95, 0.78),
        occupied_crop=(0.42, 0.48, 0.61, 0.69),
        identity="A one-storey neighbourhood strip mall organizes six complete tenant bays beneath one continuous canopy and stepped stucco parapet, with brick piers, large clear storefronts, individual recessed doors and one taller anchor-store tower.",
        materials="warm beige stucco parapet; red-brown brick piers; pale concrete block base; dark aluminum storefront framing; clear retail glazing with deep occupied shop interiors; charcoal membrane roof and metal coping",
        glass_profile="clear_retail_storefront_with_deep_occupied_shop_depth",
        aliases=["commercial_strip_mall", "strip_single_storey_classic", "classic_neighbourhood_strip_mall"],
        reuse_keys=["Strip Mall", "Neighbourhood Retail", "Convenience Retail"],
        design_lock="60 m by 18 m one-storey retail bar; exactly six complete tenant storefront bays, a continuous supported canopy, brick pier rhythm, individual entries and one taller anchor tower remain fixed while whole tenant bays may repeat.",
        palette={
            "primary": ("warm beige stucco parapet", (190, 169, 133), "stone"),
            "secondary": ("red brown brick pier", (126, 73, 51), "stone"),
            "ornament": ("pale concrete block base", (171, 168, 156), "stone"),
            "frame": ("dark aluminum storefront frame", (52, 57, 56), "metal"),
            "glass": ("clear retail storefront glass", (99, 127, 129), "glass"),
            "roof": ("charcoal membrane and coping", (67, 68, 64), "metal"),
        },
        material_crops={"primary": (0.36, 0.36, 0.64, 0.47), "secondary": (0.51, 0.48, 0.67, 0.64), "ornament": (0.52, 0.64, 0.72, 0.72), "roof": (0.22, 0.30, 0.76, 0.36)},
        development_type="retail_commercial",
        aesthetic="classic_strip_retail",
    ),
    "classic-corner-bodega-mixed-use": _spec(
        archetype_id="new_york_corner_bodega",
        variant_id="bodega_classic",
        label="Classic Corner Bodega Mixed-Use",
        shape="corner_bodega",
        native=(16.0, 18.0, 14.0),
        floors=4,
        min_floors=2,
        max_floors=5,
        floor_height=3.15,
        podium_height=3.5,
        crown_height=0.85,
        roof_height=0.4,
        catalogue_slug="new-york-corner-bodega",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/new-york-corner-bodega/variant_0.png",
        building_crop=(0.27, 0.04, 0.96, 0.91),
        occupied_crop=(0.48, 0.49, 0.77, 0.76),
        identity="A four-storey red-brick corner apartment building wraps a weathered green bodega storefront and awning around both streets, with a chamfered entry, produce-display ledges, tall upper sash, stone trim, fire escapes and a bracketed cornice.",
        materials="aged warm red brick; weathered dark green timber storefront; warm brownstone window trim; black fire-escape steel; clear retail and neutral apartment glass with occupied depth; dark built-up roof",
        glass_profile="clear_corner_retail_and_heritage_apartment_glass",
        aliases=["new_york_corner_bodega", "bodega_classic", "classic_corner_bodega_mixed_use"],
        reuse_keys=["Corner Store", "Bodega", "Mixed-Use Main Street"],
        design_lock="16 m by 18 m four-storey corner building; dark-green storefront and fabric awning wrap both public elevations around one chamfered entry, residential sash align above, a supported fire escape occupies the side and the masonry cornice turns the corner.",
        palette={
            "primary": ("aged warm red brick", (132, 63, 44), "stone"),
            "secondary": ("weathered dark green storefront timber", (61, 83, 58), "wood"),
            "ornament": ("warm brownstone window trim", (141, 112, 83), "stone"),
            "frame": ("black fire escape and storefront frame", (43, 45, 43), "metal"),
            "glass": ("clear retail and apartment glass", (96, 121, 120), "glass"),
            "roof": ("dark built up roof", (61, 61, 58), "stone"),
        },
        material_crops={"primary": (0.53, 0.22, 0.72, 0.45), "secondary": (0.45, 0.50, 0.76, 0.73), "ornament": (0.52, 0.31, 0.72, 0.47), "roof": (0.43, 0.05, 0.78, 0.14)},
        development_type="mixed_use_neighbourhood",
        aesthetic="classic_corner_bodega",
    ),
    "tilt-up-light-industrial-workshop": _spec(
        archetype_id="industrial_park_modernism",
        variant_id="industrial_tilt_up_concrete",
        label="Tilt-Up Light-Industrial Workshop",
        shape="tilt_up_industrial",
        native=(60.0, 35.0, 10.5),
        floors=1,
        min_floors=1,
        max_floors=3,
        floor_height=5.2,
        podium_height=5.2,
        crown_height=0.7,
        roof_height=0.5,
        catalogue_slug="industrial_park_modernism",
        catalogue_variant_index=0,
        source_path="archetypes/buildings/industrial_park_modernism/variant_0.png",
        building_crop=(0.08, 0.17, 0.96, 0.75),
        occupied_crop=(0.23, 0.43, 0.48, 0.62),
        identity="A broad tilt-up concrete light-industrial workshop uses real panel joints and tie holes, a recessed two-storey office entrance, ribbon glazing, four deep loading doors, steel canopies, bollards and a screened flat service roof.",
        materials="warm grey tilt-up concrete panels; darker exposed aggregate base; galvanized loading canopies and bollards; charcoal aluminum office frames; neutral industrial glazing with sparse occupied depth; pale membrane roof and dark coping",
        glass_profile="neutral_industrial_office_glass_with_sparse_occupied_depth",
        aliases=["industrial_park_modernism", "industrial_tilt_up_concrete", "tilt_up_light_industrial_workshop"],
        reuse_keys=["Light Industrial", "Tilt-Up Workshop", "Warehouse and Office"],
        design_lock="60 m by 35 m one-storey industrial envelope; complete tilt-up panel modules and joints wrap all sides, a recessed two-level office marks the public front, exactly four deep loading portals line the service side and every canopy and bollard is grounded.",
        palette={
            "primary": ("warm grey tilt up concrete", (158, 153, 141), "stone"),
            "secondary": ("dark exposed aggregate base", (121, 119, 112), "stone"),
            "ornament": ("galvanized loading steel", (132, 139, 138), "metal"),
            "frame": ("charcoal aluminum office frame", (52, 58, 58), "metal"),
            "glass": ("neutral industrial office glass", (99, 120, 119), "glass"),
            "roof": ("pale membrane and dark coping", (166, 165, 156), "stone"),
        },
        material_crops={"primary": (0.52, 0.31, 0.73, 0.52), "secondary": (0.45, 0.60, 0.70, 0.69), "ornament": (0.78, 0.45, 0.91, 0.66), "roof": (0.37, 0.20, 0.75, 0.30)},
        development_type="industrial_light",
        aesthetic="tilt_up_industrial_modernism",
    ),
    "provincial-brick-neighbourhood-school": _spec(
        archetype_id="ecole_republicaine",
        variant_id="ecole-republicaine-provincial-brick",
        label="Provincial Brick Neighbourhood School",
        shape="provincial_brick_school",
        native=(40.0, 28.0, 22.0),
        floors=3,
        min_floors=2,
        max_floors=4,
        floor_height=3.55,
        podium_height=3.7,
        crown_height=0.8,
        roof_height=3.0,
        catalogue_slug="ecole-republicaine",
        catalogue_variant_index=2,
        source_path="archetypes/buildings/ecole-republicaine/variant_2.png",
        building_crop=(0.04, 0.05, 0.99, 0.94),
        occupied_crop=(0.61, 0.31, 0.79, 0.57),
        identity="A symmetrical three-storey neighbourhood school forms a shallow U around a protected entrance court, with warm brick classroom wings, pale stone base and floor bands, tall grouped windows, pitched metal roofs, an arched gateway and a modest clock-and-bell tower.",
        materials="warm buff-red provincial brick; pale limestone base and bands; patinated copper clock and gateway trim; dark bronze window frames; neutral classroom glazing with occupied depth; weathered standing-seam metal roofs",
        glass_profile="neutral_classroom_glass_with_deep_occupied_learning_spaces",
        aliases=["ecole_republicaine", "ecole-republicaine-provincial-brick", "provincial_brick_neighbourhood_school"],
        reuse_keys=["Neighbourhood School", "Elementary School", "Education"],
        design_lock="40 m by 28 m three-storey shallow-U school; two equal classroom wings and one rear connector define a real court, a central arched gateway remains open beneath a bridge, continuous floor bands align grouped windows and one modest clock tower completes the public axis.",
        palette={
            "primary": ("warm buff red provincial brick", (151, 111, 77), "stone"),
            "secondary": ("pale limestone base and band", (191, 184, 166), "stone"),
            "ornament": ("patinated copper clock and gate trim", (77, 116, 105), "metal"),
            "frame": ("dark bronze classroom frame", (58, 54, 47), "metal"),
            "glass": ("neutral classroom glazing", (103, 123, 122), "glass"),
            "roof": ("weathered standing seam metal", (103, 91, 78), "metal"),
        },
        material_crops={"primary": (0.64, 0.30, 0.79, 0.54), "secondary": (0.63, 0.57, 0.80, 0.69), "ornament": (0.35, 0.05, 0.54, 0.22), "roof": (0.34, 0.13, 0.66, 0.30)},
        development_type="institutional_education",
        aesthetic="provincial_brick_school",
    ),
}


def with_family(family: str) -> dict:
    config = dict(FAMILIES[family])
    config["family"] = family
    return config
