"""Reference-locked design contracts for the ten Wave 15 LEGO families.

Wave 15 balances breadth and depth: seven variants represent previously
uncovered catalogue parents and three are materially distinct siblings of
already represented parents.  Every entry remains an independent geometry,
material, glazing, roof, entrance, and footprint contract.
"""
from __future__ import annotations


GOALPOST_CELLS = {
    "front-elevation-source-v1.png": (0.002, 0.002, 0.498, 0.498),
    "street-hero-source-v1.png": (0.502, 0.002, 0.998, 0.498),
    "rear-corner-source-v1.png": (0.002, 0.502, 0.498, 0.998),
    "aerial-roof-source-v1.png": (0.502, 0.502, 0.998, 0.998),
}

MATERIAL_CELLS = {
    "material-a-source-v1.png": (0.002, 0.002, 0.331, 0.498),
    "material-b-source-v1.png": (0.335, 0.002, 0.665, 0.498),
    "material-c-source-v1.png": (0.669, 0.002, 0.998, 0.498),
    "material-d-source-v1.png": (0.002, 0.502, 0.331, 0.998),
    "occupied-depth-source-v1.png": (0.335, 0.502, 0.665, 0.998),
    "material-f-source-v1.png": (0.669, 0.502, 0.998, 0.998),
}


def _spec(
    *,
    archetype_id: str,
    variant_id: str,
    label: str,
    shape: str,
    cohort: str,
    native: tuple[float, float, float],
    floors: int,
    min_floors: int,
    max_floors: int,
    floor_height: float,
    podium_height: float,
    crown_height: float,
    roof_height: float,
    catalogue_slug: str,
    catalogue_variant_index: int,
    identity: str,
    materials: str,
    glass_profile: str,
    aliases: list[str],
    reuse_keys: list[str],
    design_lock: str,
    palette: dict[str, tuple[str, tuple[int, int, int], str]],
    avoid: str,
    development_type: str,
    aesthetic: str,
) -> dict:
    return {
        "archetype_id": archetype_id,
        "variant_id": variant_id,
        "label": label,
        "shape": shape,
        "cohort": cohort,
        "native": native,
        "native_floors": floors,
        "min_floors": min_floors,
        "max_floors": max_floors,
        "floor_height": floor_height,
        "podium_height": podium_height,
        "crown_height": crown_height,
        "roof_height": roof_height,
        "catalogue_slug": catalogue_slug,
        "catalogue_variant_index": catalogue_variant_index,
        "identity": identity,
        "material_zones": materials,
        "glass_profile": glass_profile,
        "aliases": aliases,
        "reuse_keys": reuse_keys,
        "design_lock": design_lock,
        "palette": palette,
        "avoid": avoid,
        "development_type": development_type,
        "aesthetic": aesthetic,
    }


FAMILIES: dict[str, dict] = {
    "copenhill-ski-slope-energy-plant": _spec(
        archetype_id="waste_to_energy_plant",
        variant_id="wte_ski_slope",
        label="Waste-to-Energy Plant - Inhabited Ski Slope",
        shape="ski_slope_energy_plant",
        cohort="uncovered_parent",
        native=(160.0, 70.0, 85.0),
        floors=7,
        min_floors=3,
        max_floors=12,
        floor_height=5.0,
        podium_height=8.0,
        crown_height=1.2,
        roof_height=46.0,
        catalogue_slug="waste_to_energy_plant",
        catalogue_variant_index=0,
        identity="A monumental silver waste-to-energy plant rises beneath one continuous inhabited green ski slope, climbing from a low public forecourt to a tall industrial summit beside a faceted white emissions stack; a multicolour climbing wall and diagonal aluminum cassette field make the long elevation civic rather than utilitarian.",
        materials="checkerboard brushed and perforated aluminum cassettes; planted and synthetic-turf ski slope with real edge rails; pale exposed concrete process base; graphite industrial steel; neutral high-transmission visitor glazing; warm occupied control-room depth; white ceramic-coated emissions stack and dark service roof",
        glass_profile="neutral_high_transmission_industrial_visitor_glass_with_control_room_depth",
        aliases=["waste_to_energy_plant", "wte_ski_slope", "copenhill_ski_slope_energy_plant", "inhabited_energy_landscape"],
        reuse_keys=["Inhabited Ski Slope Energy Plant", "Civic Waste to Energy Landscape", "Aluminum Climbing Wall Power Plant"],
        design_lock="160 m by 70 m industrial envelope; one uninterrupted skiable roof rises diagonally from the public front edge to the high rear process block, the long side is a silver triangular-cassette climbing wall, and a separate faceted white stack reaches the 85 m summit without becoming a generic chimney pasted onto a box",
        palette={
            "primary": ("brushed and perforated silver aluminum cassette field", (151, 158, 158), "metal"),
            "secondary": ("green planted ski slope and pale aggregate path", (88, 122, 67), "plant"),
            "ornament": ("colour-coded climbing holds on dark perforated backing", (156, 77, 51), "stone"),
            "frame": ("graphite industrial structural steel", (52, 57, 58), "metal"),
            "glass": ("neutral visitor and control-room glass", (102, 123, 122), "glass"),
            "roof": ("white ceramic stack cladding and charcoal service membrane", (206, 207, 199), "metal"),
        },
        avoid="generic factory box, flat green roof, detached ramp, grass pasted on a vertical wall, tiny chimney, blue mirror curtain wall, smokestack plume, fantasy mountain",
        development_type="energy_infrastructure",
        aesthetic="inhabited_energy_landscape",
    ),
    "parametric-wave-natatorium": _spec(
        archetype_id="aquatic_natatorium_complex",
        variant_id="parametric_wave_shell",
        label="Aquatic Natatorium - Parametric Wave Shell",
        shape="wave_shell_natatorium",
        cohort="uncovered_parent",
        native=(82.0, 56.0, 35.0),
        floors=2,
        min_floors=1,
        max_floors=2,
        floor_height=5.4,
        podium_height=5.8,
        crown_height=0.9,
        roof_height=23.0,
        catalogue_slug="aquatic-natatorium-complex",
        catalogue_variant_index=0,
        identity="A broad public natatorium is enclosed by a continuous asymmetric wave shell whose translucent silver polycarbonate crest lifts above a full-height glazed gable; branching concrete struts, twin cable masts, roof ribs, and a visible blue pool hall form one credible long-span structure.",
        materials="translucent platinum polycarbonate roof panels; cool board-formed concrete plinth and branching struts; stainless cable stays; silver aluminum pressure caps; neutral low-iron pool-hall glass; occupied aquatic-hall depth with blue water and warm soffits; pale standing-seam service roof",
        glass_profile="high_transmission_low_iron_pool_hall_glass_with_blue_water_depth",
        aliases=["aquatic_natatorium_complex", "parametric_wave_shell", "parametric_wave_natatorium", "cable_stayed_aquatic_shell"],
        reuse_keys=["Parametric Wave Shell Natatorium", "Cable Stayed Aquatic Hall", "Translucent Wave Pool Complex"],
        design_lock="82 m by 56 m, two occupied public levels; one smooth asymmetric wave roof spans the pool hall, its high crest and low eaves remain continuous through front, rear and sides, diagonal concrete struts meet real roof nodes, twin masts carry visible stays, and the glazed gable reveals the pool rather than an opaque room card",
        palette={
            "primary": ("platinum translucent polycarbonate standing panels", (184, 194, 194), "glass"),
            "secondary": ("cool board-formed architectural concrete", (169, 171, 168), "stone"),
            "ornament": ("stainless cable and node hardware", (133, 141, 143), "metal"),
            "frame": ("silver aluminum curtain-wall pressure cap", (116, 128, 130), "metal"),
            "glass": ("neutral low-iron aquatic hall glass", (112, 145, 151), "glass"),
            "roof": ("pale silver service metal and translucent crest", (158, 166, 166), "metal"),
        },
        avoid="rectangular sports box, repeated sawtooth sheds, disconnected roof shards, opaque blue window wall, unsupported wave canopy, fantasy waterpark, generic barrel vault",
        development_type="institutional_health",
        aesthetic="parametric_wave_shell",
    ),
    "second-empire-clocktower-city-hall": _spec(
        archetype_id="second_empire_civic_building",
        variant_id="grand_city_hall_tower",
        label="Second Empire Civic Building - Grand Clocktower City Hall",
        shape="second_empire_city_hall",
        cohort="uncovered_parent",
        native=(62.0, 44.0, 58.0),
        floors=5,
        min_floors=3,
        max_floors=6,
        floor_height=4.1,
        podium_height=5.0,
        crown_height=2.0,
        roof_height=11.5,
        catalogue_slug="second-empire-civic-building",
        catalogue_variant_index=0,
        identity="A symmetrical pale-limestone city hall steps around a deep arched civic portal, four occupied storeys, a slate mansard attic, corner turrets and a central clock tower capped by a patinated-copper dome; balustrades, dormers, chimneys and the broad ceremonial stair complete the public silhouette.",
        materials="pale grey limestone ashlar; charcoal-blue slate mansard and turret caps; carved limestone quoins, cornices and balustrades; dark bronze heritage sash; neutral lightly reflective glazing; warm occupied civic rooms; green patinated copper clock dome and lead flashing",
        glass_profile="neutral_heritage_sash_with_warm_civic_room_depth",
        aliases=["second_empire_civic_building", "grand_city_hall_tower", "second_empire_clocktower_city_hall", "copper_dome_civic_palace"],
        reuse_keys=["Grand Second Empire City Hall", "Copper Dome Clocktower Civic Palace", "Limestone Mansard Municipal Hall"],
        design_lock="62 m by 44 m, four principal wall levels plus one occupied mansard; nine-bay symmetrical front with a fixed triple-arched portal and stair, projecting centre and end pavilions, four corner turrets, separate dormers and chimneys, and one central clock tower whose copper dome reaches 52 m",
        palette={
            "primary": ("pale grey limestone ashlar with fine mortar joints", (187, 184, 174), "stone"),
            "secondary": ("charcoal blue natural slate mansard", (57, 66, 71), "stone"),
            "ornament": ("carved limestone cornice balustrade and quoin", (205, 199, 184), "stone"),
            "frame": ("dark bronze heritage sash and door metal", (66, 55, 43), "metal"),
            "glass": ("neutral lightly reflective civic glazing", (105, 119, 116), "glass"),
            "roof": ("green patinated copper dome and lead flashing", (74, 128, 112), "metal"),
        },
        avoid="generic courthouse box, classical temple portico, flat roof, missing mansard, tiny clock tower, bright orange copper, blank side wings, pasted dormers",
        development_type="institutional",
        aesthetic="second_empire_grand_civic",
    ),
    "glass-greenhouse-vertical-farm": _spec(
        archetype_id="vertical_farm",
        variant_id="farm_glass_greenhouse_tower",
        label="Vertical Farm - Glass Greenhouse Tower",
        shape="greenhouse_vertical_farm",
        cohort="uncovered_parent",
        native=(36.0, 34.0, 112.0),
        floors=30,
        min_floors=5,
        max_floors=50,
        floor_height=3.45,
        podium_height=5.2,
        crown_height=1.5,
        roof_height=4.5,
        catalogue_slug="vertical_farm",
        catalogue_variant_index=0,
        identity="A thirty-level greenhouse tower exposes stacked hydroponic growing trays, circulation cores, robotic rails and dense living crops behind exceptionally clear glass, with alternating double-height winter gardens, silver exoskeletal braces and a vented greenhouse crown.",
        materials="high-transmission low-iron greenhouse glass; silver galvanized steel mullions and diagonal braces; pale concrete growing decks; deep green hydroponic crops; graphite robotic rails; warm occupied cultivation depth; translucent vented greenhouse roof",
        glass_profile="ultra_clear_greenhouse_glass_revealing_hydroponic_depth",
        aliases=["vertical_farm", "farm_glass_greenhouse_tower", "glass_greenhouse_vertical_farm", "stacked_hydroponic_tower"],
        reuse_keys=["Glass Greenhouse Vertical Farm", "Stacked Hydroponic Tower", "Thirty Storey Urban Greenhouse"],
        design_lock="36 m by 34 m, thirty occupied cultivation levels grouped into ten three-storey greenhouse bays; clear continuous corners, visible pale decks and varied green crop trays, alternating double-height winter gardens, three giant integrated exoskeletal X-fields, two service cores and one vented greenhouse crown without opaque office spandrels",
        palette={
            "primary": ("deep green living hydroponic crop beds", (61, 119, 60), "plant"),
            "secondary": ("pale concrete cultivation deck edges", (184, 185, 178), "stone"),
            "ornament": ("graphite robotic rail and irrigation hardware", (55, 63, 62), "metal"),
            "frame": ("silver galvanized greenhouse framing", (133, 143, 142), "metal"),
            "glass": ("ultra-clear low-iron greenhouse glass", (126, 158, 153), "glass"),
            "roof": ("translucent vented greenhouse crown", (163, 181, 176), "glass"),
        },
        avoid="blue mirror office tower, green wallpaper, identical plant stripe every floor, opaque spandrel box, sealed roof, missing deck depth, fantasy tree skyscraper",
        development_type="industrial",
        aesthetic="transparent_vertical_agriculture",
    ),
    "steel-rib-intermodal-hub": _spec(
        archetype_id="intermodal_transit_hub",
        variant_id="sculptural_steel_exoskeleton",
        label="Intermodal Transit Hub - Sculptural Steel Exoskeleton",
        shape="steel_rib_transit_hub",
        cohort="uncovered_parent",
        native=(65.0, 100.0, 37.0),
        floors=3,
        min_floors=2,
        max_floors=4,
        floor_height=5.4,
        podium_height=6.0,
        crown_height=1.0,
        roof_height=19.0,
        catalogue_slug="intermodal-transit-hub",
        catalogue_variant_index=0,
        identity="A glazed intermodal concourse is sheltered by two immense parabolic white-steel arches and a continuous fan of branching ribs, all landing on visible structural shoes above a warm brick-and-glass plinth; the luminous central nave remains open from entry to platforms.",
        materials="satin white structural steel ribs and cast nodes; warm red-brown civic brick plinth; clear low-iron concourse glass; silver pressure caps; pale terrazzo platform deck; warm occupied station depth; translucent ETFE and glass roof strips",
        glass_profile="high_transmission_station_glass_with_deep_luminous_concourse",
        aliases=["intermodal_transit_hub", "sculptural_steel_exoskeleton", "steel_rib_intermodal_hub", "parabolic_arch_transit_concourse"],
        reuse_keys=["Steel Rib Intermodal Hub", "Parabolic Arch Transit Concourse", "White Exoskeleton Station"],
        design_lock="65 m by 100 m, three public levels; the narrow glazed gable is the front facade and the complete nave runs deep along the long axis, with a lower brick plinth beneath two longitudinal parabolic arches, twenty-four paired fan ribs connecting arch nodes to real perimeter shoes, roof glazing between ribs, and an unobstructed central entry and platform axis",
        palette={
            "primary": ("satin white structural steel rib and node", (211, 214, 209), "metal"),
            "secondary": ("warm red brown civic brick plinth", (125, 76, 55), "stone"),
            "ornament": ("pale terrazzo platform and stair", (183, 181, 169), "stone"),
            "frame": ("silver aluminum curtain-wall cap", (119, 130, 130), "metal"),
            "glass": ("neutral low-iron concourse glass", (112, 140, 140), "glass"),
            "roof": ("translucent ETFE and laminated roof glass", (169, 185, 181), "glass"),
        },
        avoid="generic airport box, loose decorative ribs, ribs ending in mid-air, sealed central nave, blue mirror glass, identical simple barrel vault, opaque roof",
        development_type="transit_station",
        aesthetic="sculptural_structural_expressionism",
    ),
    "monumental-silo-cluster": _spec(
        archetype_id="machine_aesthetic_heavy_industrial",
        variant_id="heavy_silo_cluster",
        label="Machine-Aesthetic Heavy Industrial - Monumental Silo Cluster",
        shape="monumental_silo_cluster",
        cohort="uncovered_parent",
        native=(82.0, 55.0, 62.0),
        floors=8,
        min_floors=1,
        max_floors=10,
        floor_height=4.2,
        podium_height=5.5,
        crown_height=1.0,
        roof_height=7.0,
        catalogue_slug="machine_aesthetic_heavy_industrial",
        catalogue_variant_index=2,
        identity="Eight monumental cylindrical silos rise as two connected banks beneath conical caps, a glazed conveyor headhouse and elevated truss galleries; external stairs, catwalks, pipes, hoppers and a low loading hall make every transfer route physically legible.",
        materials="weathered pale concrete silo shells; galvanized corrugated steel caps and headhouse; graphite truss steel and catwalk grating; muted rust process pipes; neutral industrial glazing; warm occupied control depth; dark membrane loading-hall roof",
        glass_profile="neutral_industrial_control_glass_with_sparse_occupied_depth",
        aliases=["machine_aesthetic_heavy_industrial", "heavy_silo_cluster", "monumental_silo_cluster", "connected_bulk_storage_complex"],
        reuse_keys=["Monumental Silo Cluster", "Connected Bulk Storage Complex", "Concrete Silo and Conveyor Headworks"],
        design_lock="82 m by 55 m industrial site envelope; exactly eight full-height cylindrical silos in two four-silo banks, each with a conical cap and hopper logic, one elevated glazed headhouse, two enclosed truss galleries, open catwalk guards, external stair towers, process pipes and a separate low loading shed",
        palette={
            "primary": ("weathered pale slip-formed concrete", (153, 151, 142), "stone"),
            "secondary": ("galvanized corrugated steel cap and cladding", (133, 139, 137), "metal"),
            "ornament": ("muted rust process pipe and valve", (123, 69, 47), "metal"),
            "frame": ("graphite truss steel and catwalk grating", (53, 58, 58), "metal"),
            "glass": ("neutral industrial control-room glass", (94, 111, 109), "glass"),
            "roof": ("charcoal loading-hall membrane and metal flashing", (55, 57, 55), "metal"),
        },
        avoid="one giant cylinder, grain-elevator cartoon, random pipe spaghetti, inaccessible floating catwalks, office curtain wall, identical smooth toy silos, missing transfer galleries",
        development_type="industrial_heavy",
        aesthetic="machine_aesthetic_silo_cluster",
    ),
    "titanium-fold-art-museum": _spec(
        archetype_id="large_art_museum_gallery",
        variant_id="deconstructivist_titanium_pavilion",
        label="Large Art Museum - Folded Titanium Pavilion",
        shape="titanium_fold_museum",
        cohort="uncovered_parent",
        native=(88.0, 64.0, 34.0),
        floors=4,
        min_floors=2,
        max_floors=5,
        floor_height=4.6,
        podium_height=5.2,
        crown_height=1.0,
        roof_height=10.0,
        catalogue_slug="large-art-museum-gallery",
        catalogue_variant_index=0,
        identity="A civic art museum is composed from five colliding but continuously clad titanium-zinc gallery volumes, including two rolled shells, three folded wedges, a glazed central canyon and one suspended rectilinear gallery bridge above a deep public entry.",
        materials="small-scale matte titanium-zinc shingles; silver perforated metal screen; pale architectural concrete plinth; charcoal steel shadow joints; neutral low-iron atrium glass; warm occupied gallery and lobby depth; dark zinc roof seams and concealed drainage",
        glass_profile="neutral_low_iron_museum_atrium_glass_with_deep_gallery_depth",
        aliases=["large_art_museum_gallery", "deconstructivist_titanium_pavilion", "titanium_fold_art_museum", "sculptural_metal_gallery_canyon"],
        reuse_keys=["Folded Titanium Art Museum", "Sculptural Metal Gallery Canyon", "Deconstructivist Civic Pavilion"],
        design_lock="88 m by 64 m, four occupied gallery levels; five independently legible but joined masses form one weather-tight composition, two are smooth rolled shells, three are sharply folded wedges, a full-height glazed canyon exposes the lobby, and one rectilinear gallery bridge cantilevers above the central entry without becoming a random pile of disconnected shards",
        palette={
            "primary": ("matte titanium zinc shingle field", (160, 164, 161), "metal"),
            "secondary": ("silver perforated metal veil", (131, 138, 137), "metal"),
            "ornament": ("pale architectural concrete plinth", (177, 176, 168), "stone"),
            "frame": ("charcoal steel shadow joint and mullion", (54, 59, 60), "metal"),
            "glass": ("neutral low-iron museum atrium glass", (105, 129, 130), "glass"),
            "roof": ("dark zinc seam and concealed drainage", (78, 82, 81), "metal"),
        },
        avoid="random crumpled foil, disconnected floating shards, generic silver box, blue mirror atrium, paper-thin walls, impossible cantilever, blank rear elevation",
        development_type="institutional",
        aesthetic="deconstructivist_titanium_sculpture",
    ),
    "historic-iron-glass-market": _spec(
        archetype_id="food_hall_market_hall",
        variant_id="market_historic_iron_glass",
        label="Food Hall - Historic Iron and Glass Market",
        shape="historic_iron_glass_market",
        cohort="sibling_variant",
        native=(68.0, 42.0, 24.0),
        floors=2,
        min_floors=1,
        max_floors=3,
        floor_height=4.5,
        podium_height=5.0,
        crown_height=0.8,
        roof_height=12.0,
        catalogue_slug="food_hall_market_hall",
        catalogue_variant_index=0,
        identity="A restored nineteenth-century market hall forms three connected barrel-vaulted iron-and-glass aisles above a red-brick and honey-stone base, with exposed wrought-iron arches, clerestory lanterns, operable end fans, deep arcaded entrances and visible occupied market stalls.",
        materials="weathered red stock brick; honey sandstone spring blocks and plinth; dark green-black wrought and cast iron; slender bronze glazing bars; lightly rippled clear roof glass; warm occupied market-hall depth; patinated zinc ridge caps and stone paving",
        glass_profile="lightly_rippled_clear_market_glass_with_warm_stall_depth",
        aliases=["food_hall_market_hall", "market_historic_iron_glass", "historic_iron_glass_market", "victorian_barrel_vault_market"],
        reuse_keys=["Historic Iron and Glass Market", "Victorian Barrel Vault Food Hall", "Restored Wrought Iron Market"],
        design_lock="68 m by 42 m, one principal market floor plus a narrow mezzanine; three parallel barrel-vaulted aisles share brick party piers and continuous valleys, fourteen exposed iron arch frames carry the glass, each front gable owns a real radial fanlight and arched entry, and warm stalls remain visible through the clear end walls",
        palette={
            "primary": ("weathered red stock brick with lime mortar", (139, 78, 56), "stone"),
            "secondary": ("honey sandstone plinth springer and sill", (181, 151, 104), "stone"),
            "ornament": ("dark green black wrought iron truss and column", (45, 61, 55), "metal"),
            "frame": ("slender aged bronze glazing bar", (88, 72, 52), "metal"),
            "glass": ("lightly rippled clear market-hall glass", (129, 152, 148), "glass"),
            "roof": ("patinated zinc ridge cap and flashing", (105, 125, 117), "metal"),
        },
        avoid="Markthal inhabited arch, generic warehouse shed, one opaque barrel roof, black window wallpaper, missing valleys, sealed entrances, modern shopping mall",
        development_type="commercial_retail",
        aesthetic="victorian_iron_and_glass_market",
    ),
    "bronze-curve-concert-hall": _spec(
        archetype_id="concert_hall_modern",
        variant_id="concert_timber_acoustic",
        label="Modern Concert Hall - Opposing Bronze Acoustic Curves",
        shape="bronze_curve_concert_hall",
        cohort="sibling_variant",
        native=(88.0, 62.0, 35.0),
        floors=4,
        min_floors=2,
        max_floors=8,
        floor_height=4.6,
        podium_height=5.4,
        crown_height=1.0,
        roof_height=13.0,
        catalogue_slug="concert_hall_modern",
        catalogue_variant_index=2,
        identity="Two immense opposing weathered-bronze acoustic walls curl around a warm timber-lined glazed foyer canyon and a solid central auditorium, descending into planted roof terraces at opposite corners while deep entry soffits and balcony edges reveal the public section.",
        materials="weathered bronze standing-seam panels; warm Douglas-fir acoustic lining; charcoal architectural concrete auditorium; dark bronze frames; neutral low-iron foyer glass; warm occupied foyer and balcony depth; planted terrace soil, sedum and black membrane",
        glass_profile="neutral_low_iron_foyer_glass_revealing_timber_acoustic_depth",
        aliases=["concert_hall_modern", "concert_timber_acoustic", "bronze_curve_concert_hall", "opposing_acoustic_wall_civic_hall"],
        reuse_keys=["Bronze Curve Concert Hall", "Opposing Acoustic Wall Civic Hall", "Timber Foyer Bronze Music Venue"],
        design_lock="88 m by 62 m, four public levels; two thick continuous bronze shell walls curve in opposite directions around one central auditorium and glazed foyer canyon, their crests descend toward opposite planted terraces, the entry is carved between them beneath a timber soffit, and all rear edges and roof seams close as one weather-tight building",
        palette={
            "primary": ("weathered bronze standing seam acoustic shell", (116, 85, 58), "metal"),
            "secondary": ("warm Douglas fir acoustic lining", (167, 112, 62), "wood"),
            "ornament": ("charcoal architectural concrete auditorium", (67, 68, 64), "stone"),
            "frame": ("dark bronze foyer mullion", (69, 58, 47), "metal"),
            "glass": ("neutral low-iron foyer glass", (107, 132, 129), "glass"),
            "roof": ("planted terrace sedum and black membrane", (76, 104, 66), "plant"),
        },
        avoid="white organic shell sibling, random metal ribbons, generic concert box, paper-thin bronze fins, blue mirror lobby, detached green roof, blank rear wall",
        development_type="recreational",
        aesthetic="weathered_bronze_acoustic_landform",
    ),
    "deconstructivist-concrete-fire-station": _spec(
        archetype_id="modern_fire_station",
        variant_id="fire_deconstructivist",
        label="Modern Fire Station - Deconstructivist Concrete",
        shape="deconstructivist_fire_station",
        cohort="sibling_variant",
        native=(52.0, 36.0, 28.0),
        floors=3,
        min_floors=1,
        max_floors=3,
        floor_height=4.2,
        podium_height=5.4,
        crown_height=0.8,
        roof_height=7.0,
        catalogue_slug="modern_fire_station",
        catalogue_variant_index=0,
        identity="A raw-concrete fire station is assembled as one angular apparatus hall cut by three deep red engine bays, a folded crew wing and a leaning hose-drying tower whose narrow vertical slit and roof beacon complete an intentionally off-axis but structurally grounded civic composition.",
        materials="raw board-formed concrete; charcoal fibre-cement crew wing; deep fire-red insulated apparatus doors; blackened steel lintels and rails; neutral clear operations glazing; warm occupied crew and watch-room depth; dark zinc folded roof and red beacon metal",
        glass_profile="neutral_clear_operations_glass_with_deep_crew_room_depth",
        aliases=["modern_fire_station", "fire_deconstructivist", "deconstructivist_concrete_fire_station", "angular_hose_tower_station"],
        reuse_keys=["Deconstructivist Concrete Fire Station", "Angular Hose Tower Station", "Folded Apparatus Hall"],
        design_lock="52 m by 36 m, three occupied levels; three unobstructed deep apparatus portals occupy the left concrete hall while a ground-to-roof charcoal crew wing and sheltered public entry complete the right side of the front, one tapered and visibly grounded hose tower leans above the roof with a narrow slit, and every angled wall owns real thickness and closed returns",
        palette={
            "primary": ("raw board formed architectural concrete", (142, 140, 133), "stone"),
            "secondary": ("charcoal fibre cement crew wing", (63, 67, 66), "stone"),
            "ornament": ("deep fire red insulated apparatus door", (147, 42, 33), "metal"),
            "frame": ("blackened steel lintel rail and flashing", (46, 50, 50), "metal"),
            "glass": ("neutral clear operations glazing", (101, 121, 119), "glass"),
            "roof": ("dark zinc folded roof and red beacon metal", (64, 70, 70), "metal"),
        },
        avoid="mass timber sibling, ordinary suburban firehouse, concrete box with applied fins, blocked apparatus doors, floating hose tower, arbitrary shards, blue glass",
        development_type="institutional",
        aesthetic="deconstructivist_civic_concrete",
    ),
}


def goalpost_prompt(family: str) -> str:
    spec = FAMILIES[family]
    return f"""Use case: photorealistic-natural
Asset type: render-locked four-view architectural construction board for a CityPrompt LEGO building variant
Primary request: Design one coherent, physically buildable {spec['label']} from the catalogue contract below and show that exact same building in four equal panels in a precise 2 by 2 grid.
Panel 1: dead-front orthographic elevation, complete building visible. Panel 2: pedestrian-height front-right architectural survey oblique. Panel 3: rear-left oblique proving every material and structural system wraps the secondary elevations. Panel 4: high aerial roof-plan oblique proving roof topology, courts, spans, and equipment.
Catalogue contract: {spec['identity']}
Building lock: {spec['design_lock']}.
Scene/backdrop: clean warm-light-grey architectural studio ground and backdrop, no neighbors, trees, cars or people.
Style/medium: premium photoreal architectural survey photography and physically plausible construction reference, not concept art.
Lighting/mood: neutral bright overcast survey illumination with soft contact shadows and controlled glass reflections, consistent in every panel.
Materials/textures: {spec['material_zones']}.
Constraints: exact same coherent building topology, storey datums, structural bays, openings, entrances, material zones and roof in all four panels; credible load paths; real recessed openings and physical screens; thin neutral gutters; whole building in every frame; no labels, text, signs, logos or watermark.
Avoid: {spec['avoid']}; perspective distortion, blank sides, changed geometry between panels, entourage, dramatic sunset."""


def material_prompt(family: str) -> str:
    spec = FAMILIES[family]
    descriptions = [item[0] for item in spec["palette"].values()]
    return f"""Use case: photorealistic-natural
Asset type: shadow-neutral 3 by 2 construction and occupied-depth material board for the exact {spec['label']} shown in Image 1
Input images: Image 1 is the approved four-view geometry, palette, construction-scale and optical authority.
Primary request: Create six equal square straight-on orthographic samples in a precise 3-column by 2-row grid separated only by thin neutral-grey gutters, with no labels.
Top-left: {descriptions[0]}, authentic construction scale and fine micro-detail, no facade or opening.
Top-center: {descriptions[1]}, authentic construction scale and fine micro-detail, no complete building element.
Top-right: {descriptions[2]}, authentic construction scale and fine micro-detail, no complete ornament assembly.
Bottom-left: {descriptions[3]}, authentic construction scale and fine micro-detail, no complete frame, door or screen.
Bottom-center: {descriptions[4]} plus clean occupied depth seen dead-on, with clear floor, ceiling and restrained warm occupation, no exterior frame, mullion, screen, facade or skewed perspective.
Bottom-right: {descriptions[5]}, authentic construction scale and evenly lit, no complete roof scene.
Scene/backdrop: flat evenly lit material-capture setup. Style/medium: premium physically based photoreal architectural construction texture reference.
Lighting: diffuse neutral overcast capture; no directional sunlight, baked shadow, vignette or perspective.
Constraints: exact 3 by 2 grid; every sample fills its cell edge-to-edge; no labels, text, logos or watermark; no complete facade or repeated window grid; match Image 1 exactly.
Avoid: cartoon materials, generic substitutions, oversized motifs, blue mirror glass, dramatic lighting, building perspective, decorative border."""


def with_family(family: str) -> dict:
    config = dict(FAMILIES[family])
    config["family"] = family
    return config
